---
permalink: audit/audit-message-format.html 
sidebar: sidebar 
keywords: storagegrid, audit, message formats, message format 
summary: Los mensajes de auditoría intercambiados dentro del sistema StorageGRID incluyen información estándar común a todos los mensajes y contenido específico que describe el evento o la actividad que se está reportando. 
---
= Formato de mensaje de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los mensajes de auditoría intercambiados dentro del sistema StorageGRID incluyen información estándar común a todos los mensajes y contenido específico que describe el evento o la actividad que se está reportando.

Si la información de resumen proporcionada por link:using-audit-explain-tool.html["auditoría-explicar"]las herramientas y link:using-audit-sum-tool.html["suma de auditoría"]no es suficiente, consulte esta sección para comprender el formato general de todos los mensajes de auditoría.

El siguiente es un mensaje de auditoría de ejemplo que puede aparecer en el archivo de registro de auditoría:

[listing]
----
2014-07-17T03:50:47.484627
[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][ATYP(FC32):SYSU][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Cada mensaje de auditoría contiene una cadena de elementos de atributo. Toda la cadena está entre paréntesis (`[ ]`), y cada elemento de atributo de la cadena tiene las siguientes características:

* Encerrado entre paréntesis `[ ]`
* Introducido por la cadena `AUDT`, que indica un mensaje de auditoría
* Sin delimitadores (sin comas o espacios) antes o después
* Terminado por un carácter de salto de línea `\n`


Cada elemento incluye un código de atributo, un tipo de datos y un valor que se informa en este formato:

[listing]
----
[ATTR(type):value][ATTR(type):value]...
[ATTR(type):value]\n
----
El número de elementos de atributo del mensaje depende del tipo de evento del mensaje. Los elementos de atributo no aparecen en ningún orden en particular.

En la siguiente lista se describen los elementos del atributo:

* `ATTR` es un código de cuatro caracteres para el atributo que se informa. Hay algunos atributos que son comunes a todos los mensajes de auditoría y a otros que son específicos de eventos.
* `type` Es un identificador de cuatro caracteres del tipo de datos de programación del valor, como UI64, FC32, etc. El tipo está entre paréntesis `( )`.
* `value` es el contenido del atributo, normalmente un valor numérico o de texto. Los valores siempre siguen a dos puntos (`:`). Los valores del tipo de dato CSTR están rodeados por comillas dobles.

