---
permalink: audit/audit-messages-main.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message 
summary: En las secciones siguientes se enumeran descripciones detalladas de los mensajes de auditoría devueltos por el sistema. Cada mensaje de auditoría aparece primero en una tabla que agrupa los mensajes relacionados por la clase de actividad que representa el mensaje. Estas agrupaciones son útiles tanto para comprender los tipos de actividades auditadas como para seleccionar el tipo deseado de filtrado de mensajes de auditoría. 
---
= Descripciones de mensajes de auditoría
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En las secciones siguientes se enumeran descripciones detalladas de los mensajes de auditoría devueltos por el sistema. Cada mensaje de auditoría aparece primero en una tabla que agrupa los mensajes relacionados por la clase de actividad que representa el mensaje. Estas agrupaciones son útiles tanto para comprender los tipos de actividades auditadas como para seleccionar el tipo deseado de filtrado de mensajes de auditoría.

Los mensajes de auditoría también se enumeran alfabéticamente por sus códigos de cuatro caracteres. Esta lista alfabética le permite buscar información sobre mensajes específicos.

Los códigos de cuatro caracteres utilizados en este capítulo son los valores ATYP que se encuentran en los mensajes de auditoría, como se muestra en el siguiente mensaje de ejemplo:

[listing, subs="specialcharacters,quotes"]
----
2014-07-17T03:50:47.484627
\[AUDT:[RSLT(FC32):VRGN][AVER(UI32):10][ATIM(UI64):1405569047484627][*ATYP\(FC32\):SYSU*][ANID(UI32):11627225][AMID(FC32):ARNI][ATID(UI64):9445736326500603516]]
----
Para obtener información sobre cómo configurar los niveles de mensajes de auditoría, cambiar los destinos de los registros y usar un servidor syslog externo para su información de auditoría, consultelink:../monitor/configure-log-management.html["Configurar la gestión de registros y el servidor syslog externo"]
