---
permalink: audit/ebdl-empty-bucket-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, EBDL, Empty Bucket Delete 
summary: 'El análisis de ILM eliminó un objeto de un bloque que elimina todos los objetos (mediante una operación de bloque vacío).' 
---
= EBDL: Eliminación de bloque vacío
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El análisis de ILM eliminó un objeto de un bloque que elimina todos los objetos (mediante una operación de bloque vacío).

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
CSIZ
 a| 
Tamaño del objeto
 a| 
El tamaño del objeto en bytes.



 a| 
RUTA
 a| 
S3 Cubo/llave
 a| 
El nombre del cubo S3 y el nombre de la clave S3.



 a| 
SEGC
 a| 
UUID del contenedor
 a| 
UUID del contenedor del objeto segmentado. Este valor sólo está disponible si el objeto está segmentado.



 a| 
UUID
 a| 
Identificador único universal
 a| 
El identificador del objeto dentro del sistema StorageGRID.



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Resultado de la operación de supresión
 a| 
El resultado del evento, proceso o transacción. Si no es relevante para un mensaje, NO SE utiliza NINGUNO en lugar de SUCS para que el mensaje no se filtre accidentalmente.

|===