---
permalink: audit/gtst-grid-task-started.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTST, Grid Task Started 
summary: Este mensaje de auditoría indica que el servicio CMN ha comenzado a procesar la tarea de cuadrícula especificada. El mensaje de auditoría sigue inmediatamente el mensaje tarea de cuadrícula enviada para las tareas de cuadrícula iniciadas por el servicio de envío de tareas de cuadrícula interna y seleccionadas para la activación automática. Para las tareas de cuadrícula enviadas a la tabla pendiente, este mensaje se genera cuando el usuario inicia la tarea de cuadrícula. 
---
= GTST: Se ha iniciado la tarea de cuadrícula
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje de auditoría indica que el servicio CMN ha comenzado a procesar la tarea de cuadrícula especificada. El mensaje de auditoría sigue inmediatamente el mensaje tarea de cuadrícula enviada para las tareas de cuadrícula iniciadas por el servicio de envío de tareas de cuadrícula interna y seleccionadas para la activación automática. Para las tareas de cuadrícula enviadas a la tabla pendiente, este mensaje se genera cuando el usuario inicia la tarea de cuadrícula.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
TSID
 a| 
ID de la tarea
 a| 
Este campo identifica de forma única una tarea de cuadrícula generada y permite gestionar la tarea a lo largo de su ciclo de vida.

*Nota:* el Id. De tarea se asigna en el momento en que se genera una tarea de cuadrícula, no en el momento en que se envía. Es posible que una tarea de cuadrícula determinada se envíe varias veces y, en este caso, el campo Id. De tarea no es suficiente para vincular de forma única los mensajes de auditoría enviados, iniciados y terminados.



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Resultado
 a| 
El resultado. Este campo solo tiene un valor:

* SUCS: La tarea de red se inició correctamente.


|===