---
permalink: audit/gtsu-grid-task-submitted.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, GTSU, Grid Task Submitted 
summary: Este mensaje de auditoría indica que se ha enviado una tarea de cuadrícula al servicio CMN. 
---
= GTSU: Se ha enviado la tarea de la cuadrícula
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje de auditoría indica que se ha enviado una tarea de cuadrícula al servicio CMN.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
TSID
 a| 
ID de la tarea
 a| 
Identifica de forma única una tarea de cuadrícula generada y permite gestionar la tarea a lo largo de su ciclo de vida.

*Nota:* el Id. De tarea se asigna en el momento en que se genera una tarea de cuadrícula, no en el momento en que se envía. Es posible que una tarea de cuadrícula determinada se envíe varias veces y, en este caso, el campo Id. De tarea no es suficiente para vincular de forma única los mensajes de auditoría enviados, iniciados y terminados.



 a| 
TTYP
 a| 
Tipo de tarea
 a| 
Tipo de tarea de cuadrícula.



 a| 
TVER
 a| 
Versión de la tarea
 a| 
Número que indica la versión de la tarea de cuadrícula.



 a| 
TDSC
 a| 
Descripción de la tarea
 a| 
Una descripción legible por el usuario de la tarea de cuadrícula.



 a| 
VATS
 a| 
Válido después de la Marca de hora
 a| 
El primer momento (UINT64 microsegundos a partir del 1 de enero de 1970 - tiempo UNIX) en el que es válida la tarea de la cuadrícula.



 a| 
VBTS
 a| 
Válido antes de la Marca de hora
 a| 
La última hora (UINT64 microsegundos a partir del 1 de enero de 1970 - tiempo UNIX) en la que es válida la tarea de la cuadrícula.



 a| 
TSRC
 a| 
Origen
 a| 
El origen de la tarea:

* TXTB: La tarea de la cuadrícula se envió a través del sistema StorageGRID como un bloque de texto firmado.
* CUADRÍCULA: La tarea de la cuadrícula se envió a través del servicio interno de envío de tareas de la cuadrícula.




 a| 
ACTV
 a| 
Tipo de activación
 a| 
Tipo de activación:

* AUTO: La tarea de cuadrícula se envió para la activación automática.
* PEND: La tarea de cuadrícula se ha enviado a la tabla pendiente. Esta es la única posibilidad para la fuente TXTB.




 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Resultado
 a| 
El resultado de la presentación:

* SUCS: La tarea de la red se envió correctamente.
* ERROR: La tarea se ha movido directamente a la tabla histórica.


|===