---
permalink: audit/lkdm-leaked-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup 
summary:  
---
= LKDM: Limpieza de objetos filtrados
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje se genera cuando se limpia o elimina un fragmento filtrado. Un fragmento puede formar parte de un objeto replicado o de un objeto codificado con borrado.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
CLOC
 a| 
Ubicación del segmento
 a| 
Ruta de acceso del archivo del fragmento filtrado que se ha eliminado.



 a| 
CTYP
 a| 
Tipo de segmento
 a| 
Tipo de fragmento:

`ec: Erasure-coded object chunk`

`repl: Replicated object chunk`



 a| 
LLEYP
 a| 
Tipo de fuga
 a| 
Los cinco tipos de fugas que se pueden detectar:

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`



 a| 
CTIM
 a| 
Tiempo de creación de fragmentos
 a| 
Hora en que se creó el fragmento filtrado.



 a| 
UUID
 a| 
Identificador único universal
 a| 
Identificador del objeto al que pertenece el fragmento.



 a| 
CBID
 a| 
Identificador de bloque de contenido
 a| 
CBID del objeto al que pertenece el fragmento filtrado.



 a| 
CSIZ
 a| 
Tamaño de contenido
 a| 
Tamaño del fragmento en bytes.

|===