---
permalink: audit/metadata-update-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, Metadata update, S3 metadata update, SUPD 
summary: Los mensajes de auditoría se generan cuando un cliente S3 actualiza los metadatos de un objeto. 
---
= Mensajes de actualización de metadatos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se generan mensajes de auditoría cuando un cliente S3 actualiza los metadatos de un objeto.



== Mensajes de auditoría de actualización de metadatos S3

[cols="1a,1a,2a,1a,2a"]
|===
| Codificación | Nombre | Descripción | Traza | Consulte 


 a| 
SUPD
 a| 
Metadatos de S3 actualizados
 a| 
Se genera cuando un cliente S3 actualiza los metadatos de un objeto ingerido.
 a| 
CBID, S3KY, HTRH
 a| 
link:supd-s3-metadata-updated.html["SUPD: Se han actualizado metadatos S3"]

|===


== Ejemplo: Actualización de metadatos de S3

El ejemplo muestra una transacción correcta para actualizar los metadatos de un objeto S3 existente.



=== SUPD: Actualización de metadatos S3

El cliente S3 realiza una solicitud (SUPD) para actualizar los metadatos especificados (`x-amz-meta-\*`) para el objeto S3 (S3KY). En este ejemplo, los encabezados de las solicitudes se incluyen en el campo HTRH porque se ha configurado como encabezado de protocolo de auditoría (**CONFIGURACIÓN** > **Supervisión** > **servidor de auditoría y syslog**). Consulte link:../monitor/configure-audit-messages.html["Configure los mensajes de auditoría y el servidor de syslog externo"].

[listing]
----
2017-07-11T21:54:03.157462 [AUDT:[RSLT(FC32):SUCS][TIME(UI64):17631][SAIP(IPAD):"10.96.100.254"]
[HTRH(CSTR):"{\"accept-encoding\":\"identity\",\"authorization\":\"AWS LIUF17FGJARQHPY2E761:jul/hnZs/uNY+aVvV0lTSYhEGts=\",
\"content-length\":\"0\",\"date\":\"Tue, 11 Jul 2017 21:54:03 GMT\",\"host\":\"10.96.99.163:18082\",
\"user-agent\":\"aws-cli/1.9.20 Python/2.7.6 Linux/3.13.0-119-generic botocore/1.3.20\",
\"x-amz-copy-source\":\"/testbkt1/testobj1\",\"x-amz-metadata-directive\":\"REPLACE\",\"x-amz-meta-city\":\"Vancouver\"}"]
[S3AI(CSTR):"20956855414285633225"][SACC(CSTR):"acct1"][S3AK(CSTR):"SGKHyyv9ZQqWRbJSQc5vI7mgioJwrdplShE02AUaww=="]
[SUSR(CSTR):"urn:sgws:identity::20956855414285633225:root"]
[SBAI(CSTR):"20956855414285633225"][SBAC(CSTR):"acct1"][S3BK(CSTR):"testbkt1"]
[S3KY(CSTR):"testobj1"][CBID(UI64):0xCB1D5C213434DD48][CSIZ(UI64):10][AVER(UI32):10]
[ATIM(UI64):1499810043157462][ATYP(FC32):SUPD][ANID(UI32):12258396][AMID(FC32):S3RQ]
[ATID(UI64):8987436599021955788]]
----