---
permalink: audit/object-delete-transactions.html 
sidebar: sidebar 
keywords: object delete transaction, S3 delete, SDEL, WDEL 
summary: Puede identificar transacciones de supresión de objetos en el registro de auditoría ubicando mensajes de auditoría específicos de la API de S3. 
---
= Objeto: Eliminar transacciones
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede identificar transacciones de supresión de objetos en el registro de auditoría ubicando mensajes de auditoría específicos de la API de S3.

En las tablas siguientes no se enumeran todos los mensajes de auditoría generados durante una transacción de eliminación. Sólo se incluyen los mensajes necesarios para realizar el seguimiento de la transacción de eliminación.



== S3 elimina mensajes de auditoría

[cols="1a,1a,2a,1a,2a"]
|===
| Codificación | Nombre | Descripción | Traza | Consulte 


 a| 
SDEL
 a| 
Eliminación de S3
 a| 
Solicitud realizada para eliminar el objeto de un bloque.
 a| 
CBID, S3KY
 a| 
link:sdel-s3-delete.html["SDEL: ELIMINACIÓN DE S3"]

|===


== Ejemplo: Eliminación de objetos de S3

Cuando un cliente S3 elimina un objeto de un nodo de almacenamiento (servicio LDR), se genera un mensaje de auditoría y se guarda en el registro de auditoría.


NOTE: En el ejemplo siguiente no se enumeran todos los mensajes de auditoría generados durante una transacción de eliminación. Solo se muestran los relacionados con la transacción de eliminación de S3 (SDEL).



=== SDEL: Eliminación S3

La eliminación de objetos comienza cuando el cliente envía una solicitud DeleteObject a un servicio LDR. El mensaje contiene el bloque del cual se elimina el objeto y la clave S3 del objeto, que se utiliza para identificar el objeto.

[listing, subs="specialcharacters,quotes"]
----
2017-07-17T21:17:58.959669[AUDT:[RSLT(FC32):SUCS][TIME(UI64):14316][SAIP(IPAD):"10.96.112.29"][S3AI(CSTR):"70899244468554783528"][SACC(CSTR):"test"][S3AK(CSTR):"SGKHyalRU_5cLflqajtaFmxJn946lAWRJfBF33gAOg=="][SUSR(CSTR):"urn:sgws:identity::70899244468554783528:root"][SBAI(CSTR):"70899244468554783528"][SBAC(CSTR):"test"]\[S3BK\(CSTR\):"example"\]\[S3KY\(CSTR\):"testobject-0-7"\][CBID\(UI64\):0x339F21C5A6964D89][CSIZ(UI64):30720][AVER(UI32):10][ATIM(UI64):150032627859669][ATYP\(FC32\):SDEL][ANID(UI32):12086324][AMID(FC32):S3RQ][ATID(UI64):4727861330952970593]]
----