---
permalink: audit/ovwr-object-overwrite.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, OVWR, Object Overwrite 
summary: 'Este mensaje se genera cuando una operación \(cliente-solicitado\) externa hace que un objeto sea sobrescrito por otro objeto.' 
---
= OVWR: Sobrescritura de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Este mensaje se genera cuando una operación externa (solicitada por el cliente) hace que un objeto sea sobrescrito por otro objeto.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
CBID
 a| 
Identificador de bloque de contenido (nuevo)
 a| 
CBID para el nuevo objeto.



 a| 
CSIZ
 a| 
Tamaño de objeto anterior
 a| 
El tamaño, en bytes, del objeto que se sobrescribe.



 a| 
OCBD
 a| 
Identificador de bloque de contenido (anterior)
 a| 
El CBID del objeto anterior.



 a| 
UUID
 a| 
ID único universal (nuevo)
 a| 
El identificador del nuevo objeto dentro del sistema StorageGRID.



 a| 
OUID
 a| 
ID único universal (anterior)
 a| 
El identificador del objeto anterior dentro del sistema StorageGRID.



 a| 
RUTA
 a| 
Ruta de objeto S3
 a| 
La ruta de acceso del objeto S3 utilizada tanto para el objeto anterior como para el nuevo



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Código de resultado
 a| 
Resultado de la transacción de sobrescritura de objetos. El resultado es siempre:

SUCS: Exitoso



 a| 
SGRP
 a| 
Planta (grupo)
 a| 
Si está presente, el objeto sobrescrito se eliminó en el sitio especificado, que no es el sitio donde se ingirió el objeto sobrescrito.

|===