---
permalink: audit/sget-s3-get.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SGET, S3 GET 
summary: Cuando un cliente S3 emite una transacción GET, se realiza una solicitud para recuperar un objeto o enumerar los objetos de un bloque. El servidor emite este mensaje si la transacción se realiza correctamente. 
---
= SGET: S3 GET
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un cliente S3 emite una transacción GET, se realiza una solicitud para recuperar un objeto o enumerar los objetos de un depósito o para eliminar un subrecurso de cubo/objeto. El servidor emite este mensaje si la transacción se realiza correctamente.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
CBID
 a| 
Identificador de bloque de contenido
 a| 
Identificador único del bloque de contenido solicitado. Si el CBID es desconocido, este campo se establece en 0. Las operaciones en los depósitos no incluyen este campo.



 a| 
CNCH
 a| 
Encabezado de control de consistencia
 a| 
El valor del encabezado de solicitud HTTP de control de coherencia, si está presente en la solicitud.



 a| 
CNID
 a| 
Identificador de conexión
 a| 
Identificador único del sistema para la conexión TCP/IP.



 a| 
CSIZ
 a| 
Tamaño de contenido
 a| 
El tamaño del objeto recuperado en bytes. Las operaciones en los depósitos no incluyen este campo.



 a| 
HTRH
 a| 
Encabezado de solicitud HTTP
 a| 
Lista de los nombres de encabezado y valores registrados de la solicitud HTTP como seleccionados durante la configuración.

 `X-Forwarded-For` Se incluye automáticamente si está presente en la solicitud y si el `X-Forwarded-For` valor es diferente de la dirección IP del remitente de la solicitud (campo de auditoría SAIP).



 a| 
MENIDAD
 a| 
ListObjectsV2
 a| 
Se solicitó una respuesta _v2 format_. Para obtener más información, consulte https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html["AWS ListObjectsV2"^]. Sólo para OPERACIONES de OBTENCIÓN DE cucharón.



 a| 
NCHD
 a| 
Número de hijos
 a| 
Incluye claves y prefijos comunes. Sólo para OPERACIONES de OBTENCIÓN DE cucharón.



 a| 
SONÓ
 a| 
Lectura de rango
 a| 
Solo para operaciones de lectura de rango. Indica el rango de bytes que se ha leído en esta solicitud. El valor después de la barra inclinada (/) muestra el tamaño de todo el objeto.



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Código de resultado
 a| 
Resultado DE LA transacción GET. El resultado es siempre:

SUCS: Exitoso



 a| 
S3AI
 a| 
ID de cuenta de inquilino de S3 (remitente de solicitud)
 a| 
El ID de cuenta de inquilino del usuario que envió la solicitud. Un valor vacío indica acceso anónimo.



 a| 
S3AK
 a| 
ID de clave de acceso S3 (remitente de solicitudes)
 a| 
El ID de clave de acceso de S3 hash para el usuario que envió la solicitud. Un valor vacío indica acceso anónimo.



 a| 
S3BK
 a| 
Bloque de S3
 a| 
El nombre de bloque de S3.



 a| 
S3KY
 a| 
Clave de S3
 a| 
El nombre de clave S3, sin incluir el nombre del bloque. Las operaciones en los depósitos no incluyen este campo.



 a| 
S3SR
 a| 
Subrecurso de S3
 a| 
El bloque o subrecurso de objeto en el que se opera, si procede.



 a| 
SACC
 a| 
Nombre de cuenta de inquilino de S3 (remitente de la solicitud)
 a| 
El nombre de la cuenta de arrendatario para el usuario que envió la solicitud. Vacío para solicitudes anónimas.



 a| 
SAIP
 a| 
Dirección IP (remitente de solicitud)
 a| 
La dirección IP de la aplicación cliente que realizó la solicitud.



 a| 
SBAC
 a| 
Nombre de cuenta de inquilino de S3 (propietario del bloque)
 a| 
El nombre de cuenta de inquilino para el propietario del bloque. Se utiliza para identificar el acceso de cuenta cruzada o anónimo.



 a| 
SBAI
 a| 
ID de cuenta de inquilino de S3 (propietario del bloque)
 a| 
El ID de cuenta de inquilino del propietario del bloque de destino. Se utiliza para identificar el acceso de cuenta cruzada o anónimo.



 a| 
SUSR
 a| 
URN de usuario de S3 (remitente de solicitudes)
 a| 
El ID de cuenta de arrendatario y el nombre de usuario del usuario que realiza la solicitud. El usuario puede ser un usuario local o un usuario LDAP. Por ejemplo: `urn:sgws:identity::03393893651506583485:root`

Vacío para solicitudes anónimas.



 a| 
TIEMPO
 a| 
Tiempo
 a| 
Tiempo de procesamiento total de la solicitud en microsegundos.



 a| 
TLIP
 a| 
Dirección IP del equilibrador de carga de confianza
 a| 
Si la solicitud se enrutó por un equilibrador de carga de capa 7 de confianza, la dirección IP del equilibrador de carga.



 a| 
TRNC
 a| 
Truncado o no truncado
 a| 
Si se devuelven todos los resultados, se establece en false. Establezca como verdadero si hay más resultados disponibles para devolver. Sólo para OPERACIONES de OBTENCIÓN DE cucharón.



 a| 
UUID
 a| 
Identificador único universal
 a| 
El identificador del objeto dentro del sistema StorageGRID.



 a| 
VSID
 a| 
ID de versión
 a| 
El código de versión de la versión específica de un objeto que se solicitó. Las operaciones en cubos y objetos en depósitos sin versiones no incluyen este campo.

|===