---
permalink: audit/svru-object-store-verify-unknown.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SVRU, Object Store Verify Unknown 
summary: El componente almacenamiento del servicio LDR analiza continuamente todas las copias de los datos de objetos replicados en el almacén de objetos. Este mensaje se genera cuando se detecta una copia desconocida o inesperada de los datos de objeto replicados en el almacén de objetos y se mueve al directorio de cuarentena. 
---
= SVRU: Verificación del almacén de objetos desconocida
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El componente de almacenamiento del servicio LDR analiza continuamente todas las copias de los datos de objetos replicados en el almacén de objetos. Este mensaje se genera cuando se detecta una copia desconocida o inesperada de los datos de objeto replicados en el almacén de objetos y se mueve al directorio de cuarentena.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
FPTH
 a| 
Ruta del archivo
 a| 
Ruta de acceso del archivo de la copia de objeto inesperada.



 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Resultado
 a| 
Este campo tiene el valor 'NONE'. RSLT es un campo de mensaje obligatorio, pero no es relevante para este mensaje. 'NINGUNO' se utiliza en lugar de 'UCS' para que este mensaje no se filtre.

|===

NOTE: El mensaje de auditoría SVRU: Object Store Verify Unknown debe supervisarse de cerca. Significa que se han detectado copias inesperadas de datos de objetos en el almacén de objetos. Esta situación debe investigarse inmediatamente para determinar cómo se crearon estas copias, ya que pueden indicar fallos de hardware inminentes.
