---
permalink: audit/sysd-node-stop.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYSD, Node Stop 
summary: Cuando un servicio se detiene correctamente, se genera este mensaje para indicar que se ha solicitado el cierre. Normalmente, este mensaje se envía sólo después de un reinicio posterior, porque la cola de mensajes de auditoría no se borra antes del cierre. Busque el mensaje SYST, enviado al principio de la secuencia de apagado, si el servicio no se ha reiniciado. 
---
= SYSD: Parada del nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un servicio se detiene correctamente, se genera este mensaje para indicar que se ha solicitado el cierre. Normalmente, este mensaje se envía sólo después de un reinicio posterior, porque la cola de mensajes de auditoría no se borra antes del cierre. Busque el mensaje SYST, enviado al principio de la secuencia de apagado, si el servicio no se ha reiniciado.

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Apagado limpio
 a| 
La naturaleza del cierre:

SUCS: El sistema se cerró correctamente.

|===
El mensaje no indica si el servidor host se está parando, sólo el servicio de creación de informes. La RSLT de un SYSD no puede indicar un apagado “sucio”, porque el mensaje se genera solo mediante apagados “limpios”.
