---
permalink: audit/syst-node-stopping.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SYST, Node Stopping 
summary: 'Cuando un servicio se detiene de forma controlada, se genera este mensaje para indicar que se ha solicitado el apagado y que el servicio ha iniciado su secuencia de apagado. SYST se puede usar para determinar si se ha solicitado el apagado, antes de que el servicio se reinicie (a diferencia de SYSD, que normalmente se envía después de que el servicio se reinicia).' 
---
= Mensaje de auditoría SYST para nodo que se detiene en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando un servicio se detiene de forma controlada, se genera este mensaje para indicar que se ha solicitado el apagado y que el servicio ha iniciado su secuencia de apagado. SYST se puede usar para determinar si se ha solicitado el apagado, antes de que el servicio se reinicie (a diferencia de SYSD, que normalmente se envía después de que el servicio se reinicia).

[cols="1a,1a,4a"]
|===
| Codificación | Campo | Descripción 


 a| 
TRANSFORMACIÓN DIGITAL
 a| 
Apagado limpio
 a| 
La naturaleza del cierre:

SUCS: El sistema se cerró correctamente.

|===
El mensaje no indica si el servidor host se está parando, sólo el servicio de creación de informes. El código RSLT de un mensaje SYST no puede indicar un cierre “sucio”, porque el mensaje se genera solo mediante apagados “limpios”.
