---
permalink: swnodes/example-node-configuration-files.html 
sidebar: sidebar 
keywords: example debian node configuration file, example ubuntu linux node configuration file, example red hat linux node configuration file, example rhel node configuration file 
summary: Puede usar los archivos de configuración del nodo de ejemplo para ayudar a configurar los archivos de configuración del nodo para el sistema StorageGRID. Los ejemplos muestran archivos de configuración de nodo para todos los tipos de nodos de cuadrícula. 
---
= Archivos de configuración de nodo de ejemplo (Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar los archivos de configuración del nodo de ejemplo para ayudar a configurar los archivos de configuración del nodo para el sistema StorageGRID. Los ejemplos muestran archivos de configuración de nodo para todos los tipos de nodos de cuadrícula.


NOTE: "Linux" se refiere a una implementación de RHEL, Ubuntu o Debian.  Para obtener una lista de las versiones compatibles, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] .

En la mayoría de los nodos, puede agregar información de direccionamiento de red de administrador y cliente (IP, máscara, puerta de enlace, etc.) al configurar la cuadrícula mediante Grid Manager o la API de instalación. La excepción es el nodo de administrador principal. Si desea examinar la dirección IP de red de administrador del nodo de administración principal para completar la configuración de grid (porque la red de grid no se enrutó, por ejemplo), debe configurar la conexión de red de administración para el nodo de administración principal en su archivo de configuración de nodo. Esto se muestra en el ejemplo.


NOTE: En los ejemplos, el destino de red de cliente se ha configurado como práctica recomendada, aunque la red de cliente esté deshabilitada de forma predeterminada.



== Ejemplo de nodo de administración primario

*Ejemplo de nombre de archivo*: `/etc/storagegrid/nodes/dc1-adm1.conf`

*Ejemplo del contenido del archivo:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Primary
TEMPORARY_PASSWORD_TYPE = Use custom password
CUSTOM_TEMPORARY_PASSWORD = Passw0rd
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm1-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm1-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm1-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.2
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1

ADMIN_NETWORK_CONFIG = STATIC
ADMIN_NETWORK_IP = 192.168.100.2
ADMIN_NETWORK_MASK = 255.255.248.0
ADMIN_NETWORK_GATEWAY = 192.168.100.1
ADMIN_NETWORK_ESL = 192.168.100.0/21,172.16.0.0/21,172.17.0.0/21
----


== Ejemplo para Storage Node

*Ejemplo de nombre de archivo:* `/etc/storagegrid/nodes/dc1-sn1.conf`

*Ejemplo del contenido del archivo:*

[listing]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/dc1-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/dc1-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/dc1-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/dc1-sn1-rangedb-3
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Ejemplo para Gateway Node

*Ejemplo de nombre de archivo:* `/etc/storagegrid/nodes/dc1-gw1.conf`

*Ejemplo del contenido del archivo:*

[listing]
----
NODE_TYPE = VM_API_Gateway
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-gw1-var-local
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.5
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----


== Ejemplo de un nodo de administrador que no es primario

*Ejemplo de nombre de archivo:* `/etc/storagegrid/nodes/dc1-adm2.conf`

*Ejemplo del contenido del archivo:*

[listing]
----
NODE_TYPE = VM_Admin_Node
ADMIN_ROLE = Non-Primary
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/dc1-adm2-var-local
BLOCK_DEVICE_AUDIT_LOGS = /dev/mapper/dc1-adm2-audit-logs
BLOCK_DEVICE_TABLES = /dev/mapper/dc1-adm2-tables
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003

GRID_NETWORK_IP = 10.1.0.6
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----