---
permalink: swnodes/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: Utilice el paquete StorageGRID correspondiente a su tipo de sistema operativo para instalar los servicios de host de StorageGRID . 
---
= Instalar servicios de host de StorageGRID (Linux)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice el paquete StorageGRID correspondiente a su tipo de sistema operativo para instalar los servicios de host de StorageGRID .


NOTE: "Linux" se refiere a una implementación de RHEL, Ubuntu o Debian.  Para obtener una lista de las versiones compatibles, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] .

[role="tabbed-block"]
====
.RHEL
--
Se utiliza el paquete de RPM de StorageGRID para instalar los servicios de host de StorageGRID.

.Acerca de esta tarea
Estas instrucciones describen cómo instalar los servicios del host desde los paquetes RPM. Como alternativa, puede usar los metadatos del repositorio de DNF incluidos en el archivo de instalación para instalar los paquetes RPM de forma remota. Consulte las instrucciones del repositorio de DNF para su sistema operativo Linux.

.Pasos
. Copie los paquetes de RPM de StorageGRID en cada uno de sus hosts o haga que estén disponibles en el almacenamiento compartido.
+
Por ejemplo, colóquelos en el `/tmp` directorio, para que pueda utilizar el comando de ejemplo en el siguiente paso.

. Inicie sesión en cada host como raíz o utilice una cuenta con permiso sudo y ejecute los siguientes comandos en el orden especificado:
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Images-version-SHA.rpm
----
+
[listing]
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Service-version-SHA.rpm
----
+

CAUTION: Primero debe instalar el paquete de imágenes y luego el paquete de servicio.

+

NOTE: Si ha colocado los paquetes en un directorio distinto de `/tmp`, modifique el comando para reflejar la ruta de acceso que ha utilizado.



--
.Ubuntu o Debian
--
Utilice el paquete DEB de StorageGRID para instalar los servicios de host de StorageGRID para Ubuntu o Debian.

.Acerca de esta tarea
Estas instrucciones describen cómo instalar los servicios del host desde los paquetes DEB. Como alternativa, puede usar los metadatos del repositorio de APT incluidos en el archivo de instalación para instalar los paquetes DEB de forma remota. Consulte las instrucciones del repositorio de APT para su sistema operativo Linux.

.Pasos
. Copie los paquetes de DEB de StorageGRID en cada uno de sus hosts o haga que estén disponibles en el almacenamiento compartido.
+
Por ejemplo, colóquelos en el `/tmp` directorio, para que pueda utilizar el comando de ejemplo en el siguiente paso.

. Inicie sesión en cada host como raíz o utilice una cuenta con permiso sudo y ejecute los siguientes comandos.
+
Debe instalar el `images` paquete primero y el `service` paquete segundo. Si ha colocado los paquetes en un directorio distinto de `/tmp`, modifique el comando para reflejar la ruta de acceso que ha utilizado.

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: Python 3 ya debe estar instalado antes de que se puedan instalar los paquetes StorageGRID .  El `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` El comando fallará hasta que lo hayas hecho.



--
====