---
permalink: swnodes/overview-of-installation-rest-api.html 
sidebar: sidebar 
keywords: installation REST API 
summary: StorageGRID proporciona la API de instalación de StorageGRID para realizar tareas de instalación. 
---
= Conoce la API de REST de instalación de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID proporciona la API de instalación de StorageGRID para realizar tareas de instalación.

La API utiliza la plataforma API de código abierto de Swagger para proporcionar la documentación de API. Swagger permite que tanto desarrolladores como no desarrolladores interactúen con la API en una interfaz de usuario que ilustra cómo responde la API a los parámetros y las opciones. En esta documentación se asume que está familiarizado con las tecnologías web estándar y el formato de datos JSON.


CAUTION: Cualquier operación de API que realice mediante la página web de Documentación de API es operaciones en directo. Tenga cuidado de no crear, actualizar o eliminar datos de configuración u otros datos por error.

Cada comando de API REST incluye la URL de la API, una acción HTTP, los parámetros de URL necesarios o opcionales y una respuesta de API esperada.



[[storagegrid-installation-api]]
== API de instalación de StorageGRID

La API de instalación de StorageGRID solo está disponible cuando está configurando inicialmente el sistema StorageGRID y si necesita realizar una recuperación de nodo de administración principal. Se puede acceder a la API de instalación a través de HTTPS desde Grid Manager.

Para acceder a la documentación de la API, vaya a la página web de instalación en el nodo de administración principal y seleccione *Ayuda* > *Documentación de la API* en la barra de menús.

La API de instalación de StorageGRID incluye las siguientes secciones:

* *config*: Operaciones relacionadas con el lanzamiento del producto y las versiones de la API. Puedes consultar la versión de lanzamiento del producto y las versiones principales de la API compatibles con dicho lanzamiento.
* *grid*: Operaciones de configuración a nivel de grid. Puedes consultar y actualizar los ajustes de grid, incluidos los detalles de grid, las subredes de Grid Network, las contraseñas de grid y las direcciones IP de los servidores NTP y DNS.
* *nodos*: Operaciones de configuración a nivel de nodo. Puedes obtener una lista de nodos de la red, eliminar un nodo de la red, configurar un nodo de la red, ver un nodo de la red y restablecer la configuración de un nodo de la red.
* *provision*: Operaciones de aprovisionamiento. Puedes iniciar la operación de aprovisionamiento y ver el estado de la operación de aprovisionamiento.
* *recuperación*: Operaciones de recuperación del nodo de administración principal. Puedes restablecer la información, cargar el paquete de recuperación, iniciar la recuperación y consultar el estado de la operación de recuperación.
* *paquete-de-recuperación*: Operaciones para descargar el paquete de recuperación.
* *sitios*: Operaciones de configuración a nivel de sitio. Puedes crear, ver, eliminar y modificar un sitio.
* *contraseña-temporal*: Operaciones sobre la contraseña temporal para proteger la mgmt-api durante la instalación.

