---
permalink: swnodes/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Es posible usar una máquina virtual para alojar cualquier tipo de nodo StorageGRID. Se necesita una máquina virtual para cada nodo de grid. 
---
= Requisitos de software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar una máquina virtual para alojar cualquier tipo de nodo StorageGRID. Se necesita una máquina virtual para cada nodo de grid.

[role="tabbed-block"]
====
.RHEL
--
Para instalar StorageGRID en RHEL, debe instalar algunos paquetes de software de terceros.  Algunas distribuciones de Linux compatibles no contienen estos paquetes de forma predeterminada.  Las versiones de paquetes de software en las que se prueban las instalaciones de StorageGRID incluyen las que se enumeran en esta página.

Si selecciona una opción de instalación en tiempo de ejecución de contenedor y distribución de Linux que requiera alguno de estos paquetes y la distribución de Linux no los instala automáticamente, instale una de las versiones que se enumeran aquí, si está disponible en su proveedor o en el proveedor de soporte para su distribución de Linux. De lo contrario, utilice las versiones de paquete predeterminadas disponibles en su proveedor.

Todas las opciones de instalación requieren Podman o Docker. No instale ambos paquetes. Instale solo el paquete requerido por su opción de instalación.


NOTE: La compatibilidad con Docker como motor de contenedor para puestas en marcha de solo software queda obsoleta. En una futura versión, Docker se sustituirá por otro motor de contenedor.

*Versiones de Python probadas*

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3,8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6


*Versiones de Podman probadas*

* 3,2.3-0
* 3,4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4,3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12


*Versiones de Docker probadas*


IMPORTANT: La compatibilidad de Docker está obsoleta y se eliminará en un lanzamiento futuro.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23,0.6-1
* Docker-CE 24,0.2-1
* Docker-CE 24,0.4-1
* Docker-CE 24,0.5-1
* Docker-CE 24,0.7-1
* 1,5-2


--
.Ubuntu y Debian
--
Para instalar StorageGRID en Ubuntu o Debian, debe instalar algunos paquetes de software de terceros. Algunas distribuciones de Linux soportadas no contienen estos paquetes por defecto. Las versiones del paquete de software en las que se han probado las instalaciones de StorageGRID incluyen las que se indican en esta página.

Si selecciona una opción de instalación en tiempo de ejecución de contenedor y distribución de Linux que requiera alguno de estos paquetes y la distribución de Linux no los instala automáticamente, instale una de las versiones que se enumeran aquí, si está disponible en su proveedor o en el proveedor de soporte para su distribución de Linux. De lo contrario, utilice las versiones de paquete predeterminadas disponibles en su proveedor.

Todas las opciones de instalación requieren Podman o Docker. No instale ambos paquetes. Instale solo el paquete requerido por su opción de instalación.


NOTE: La compatibilidad con Docker como motor de contenedor para puestas en marcha de solo software queda obsoleta. En una futura versión, Docker se sustituirá por otro motor de contenedor.

*Versiones de Python probadas*

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3,8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6


*Versiones de Podman probadas*

* 3,2.3-0
* 3,4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4,3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12


*Versiones de Docker probadas*


IMPORTANT: La compatibilidad de Docker está obsoleta y se eliminará en un lanzamiento futuro.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23,0.6-1
* Docker-CE 24,0.2-1
* Docker-CE 24,0.4-1
* Docker-CE 24,0.5-1
* Docker-CE 24,0.7-1
* 1,5-2


--
.VMware
--
*Hipervisor VMware vSphere*

Debe instalar VMware vSphere Hypervisor en un servidor físico preparado. El hardware debe estar configurado correctamente (incluidas las versiones del firmware y la configuración del BIOS) antes de instalar el software VMware.

* Configure las redes en el hipervisor según sea necesario para admitir la conexión a redes del sistema StorageGRID que está instalando.
+
link:../network/index.html["Directrices sobre redes"]

* Asegúrese de que el almacén de datos sea lo suficientemente grande para las máquinas virtuales y los discos virtuales necesarios para alojar los nodos de grid.
* Si crea más de un almacén de datos, asigne un nombre a cada almacén de datos para poder identificar fácilmente qué almacén de datos se debe usar para cada nodo de grid al crear máquinas virtuales.


*Requisitos de configuración del host ESX*


CAUTION: Debe configurar correctamente el protocolo de hora de red (NTP) en cada host ESX. Si el tiempo del host es incorrecto, podrían producirse efectos negativos, incluso la pérdida de datos.

*Requisitos de configuración de VMware*

Debe instalar y configurar VMware vSphere y vCenter antes de implementar los nodos de StorageGRID.

Para obtener información sobre las versiones compatibles del hipervisor de VMware vSphere y el software VMware vCenter Server, consulte https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] el .

Para conocer los pasos necesarios para instalar estos productos de VMware, consulte la documentación de VMware.

--
====