---
permalink: legal-notices.html 
sidebar: sidebar 
keywords:  
summary:  
---
= Avisos legales
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más.



[[copyright]]
== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



[[trademarks]]
== Marcas comerciales

NETAPP, el logotipo de NETAPP y las marcas enumeradas en la página de marcas comerciales de NetApp son marcas comerciales de NetApp, Inc. Los demás nombres de empresas y productos son marcas comerciales de sus respectivos propietarios.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



[[patents]]
== Estadounidenses

Puede encontrar una lista actual de las patentes propiedad de NetApp en:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



[[privacy-policy]]
== Política de privacidad

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



[[api-license]]
== Licencia API

Esta documentación no otorga ninguna licencia ni otros derechos sobre la API REST de StorageGRID S3. Cualquier uso o acceso a la API REST de StorageGRID S3 requiere y está sujeto a un acuerdo de licencia independiente con NetApp.



[[open-source]]
== Código abierto

Los archivos de notificación proporcionan información sobre los derechos de autor y las licencias de terceros que se utilizan en software de NetApp.

https://library.netapp.com/ecm/ecm_download_file/ECMLP3351268[]
