---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12,0 utiliza la versión 4 de la API de administración de grid. La versión 4 deja de ser la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles. 
---
= Cambios en la API de gestión de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12,0 utiliza la versión 4 de la API de administración de grid. La versión 4 deja de ser la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles.


NOTE: Puede continuar utilizando versiones obsoletas de la API de gestión con StorageGRID 12,0; no obstante, la compatibilidad con estas versiones de la API se quitará en una futura versión de StorageGRID. Después de actualizar a StorageGRID 12,0, puede desactivar las API obsoletas utilizando `PUT /grid/config/management` la API.

Para obtener más información, vaya a link:../admin/using-grid-management-api.html["Utilice la API de gestión de grid"].



== Nuevos puntos finales privados para mover ADC

Se han agregado los siguientes extremos privados para permitirle link:../maintain/move-adc-service.html["Mueva el servicio ADC"]desde un nodo de almacenamiento a otro en el mismo sitio:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`
