---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 12,0 utiliza la versión 4 de la API de gestión de inquilinos. La versión 4 deja de ser la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles. 
---
= Cambios en la API de gestión de inquilinos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12,0 utiliza la versión 4 de la API de gestión de inquilinos. La versión 4 deja de ser la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles.


NOTE: Puede continuar utilizando versiones obsoletas de la API de administración de inquilinos con StorageGRID 12,0; sin embargo, el soporte para estas versiones de la API se eliminará en una futura versión de StorageGRID. Después de actualizar a StorageGRID 12,0, puede desactivar las API obsoletas utilizando `PUT /grid/config/management` la API.

Para obtener más información, vaya a link:../tenant/understanding-tenant-management-api.html["Conozca la API de gestión de inquilinos"].



== Nueva API para la replicación de objetos

Puede usar `/org/cross-grid-replication/{versionId}/replicate` la API para replicar manualmente objetos en un bucket existente que tenga recientemente configurada la replicación entre grid.
