---
permalink: upgrade/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 11,9 utiliza la versión 4 de la API de administración de grid. La versión 4 deja de ser la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles. 
---
= Cambios en la API de gestión de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 11,9 utiliza la versión 4 de la API de administración de grid. La versión 4 deja de ser la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles.


NOTE: Puede continuar utilizando versiones obsoletas de la API de gestión con StorageGRID 11,9; no obstante, la compatibilidad con estas versiones de la API se quitará en una futura versión de StorageGRID. Después de actualizar a StorageGRID 11,9, puede desactivar las API obsoletas utilizando `PUT /grid/config/management` la API.

Para obtener más información, vaya a link:../admin/using-grid-management-api.html["Utilice la API de gestión de grid"].



== Revise la configuración de cumplimiento después de habilitar el bloqueo de objetos S3 global

Revise la configuración de cumplimiento de los arrendatarios existentes después de activar la configuración global S3 Object Lock. Cuando habilita esta opción, la configuración de bloqueo de objetos por inquilino de S3 depende de la versión de StorageGRID en el momento en que se creó el inquilino.



== Solicitudes de api de gestión heredadas eliminadas

Estas solicitudes heredadas se han eliminado:

`/grid/server-types`

`/grid/ntp-roles`



== Cambios en `GET /private/storage-usage` API

* Se ha agregado una nueva propiedad `usageCacheDuration` , al cuerpo de la respuesta. Esta propiedad especifica la duración (en segundos) para la que la caché de consulta de uso sigue siendo válida. Este valor se aplica cuando se comprueba el uso con respecto a los límites de la cuota de almacenamiento del inquilino y la capacidad del bloque.
*  `GET /api/v4/private/storage-usage`El comportamiento se ha corregido para que coincida con el anidamiento del esquema.
* Estos cambios se aplican solo a la API privada.




== Cambios en `GET cross-grid-replication` API

La API */org/containers/:name/cross-grid-replication* GET ya no necesita (`rootAccess`el permiso root access ); sin embargo, debe pertenecer a un grupo de usuarios que tenga el (`viewAllContainers`permiso Manage All buckets (`manageAllContainers`) o View All buckets ).

La API PUT */org/containers/:name/cross-grid-replication* no cambia y aún requiere (`rootAccess`el permiso de acceso root ).
