---
permalink: upgrade/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 12.0 utiliza la versión 4 de la API de administración de inquilinos.  La versión 4 deja obsoleta la versión 3; sin embargo, las versiones 1, 2 y 3 aún son compatibles. 
---
= Cambios en la API de gestión de inquilinos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.0 utiliza la versión 4 de la API de administración de inquilinos.  La versión 4 deja obsoleta la versión 3; sin embargo, las versiones 1, 2 y 3 aún son compatibles.


NOTE: Puede seguir usando versiones obsoletas de la API de administración de inquilinos con StorageGRID 12.0; sin embargo, la compatibilidad con estas versiones de la API se eliminará en una futura versión de StorageGRID.  Después de actualizar a StorageGRID 12.0, puede desactivar las API obsoletas mediante el uso de `PUT /grid/config/management` API.

Para obtener más información, vaya a link:../tenant/understanding-tenant-management-api.html["Conozca la API de gestión de inquilinos"].



== Nueva API para la replicación de objetos

Puedes utilizar el `/org/cross-grid-replication/{versionId}/replicate` API para replicar manualmente objetos en un depósito existente que tiene replicación entre redes recién configurada.
