---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Antes de actualizar un sistema StorageGRID, verifique que el sistema esté listo para acomodar la actualización. Asegúrese de que el sistema funciona con normalidad y de que todos los nodos de grid funcionan. 
---
= Compruebe el estado del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar un sistema StorageGRID, verifique que el sistema esté listo para acomodar la actualización. Asegúrese de que el sistema funciona con normalidad y de que todos los nodos de grid funcionan.

.Pasos
. Inicie sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
. Compruebe y resuelva cualquier alerta activa.
. Confirme que no hay ninguna tarea de cuadrícula en conflicto activa ni pendiente.
+
.. Seleccione *SUPPORT* > *Tools* > *Topología de cuadrícula*.
.. Seleccione *_site_* > *_primary Admin Node_* > *CMN* > *Grid Tasks* > *Configuration*.
+
Las tareas de evaluación de la gestión del ciclo de vida de la información (ILME) son las únicas tareas de la cuadrícula que se pueden ejecutar simultáneamente con la actualización del software.

.. Si hay otras tareas de cuadrícula activas o pendientes, espere a que finalicen o liberen el bloqueo.
+

NOTE: Póngase en contacto con el soporte técnico si una tarea no finaliza o libera el bloqueo.



. link:../network/internal-grid-node-communications.html["Comunicaciones internas de los nodos de grid"]Consulte y link:../network/external-communications.html["Comunicaciones externas"] para asegurarse de que todos los puertos requeridos para StorageGRID 11,9 se abren antes de la actualización.
+

NOTE: No son necesarios puertos adicionales para actualizar a StorageGRID 12,0.


