---
permalink: upgrade/checking-systems-condition-before-upgrading-software.html 
sidebar: sidebar 
keywords: upgrade, grid tasks, firewall, ports 
summary: Antes de actualizar un sistema StorageGRID, verifique que el sistema esté listo para acomodar la actualización. Asegúrese de que el sistema funciona con normalidad y de que todos los nodos de grid funcionan. 
---
= Compruebe el estado del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de actualizar un sistema StorageGRID, verifique que el sistema esté listo para acomodar la actualización. Asegúrese de que el sistema funciona con normalidad y de que todos los nodos de grid funcionan.

.Pasos
. Inicie sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
. Compruebe y resuelva cualquier alerta activa.
. Referirse alink:../network/internal-grid-node-communications.html["Comunicaciones internas de los nodos de grid"] ylink:../network/external-communications.html["Comunicaciones externas"] para garantizar que todos los puertos necesarios para StorageGRID 12.0 estén abiertos antes de realizar la actualización.
+

NOTE: No se requieren puertos adicionales al actualizar a StorageGRID 12.0.


