---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: Conozca cómo se verá afectado su sistema StorageGRID durante la actualización. 
---
= Cómo se ve afectado el sistema durante la actualización
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Conozca cómo se verá afectado su sistema StorageGRID durante la actualización.



== Se permite el acceso SSH externo hasta que se complete la actualización

Se permite el acceso SSH externo durante la actualización.  Cuando se completa la actualización, el acceso SSH externo se bloquea de forma predeterminada.  Después de actualizar, puede usar la pestaña *Bloquear SSH* disponible en la página *Grid Manager* > *Configuración de seguridad* paralink:../admin/manage-external-ssh-access.html["administrar el acceso SSH externo"] .  El acceso SSH entre nodos de la red no se ve afectado.



== Las actualizaciones de StorageGRID no son disruptivas

El sistema StorageGRID puede procesar y recuperar datos de las aplicaciones cliente durante el proceso de actualización. Si aprueba que se actualicen todos los nodos del mismo tipo (por ejemplo, Nodos de almacenamiento), los nodos se desactivan de uno en uno, por lo que no hay momento en que no estén disponibles todos los nodos de grid o todos los nodos de grid de un determinado tipo.

Para garantizar la disponibilidad continua, asegúrese de que su política de ILM contenga reglas que especifiquen el almacenamiento de varias copias de cada objeto. También debe asegurarse de que todos los clientes S3 externos estén configurados para enviar solicitudes a uno de los siguientes:

* Dirección IP virtual de grupo de alta disponibilidad
* Un equilibrador de carga de terceros de alta disponibilidad
* Múltiples nodos de puerta de enlace para cada cliente
* Varios nodos de almacenamiento para cada cliente




== Las aplicaciones cliente pueden experimentar interrupciones a corto plazo

El sistema StorageGRID puede procesar y recuperar datos de las aplicaciones cliente durante el proceso de actualización; sin embargo, las conexiones de cliente a nodos de pasarela individuales o nodos de almacenamiento se pueden interrumpir temporalmente si la actualización necesita reiniciar los servicios de esos nodos. La conectividad se restaurará una vez que se complete el proceso de actualización y se reanuden los servicios en los nodos individuales.

Es posible que deba programar tiempos de inactividad para aplicar una actualización si no se acepta la pérdida de conectividad durante un período breve. Puede utilizar la aprobación selectiva para programar la actualización de determinados nodos.


NOTE: Puede utilizar varias puertas de enlace y grupos de alta disponibilidad para proporcionar conmutación automática al respaldo durante el proceso de actualización. Consulte las instrucciones para link:../admin/configure-high-availability-group.html["configuración de grupos de alta disponibilidad"].



== Las reparaciones en segundo plano no se ejecutarán en redes con nodos de versiones mixtas

Las reparaciones en segundo plano no se ejecutan durante la actualización cuando la red contiene nodos de versiones mixtas.  Cualquier inconsistencia que ocurra durante una interrupción del sitio no se reparará hasta que se complete la actualización.



== El firmware del dispositivo se ha actualizado

Durante la actualización de StorageGRID 12.0:

* Todos los nodos del dispositivo StorageGRID se actualizan automáticamente a la versión 12.0 del firmware del instalador del dispositivo StorageGRID .
* Los dispositivos SG6060 y SGF6024 se actualizan automáticamente a la versión de firmware BIOS 3B08.EX y a la versión de firmware BMC 4.01.07.
* Los dispositivos SG100 y SG1000 se actualizan automáticamente a la versión de firmware BIOS 3B13.EC y a la versión de firmware BMC 4.75.07.
* Los dispositivos SGF6112, SG6160, SG110 y SG1100 se actualizan automáticamente a la versión de firmware BIOS 3A14.QD y a la versión de firmware BMC 3.19.07.




== Las políticas de ILM se tratan de forma diferente según su estado

* La política activa seguirá siendo la misma después de la actualización.
* En la actualización, sólo se conservan las últimas 10 políticas históricas.
* Si hay una política propuesta, se eliminará durante la actualización.




== Es posible que se activen alertas

Es posible que se activen alertas cuando se inician y se detienen los servicios y cuando el sistema StorageGRID funciona como un entorno de versiones mixtas (algunos nodos de grid que ejecutan una versión anterior, mientras que otros se han actualizado a una versión posterior). Es posible que se activen otras alertas una vez que se complete la actualización.

Por ejemplo, es posible que vea la alerta *No se puede comunicar con el nodo* cuando se detienen los servicios, o es posible que vea la alerta *Error de comunicación de Cassandra* cuando algunos nodos se han actualizado a StorageGRID 12.0 pero otros nodos aún ejecutan StorageGRID 11.9.  En general, estas alertas desaparecerán cuando se complete la actualización.

La alerta *Ubicación ILM inalcanzable* podría activarse cuando los nodos de almacenamiento se detienen durante la actualización a StorageGRID 12.0.  Esta alerta podría persistir durante 1 día después de que se complete la actualización.

Una vez completada la actualización, puede revisar cualquier alerta relacionada con la actualización seleccionando *Alertas resueltas recientemente* o *Alertas actuales* desde el panel de control de Grid Manager.



== Los cambios de configuración están restringidos


NOTE: Esta lista se aplica específicamente a las actualizaciones de StorageGRID 11.9 a StorageGRID 12.0.  Si está actualizando a otra versión de StorageGRID , consulte la lista de cambios restringidos en las instrucciones de actualización para esa versión.

Hasta que finalice la tarea *Activar nueva función*:

* No realice ningún cambio en la configuración de la cuadrícula.
* No active ni desactive ninguna función nueva.
* No actualice la configuración de ILM. De lo contrario, es posible que experimente un comportamiento de ILM inconsistente e inesperado.
* No aplique una revisión ni recupere un nodo de grid.
+

NOTE: Si necesita recuperar un nodo durante la actualización, póngase en contacto con el soporte técnico.

* No debe administrar grupos de alta disponibilidad, interfaces VLAN ni puntos finales del equilibrador de carga mientras actualiza a StorageGRID 12.0.
* No elimine ningún grupo de alta disponibilidad hasta que se complete la actualización a StorageGRID 12.0.  Las direcciones IP virtuales en otros grupos de HA podrían volverse inaccesibles.


Hasta que finalice la tarea *pasos de actualización final*:

* No realice un procedimiento de expansión.
* No realice un procedimiento de decomiso.

