---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Utilice estas instrucciones para actualizar un sistema StorageGRID a una nueva versión. 
---
= Actualice el software StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice estas instrucciones para actualizar un sistema StorageGRID a una nueva versión.

Cuando realiza la actualización, se actualizan todos los nodos del sistema StorageGRID.



== Antes de empezar

Revise estos temas para saber más sobre las nuevas funciones y mejoras que se han aplicado en StorageGRID 11,9, determine si alguna función se ha obsoleto o se ha eliminado y obtenga información sobre los cambios en las API de StorageGRID.

* link:whats-new.html["Novedades de StorageGRID 11,9"]
* link:removed-or-deprecated-features.html["Operaciones eliminadas o obsoletas"]
* link:changes-to-grid-management-api.html["Cambios en la API de gestión de grid"]
* link:changes-to-tenant-management-api.html["Cambios en la API de gestión de inquilinos"]

