---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: storagegrid software upgrade 
summary: Utilice estas instrucciones para actualizar un sistema StorageGRID a una nueva versión. 
---
= Actualice el software StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice estas instrucciones para actualizar un sistema StorageGRID a una nueva versión.

Cuando realiza la actualización, se actualizan todos los nodos del sistema StorageGRID.


CAUTION: No inicie la actualización si necesita urgentemente ampliar su almacenamiento para aumentar la capacidad (si su almacenamiento está casi lleno).  Complete el procedimiento de actualización de manera oportuna.  Si es necesaria una recuperación, comuníquese con el soporte técnico.



== Antes de actualizar

Revise estos temas para conocer las nuevas características y mejoras en StorageGRID 12.0, determinar si alguna característica ha quedado obsoleta o se ha eliminado y obtener información sobre los cambios en las API de StorageGRID .

* link:how-your-system-is-affected-during-upgrade.html["Cómo se ve afectado el sistema durante la actualización"]
* link:whats-new.html["Novedades de StorageGRID 12.0"]
* link:removed-or-deprecated-features.html["Operaciones eliminadas o obsoletas"]
* link:changes-to-grid-management-api.html["Cambios en la API de gestión de grid"]
* link:changes-to-tenant-management-api.html["Cambios en la API de gestión de inquilinos"]

