---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: Antes de iniciar la actualización, verifique que la versión anterior de StorageGRID esté actualmente instalada con la última revisión disponible aplicada. 
---
= Comprobar la versión instalada de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de iniciar la actualización, verifique que la versión anterior de StorageGRID esté actualmente instalada con la última revisión disponible aplicada.

.Acerca de esta tarea
Antes de actualizar a StorageGRID 12.0, su red debe tener instalado StorageGRID 11.9.0.8 o posterior.  Si actualmente está usando una versión anterior de StorageGRID, debe instalar todos los archivos de actualización anteriores junto con sus últimas revisiones (muy recomendado) hasta que la versión actual de su red sea al menos StorageGRID 11.9.0.8.

Una posible ruta de actualización se muestra en la <<example-upgrade-path,ejemplo>>.


CAUTION: NetApp recomienda encarecidamente que aplique la última revisión para cada versión de StorageGRID antes de actualizar a la siguiente versión y que también aplique la última revisión para cada nueva versión que instale.  En algunos casos, es necesario aplicar una revisión para evitar el riesgo de pérdida de datos.  Referirse a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp: StorageGRID"^] y las notas de la versión de cada revisión para obtener más información.



== Verificar la versión instalada

.Pasos
. Inicie sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
. En la parte superior de Grid Manager, seleccione *Ayuda* > *Acerca de*.
. Verifique que la *Versión* sea 11.9.0.8 o posterior.
. Si la *Versión* no es 11.9.0.8 o posterior, vaya a https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Descargas de NetApp: StorageGRID"^] para descargar los archivos de actualización y revisión que necesita.
. link:../upgrade/index.html["Siga las instrucciones de actualización"]para cada versión que hayas descargado. link:../maintain/storagegrid-hotfix-procedure.html["Aplicar la última revisión"] para cada lanzamiento (muy recomendado).


Consulte el siguiente ejemplo de actualización.



== [[example-upgrade-path]]Ejemplo: Actualizar a StorageGRID 12.0 desde la versión 11.8

El siguiente ejemplo muestra los pasos para actualizar de la versión 11.8 de StorageGRID a la versión 11.9 como preparación para una actualización de StorageGRID 12.0.

Descargue e instale software en la siguiente secuencia para preparar el sistema para la actualización:

. Actualice a la versión principal de StorageGRID 11.8.0.
. Aplique la última revisión de StorageGRID 11,8.0._y_.
. Actualice a la versión principal de StorageGRID 11.9.0.
. Aplique la revisión StorageGRID 11.9.0.8 o posterior.

