---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Esta versión de StorageGRID introduce las siguientes funciones y cambios funcionales. 
---
= Novedades de StorageGRID 12.0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta versión de StorageGRID introduce las siguientes funciones y cambios funcionales.



== Dispositivos

* La capacidad de almacenamiento y la rentabilidad han aumentado significativamente.
* Las actualizaciones automáticas del firmware de la unidad mejoran la confiabilidad del sistema y reducen los gastos generales de mantenimiento.




== Inteligencia artificial (IA) y aprendizaje automático (ML)

* link:../tenant/what-is-branch-bucket.html["Cubos de ramas"]permitir versiones puntuales de los buckets que facilitan una recuperación más rápida del ransomware y conjuntos de datos aislados para pruebas y experimentación.
* Una capa de almacenamiento en caché S3 mejora el rendimiento para el entrenamiento de IA/ML.




== Capacidad

StorageGRID ahora admite un billón de objetos, lo que supone más del doble del límite anterior.  Consulte la https://fusion.netapp.com/["Herramienta NetApp Fusion"^] para dimensionar y diseñar StorageGRID.



== Actualizaciones de Cassandra

StorageGRID ahora utiliza una versión más nueva de Cassandra para el almacenamiento de metadatos.  Esta versión de Cassandra utiliza el espacio en disco de manera más eficiente para almacenar más metadatos.

Después de ustedlink:../upgrade/index.html["Actualización de StorageGRID 11.9 a 12.0"] Se producirá una actualización del formato de metadatos en segundo plano durante uno a tres días.  Durante este tiempo, ciertos procedimientos de mantenimiento que involucran la transmisión de metadatos, como la expansión, estarán deshabilitados.

Consulte link:../upgrade/performing-upgrade.html#upgrade-other-nodes["Actualice otros nodos"] .



== Federación

* Ahora puedeslink:../admin/managing-users.html#import-federated-users["importar hasta 100 usuarios federados"] en StorageGRID.
* Ahora puedeslink:../ilm/configuring-regions-optional-and-s3-only.html["modificar la región predeterminada"] para depósitos S3.  Esta capacidad proporciona una mayor flexibilidad en la gestión de la configuración regional y el cumplimiento de los datos.
* Ahora puede configurar la replicación entre redes entre buckets con el bloqueo de objetos S3 habilitado. Consulte link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Replicación entre cuadrículas con S3 Object Lock"] .
+
NetApp recomienda utilizar esta función solo entre los depósitos de origen y destino de StorageGRID 12.0.  Sin embargo, esta función es compatible entre los depósitos de origen de StorageGRID 11.9 con el bloqueo de objetos S3 deshabilitado y los depósitos de destino de StorageGRID 12.0 con el bloqueo de objetos S3 habilitado.





== Manejabilidad

* Mejoradolink:../maintain/decommission-procedure.html["procedimiento de desmantelamiento"] Reduce el tiempo y la complejidad para mejorar la eficiencia operativa.
* El comportamiento mejorado para una fuerte consistencia global brinda tolerancia a fallas del sitio para las solicitudes de los clientes cuando las redes tienen tres o más sitios.
+
** Las nuevas instalaciones de StorageGRID 12.0 y posteriores utilizarán de manera predeterminada la semántica de Quorum cuandolink:../s3/consistency.html["fuerte consistencia global"] está establecido
** Si actualiza de StorageGRID 11.9 a StorageGRID 12.0, las cuadrículas actualizadas mantendrán el comportamiento anterior para lograr una fuerte consistencia global.





NOTE: Si necesita volver al comportamiento anterior para lograr una consistencia global fuerte, consulte https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency["Configuración de la semántica de quórum de StorageGRID para una consistencia global sólida"^] para obtener instrucciones.

* La capacidad de iniciar cargas de registros alink:../admin/configure-autosupport-grid-manager.html["AutoSupport"] Ayuda a mejorar la capacidad de respuesta del soporte.
* Reducido https://docs.netapp.com/us-en/storagegrid-appliances/index.html["aparato"^] El tiempo de reinicio minimiza el tiempo de inactividad para mejorar la disponibilidad general del sistema.
* link:../maintain/move-adc-service.html["La capacidad de mover el servicio ADC"]a otro nodo de almacenamiento aumenta la flexibilidad y la resiliencia en la gestión de los nodos de almacenamiento que alojan el servicio ADC.  Puede mover el servicio ADC antes de desmantelar un nodo de almacenamiento o convertir un nodo de almacenamiento en un nodo de solo datos.
* Para maximizar la capacidad de almacenamiento de datos, puedelink:../maintain/convert-to-data-only-node.html["convertir un nodo de almacenamiento en un nodo de solo datos"] , lo que hace que los metadatos de ese nodo se migren a nodos de almacenamiento combinados o de solo metadatos.
* La capacidad de cualquier nodo de administración paralink:../maintain/selecting-node-recovery-procedure.html["recuperar cualquier otro nodo"] (excepto el nodo de administración principal) mejora la recuperación del sistema y la tolerancia a fallas, mejorando la confiabilidad general.
* Los usuarios ahora pueden usar un bucket S3 paralink:../monitor/configure-log-management.html#use-a-bucket["almacenar registros de auditoría durante un largo período de tiempo"] .




== Seguridad

* Un cifrado de datos más fuerte y una protección de la integridad proporcionan mejor seguridad y rendimiento.
* La mayor seguridad de las contraseñas almacenadas reduce el riesgo de acceso no autorizado.
* link:../admin/manage-external-ssh-access.html["SSH está bloqueado por defecto"]para mejorar la seguridad permitiendo el acceso controlado.




== Grupos de inquilinos

* Ahora puedeslink:../tenant/manage-groups.html["configurar una nueva política de confianza de S3"] para soportar la API AssumeRole.  La función AssumeRole proporciona credenciales a corto plazo para una mayor seguridad y un control de acceso flexible.
* La cuota de recuento de objetos por bucket permite un mejor control y gestión de los recursos de almacenamiento.




== Interfaz de usuario

* Las configuraciones del tema oscuro y del tema del sistema están disponibles en el menú Usuario del Administrador de red y del Administrador de inquilinos.
* La página del servidor de auditoría y syslog, renombradalink:../monitor/configure-log-management.html["Gestión de registros"] , se ha refactorizado con adiciones para almacenar registros en un depósito del sistema para fines de respaldo.
* Se eliminó la página de Topología de cuadrícula heredada.  En las últimas versiones de StorageGRID , las operaciones y métricas disponibles en esa página se migraron a otras páginas en el Administrador de Grid, en particular a lalink:../monitor/viewing-nodes-page.html["Nodos"] .

