---
permalink: upgrade/whats-new.html 
sidebar: sidebar 
keywords: what is new in StorageGRID 12.0 
summary: Esta versión de StorageGRID introduce las siguientes funciones y cambios funcionales. 
---
= Novedades en StorageGRID 12,0
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Esta versión de StorageGRID introduce las siguientes funciones y cambios funcionales.



== Replicación entre grid con S3 Object Lock

Puede configurar la replicación entre grid entre buckets con S3 Object Lock habilitado. Consulte link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol["Replicación entre grid con S3 Object Lock"].

NetApp recomienda utilizar esta función solo entre los bloques de origen y de destino de StorageGRID 12,0. Sin embargo, esta función se admite entre los buckets de origen de StorageGRID 11,9 con bloqueo de objeto S3 desactivado y los cubos de destino de StorageGRID 12,0 con bloqueo de objeto S3 habilitado.



== Seguridad



=== Mejora de la seguridad para las contraseñas cifradas en el disco

Seguridad de contraseñas mejorada, incluido un recuento de redondas hash altamente aumentado para hashes de contraseñas SHA512.



== S3 cubos



=== Cucharones para bifurcaciones

Ahora puede link:../tenant/manage-branch-bucket-html["crear cubos de bifurcación"]obtener un cubo de S3. Un depósito de bifurcación proporciona acceso a objetos de depósito S3 tal como existían en un momento determinado. Un bloque de sucursales no es lo mismo que un backup.



== Interfaz de usuario



=== Tema oscuro

La configuración del tema oscuro y del tema del sistema está disponible en el menú Usuario de Grid Manager y el Gestor de inquilinos.



== Mejoras de Grid Manager



=== Configurar la mejora de regiones

La página Regiones en Grid Manager ahora incluye una pestaña *región predeterminada*. Puede utilizar esta pestaña para cambiar la región por defecto definida para S3 cubos. link:../ilm/configuring-regions-optional-and-s3-only.html["Leer más"].
