---
permalink: ubuntu/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download ubuntu or debian installation files 
summary: Debe descargar el archivo de instalación de StorageGRID y extraer los archivos necesarios. Opcionalmente, puede verificar manualmente los archivos en el paquete de instalación. 
---
= Descargue y extraiga los archivos de instalación de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe descargar el archivo de instalación de StorageGRID y extraer los archivos necesarios. Opcionalmente, puede verificar manualmente los archivos en el paquete de instalación.

.Pasos
. Vaya a la https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["Página de descargas de NetApp para StorageGRID"^].
. Seleccione el botón para descargar la última versión, o seleccione otra versión en el menú desplegable y seleccione *Ir*.
. Inicie sesión con el nombre de usuario y la contraseña de su cuenta de NetApp.
. Si aparece una declaración Precaution/MustRead, léala y seleccione la casilla de verificación.
+

CAUTION: Debe aplicar cualquier revisión requerida después de instalar la versión de StorageGRID. Para obtener más información, consulte link:../maintain/storagegrid-hotfix-procedure.html["procedimiento de revisión en las instrucciones de recuperación y mantenimiento"]

. Lea el Contrato de licencia de usuario final, seleccione la casilla de verificación y, a continuación, seleccione * Aceptar y continuar *.
. En la columna *Instalar StorageGRID*, seleccione el archivo de instalación .tgz o .zip para Ubuntu o Debian.
+

NOTE: Seleccione el `.zip` archivo si está ejecutando Windows en el portátil de servicio.

. Guarde el archivo de instalación.
. [[ubuntu-download-verification-package]]Si necesita verificar el archivo de instalación:
+
.. Descargue el paquete de verificación de firma de código StorageGRID. El nombre de archivo de este paquete utiliza el formato `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`, donde `<version-number>` es la versión de software StorageGRID.
.. Siga los pasos a link:../ubuntu/download-files-verify.html["verifique manualmente los archivos de instalación"].


. Extraiga los archivos del archivo de instalación.
. Elija los archivos que necesita.
+
Los archivos que necesita dependen de la topología de grid planificada y de cómo implementará su sistema StorageGRID.

+

NOTE: Las rutas enumeradas en la tabla son relativas al directorio de nivel superior instalado por el archivo de instalación extraído.



[cols="1a,1a"]
|===
| Ruta y nombre de archivo | Descripción 


| ./debs/README  a| 
Archivo de texto que describe todos los archivos contenidos en el archivo de descarga de StorageGRID.



| ./debs/NLF000000.txt  a| 
Un archivo de licencia de NetApp que no es de producción y que se puede usar para pruebas e implementaciones conceptuales.



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
PAQUETE DEB para instalar las imágenes del nodo StorageGRID en hosts de Ubuntu o Debian.



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
MD5 suma de comprobación para el archivo `/debs/storagegrid-webscale-images-version-SHA.deb`.



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
PAQUETE DEB para instalar el servicio de host de StorageGRID en hosts de Ubuntu o Debian.



| Herramienta de secuencia de comandos de la implementación | Descripción 


| ./debs/configure-storagegrid.py  a| 
Script Python que se utiliza para automatizar la configuración de un sistema StorageGRID.



| ./debs/configure-sga.py  a| 
Una secuencia de comandos Python que se utiliza para automatizar la configuración de los dispositivos StorageGRID.



| ./debs/storagegrid-ssoauth.py  a| 
Ejemplo de secuencia de comandos Python que puede utilizar para iniciar sesión en la API de gestión de grid cuando está activado el inicio de sesión único. También puede utilizar este script para la integración federada de ping.



| ./debs/configure-storagegrid.sample.json  a| 
Un archivo de configuración de ejemplo para utilizar con `configure-storagegrid.py` el script.



| ./debs/configure-storagegrid.blank.json  a| 
Un archivo de configuración en blanco para su uso con `configure-storagegrid.py` el script.



| ./débitos/extras/ansible  a| 
Ejemplo de rol de Ansible y libro de aplicaciones para configurar hosts Ubuntu o Debian para la implementación del contenedor StorageGRID. Puede personalizar el rol o el libro de estrategia según sea necesario.



| ./debs/storagegrid-ssoauth-azure.py  a| 
Un ejemplo de script de Python que puede utilizar para iniciar sesión en la API de administración de grid cuando se activa el inicio de sesión único (SSO) mediante Active Directory o ping federate.



| ./debs/storagegrid-ssoauth-azure.js  a| 
Un script de ayuda llamado por el script de Python compañero `storagegrid-ssoauth-azure.py` para realizar interacciones SSO con Azure.



| ./debs/extras/esquemas api  a| 
Esquemas de API para StorageGRID.

*Nota*: Antes de realizar una actualización, puede usar estos esquemas para confirmar que cualquier código que haya escrito para usar las API de administración de StorageGRID será compatible con la nueva versión de StorageGRID si no tiene un entorno StorageGRID que no sea de producción para probar la compatibilidad de la actualización.

|===