---
permalink: ubuntu/installing-storagegrid-webscale-host-services.html 
sidebar: sidebar 
keywords: how to install StorageGRID host services 
summary: Se utiliza el paquete de DEB de StorageGRID para instalar los servicios de host de StorageGRID. 
---
= Instale los servicios de host StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se utiliza el paquete de DEB de StorageGRID para instalar los servicios de host de StorageGRID.

.Acerca de esta tarea
Estas instrucciones describen cómo instalar los servicios del host desde los paquetes DEB. Como alternativa, puede usar los metadatos del repositorio de APT incluidos en el archivo de instalación para instalar los paquetes DEB de forma remota. Consulte las instrucciones del repositorio de APT para su sistema operativo Linux.

.Pasos
. Copie los paquetes de DEB de StorageGRID en cada uno de sus hosts o haga que estén disponibles en el almacenamiento compartido.
+
Por ejemplo, colóquelos en el `/tmp` directorio, para que pueda utilizar el comando de ejemplo en el siguiente paso.

. Inicie sesión en cada host como raíz o utilice una cuenta con permiso sudo y ejecute los siguientes comandos.
+
Debe instalar el `images` paquete primero y el `service` paquete segundo. Si ha colocado los paquetes en un directorio distinto de `/tmp`, modifique el comando para reflejar la ruta de acceso que ha utilizado.

+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
[listing]
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+

NOTE: Python 2.7 ya debe estar instalado antes de poder instalar los paquetes StorageGRID. El `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` comando fallará hasta que lo haya hecho.


