---
permalink: ubuntu/installing-linux.html 
sidebar: sidebar 
keywords: how to install Linux 
summary: Debe instalar StorageGRID en todos los hosts de grid de Ubuntu o Debian. Para ver una lista de las versiones admitidas, use la herramienta de matriz de interoperabilidad de NetApp. 
---
= Instale Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar StorageGRID en todos los hosts de grid de Ubuntu o Debian. Para ver una lista de las versiones admitidas, use la herramienta de matriz de interoperabilidad de NetApp.

.Antes de empezar
Asegúrese de que su sistema operativo cumple con los requisitos mínimos de versión de núcleo de StorageGRID, como se indica a continuación. Utilice el comando `uname -r` para obtener la versión de kernel de su sistema operativo o póngase en contacto con su proveedor del sistema operativo.

*Nota:* La compatibilidad con las versiones 18,04 y 20,04 de Ubuntu ha quedado obsoleta y se eliminará en una versión futura.

[cols="1a,2a,3a"]
|===
| Versión de Ubuntu | Versión mínima del núcleo | Nombre del paquete del núcleo 


 a| 
18.04.6 (obsoleto)
 a| 
5,4.0-150-generic
 a| 
linux-image-5,4.0-150-generic/bionic-updates,bionic-security,ahora 5,4.0-150,167~18.04.1



 a| 
20.04.5 (obsoleto)
 a| 
5,4.0-131-generic
 a| 
linux-image-5,4.0-131-generic/focal-updates,ahora 5,4.0-131,147



 a| 
22.04.1
 a| 
5.15.0-47-genérico
 a| 
linux-image-5.15.0-47-generic/jammy-updates, jammy-security, ahora 5.15.0-47,51



 a| 
24,04
 a| 
6,8.0-31-generic
 a| 
linux-image-6,8.0-31-generic/noble, ahora 6,8.0-31,31

|===
*Nota:* La compatibilidad con Debian versión 11 ha sido obsoleta y se eliminará en una versión futura.

[cols="1a,2a,2a"]
|===
| Versión de Debian | Versión mínima del núcleo | Nombre del paquete del núcleo 


 a| 
11 (obsoleto)
 a| 
5.10.0-18-amd64
 a| 
linux-image-5.10.0-18-amd64/stable, ahora 5.10.150-1



 a| 
12
 a| 
6,1.0-9-amd64
 a| 
linux-image-6,1.0-9-amd64/stable, ahora 6,1.27-1

|===
.Pasos
. Instalar Linux en todos los hosts de grid físicos o virtuales de acuerdo con las instrucciones del mayorista o del procedimiento estándar.
+

NOTE: No instale ningún entorno de escritorio gráfico. Al instalar Ubuntu, debe seleccionar *utilidades estándar del sistema*. Se recomienda seleccionar *OpenSSH Server* para habilitar el acceso ssh a sus hosts Ubuntu. Todas las demás opciones pueden permanecer desactivadas.

. Asegúrese de que todos los hosts tengan acceso a los repositorios de paquetes de Ubuntu o Debian.
. Si el intercambio está activado:
+
.. Ejecute el siguiente comando: `$ sudo swapoff --all`
.. Elimine todas las entradas de intercambio de `/etc/fstab` para mantener la configuración.
+

NOTE: Si no se deshabilita por completo el intercambio, el rendimiento se puede reducir considerablemente.




