---
permalink: network/general-networking-requirements.html 
sidebar: sidebar 
keywords: networking requirements, storagegrid networks 
summary: Todas las puestas en marcha de StorageGRID deben admitir las siguientes conexiones. 
---
= Requisitos generales de red
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Todas las puestas en marcha de StorageGRID deben admitir las siguientes conexiones.

Estas conexiones se pueden realizar a través de las redes Grid, Admin o Client o las combinaciones de estas redes, como se ilustra en los ejemplos de topología de red.

* *Conexiones de administración*: Conexiones de entrada de un administrador al nodo, normalmente a través de SSH. Acceso del navegador web a Grid Manager, al responsable de inquilinos y al instalador de dispositivos de StorageGRID.
* *Conexiones de servidor NTP*: Conexión UDP saliente que recibe una respuesta UDP entrante.
+
El nodo de administración primario debe tener acceso al menos un servidor NTP.

* *Conexiones de servidor DNS*: Conexión UDP saliente que recibe una respuesta UDP entrante.
* *Conexiones del servidor LDAP/Active Directory*: Conexión TCP saliente desde el servicio Identity en nodos de almacenamiento.
* *AutoSupport*: Conexión TCP saliente desde los nodos de administración a `support.netapp.com` un proxy configurado por el cliente.
* *Servidor de administración de claves externo*: Conexión TCP de salida desde cada nodo de dispositivo con cifrado de nodos activado.
* Conexiones TCP entrantes desde clientes S3.
* Solicitudes salientes de servicios de plataforma de StorageGRID como la replicación de CloudMirror o de los pools de almacenamiento en cloud.


Si StorageGRID no puede contactar con ninguno de los servidores NTP o DNS aprovisionados mediante las reglas de enrutamiento predeterminadas, intentará el contacto automáticamente en todas las redes (Grid, Admin y Client) siempre y cuando se especifiquen las direcciones IP de los servidores DNS y NTP. Si se puede acceder a los servidores NTP o DNS en cualquier red, StorageGRID creará automáticamente reglas de enrutamiento adicionales para garantizar que la red se utilice para todos los futuros intentos de conexión con ella.


TIP: Aunque puede utilizar estas rutas de host detectadas automáticamente, en general debe configurar manualmente las rutas DNS y NTP para garantizar la conectividad en caso de que se produzca un error en la detección automática.

Si no está listo para configurar las redes de administración y cliente opcionales durante la implementación, puede configurar estas redes cuando apruebe los nodos de cuadrícula durante los pasos de configuración. Además, puede configurar estas redes una vez finalizada la instalación mediante la herramienta Change IP (Cambiar IPlink:../maintain/configuring-ip-addresses.html["Configurar las direcciones IP"]) (consulte ).



== Conexiones para nodos de administrador y nodos de puerta de enlace

Los nodos de administración siempre deben estar protegidos de clientes que no son de confianza, como los que están en la Internet abierta. Debe asegurarse de que ningún cliente que no sea de confianza puede acceder a un nodo de administración en la red de grid, la red de administración o la red de cliente.

Los nodos de administración y los nodos de puerta de enlace que planea añadir a grupos de alta disponibilidad se deben configurar con una dirección IP estática. Consulte link:../admin/managing-high-availability-groups.html["Gestión de grupos de alta disponibilidad"].



== Uso de la traducción de direcciones de red (NAT)

No utilice la traducción de direcciones de red (NAT) en la red de grid entre nodos de grid o entre sitios de StorageGRID. Cuando utilice direcciones IPv4 privadas para la red de cuadrícula, esas direcciones deben poder enrudarse directamente desde cada nodo de cuadrícula de cada sitio. Sin embargo, según sea necesario, puede utilizar NAT entre clientes externos y nodos de cuadrícula, como para proporcionar una dirección IP pública para un nodo de puerta de enlace. El uso de NAT para tender un segmento de red pública sólo se admite cuando se emplea una aplicación de túnel que es transparente para todos los nodos de la cuadrícula, lo que significa que los nodos de la cuadrícula no necesitan conocimientos de direcciones IP públicas.
