= Ubicación de los archivos de configuración del nodo
:allow-uri-read: 




== Ubicación de los archivos de configuración del nodo

Coloque el archivo de configuración para cada nodo StorageGRID en el `/etc/storagegrid/nodes` directorio del host donde se ejecutará el nodo. Por ejemplo, si planea ejecutar un nodo de administración, un nodo de puerta de enlace y un nodo de almacenamiento en el host A, debe colocar los archivos de configuración de tres nodos en `/etc/storagegrid/nodes` el host A.

Puede crear los archivos de configuración directamente en cada host mediante un editor de texto, como vim o nano, o bien puede crearlos en otro lugar y moverlos a cada host.



== Nomenclatura de los archivos de configuración de nodos

Los nombres de los archivos de configuración son significativos. El formato es `node-name.conf`, donde `node-name` es un nombre que se asigna al nodo. Este nombre aparece en el instalador de StorageGRID y se utiliza para operaciones de mantenimiento de nodos, como la migración de nodos.

Los nombres de los nodos deben seguir estas reglas:

* Debe ser único
* Debe comenzar por una letra
* Puede contener los caracteres De La A a la Z y de la a a la Z.
* Puede contener los números del 0 al 9
* Puede contener uno o varios guiones (-)
* No debe tener más de 32 caracteres, sin incluir `.conf` la extensión


Los archivos que `/etc/storagegrid/nodes` no sigan estas convenciones de nomenclatura no serán analizados por el servicio de host.

Si tiene una topología de varios sitios planificada para la cuadrícula, un esquema típico de nomenclatura de nodos podría ser:

`site-nodetype-nodenumber.conf`

Por ejemplo, puede utilizar `dc1-adm1.conf` para el primer nodo de administración en el centro de datos 1 y `dc2-sn3.conf` para el tercer nodo de almacenamiento en el centro de datos 2. Sin embargo, puede utilizar cualquier esquema que desee, siempre que todos los nombres de nodo sigan las reglas de nomenclatura.



== Contenido de un archivo de configuración de nodo

Un archivo de configuración contiene pares clave/valor, con una clave y un valor por línea. Para cada par clave/valor, siga estas reglas:

* La clave y el valor deben estar separados por un signo igual (`=`) y un espacio en blanco opcional.
* Las teclas no pueden contener espacios.
* Los valores pueden contener espacios incrustados.
* Se ignora cualquier espacio en blanco inicial o final.


La siguiente tabla define los valores de todas las claves admitidas. Cada clave tiene una de las siguientes designaciones:

* *Requerido*: Requerido para cada nodo o para los tipos de nodo especificados
* *Mejor práctica*: Opcional, aunque recomendado
* *Opcional*: Opcional para todos los nodos




=== Claves de red de administración



==== IP_ADMINISTRADOR

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Dirección IPv4 de la red Grid del nodo de administración que desea utilizar para instalar el nodo basado en Linux.  Para la recuperación, utilice la IP del nodo de administración principal si está disponible; de lo contrario, utilice la IP de un nodo de administración que no sea principal.  Si omite este parámetro, el nodo intentará descubrir un nodo de administración principal mediante mDNS.

link:how-grid-nodes-discover-primary-admin-node.html["La forma en que los nodos de grid detectan el nodo de administrador principal"]

*Nota*: Este valor se ignora, y podría estar prohibido, en el nodo de administración principal.
 a| 
Mejor práctica

|===


==== ADMIN_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
DHCP, ESTÁTICO O DESHABILITADO
 a| 
Opcional

|===


==== ADMIN_NETWORK_ESL

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Lista separada por comas de subredes en notación CIDR a la que este nodo debe comunicarse mediante la puerta de enlace de la red de administración.

Ejemplo: `172.16.0.0/21,172.17.0.0/21`
 a| 
Opcional

|===


==== ADMIN_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La dirección IPv4 de la puerta de enlace de red de administrador local para este nodo. Debe estar en la subred definida por ADMIN_NETWORK_IP y ADMIN_NETWORK_MASK. Este valor se omite para redes configuradas con DHCP.

Ejemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Obligatorio si `ADMIN_NETWORK_ESL` se especifica. Opcional de lo contrario.

|===


==== IP_RED_ADMIN

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La dirección IPv4 de este nodo en la red administrativa. Esta clave solo es necesaria cuando ADMIN_NETWORK_CONFIG = STATIC; no la especifique para otros valores.

Ejemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Necesario cuando ADMIN_NETWORK_CONFIG = STATIC.

Opcional de lo contrario.

|===


==== ADMIN_NETWORK_MAC

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La dirección MAC de la interfaz de red de administración en el contenedor.

Este campo es opcional. Si se omite, se generará automáticamente una dirección MAC.

Debe tener 6 pares de dígitos hexadecimales separados por dos puntos.

Ejemplo: `b2:9c:02:c2:27:10`
 a| 
Opcional

|===


==== ADMIN_NETWORK_MASK

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La máscara de red IPv4 para este nodo, en la red de administrador. Especifique esta clave cuando ADMIN_NETWORK_CONFIG = STATIC; no la especifique para otros valores.

Ejemplos:

`255.255.255.0`

`255.255.248.0`
 a| 
Necesario si se especifica ADMIN_NETWORK_IP y ADMIN_NETWORK_CONFIG = STATIC.

Opcional de lo contrario.

|===


==== MTU_RED_ADMIN

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La unidad de transmisión máxima (MTU) para este nodo en la red de administración. No especifique si ADMIN_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se utiliza 1500.

Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado.

*IMPORTANTE*: El valor MTU de la red debe coincidir con el valor configurado en el puerto del switch al que está conectado el nodo. De lo contrario, pueden ocurrir problemas de rendimiento de red o pérdida de paquetes.

Ejemplos:

`1500`

`8192`
 a| 
Opcional

|===


==== ADMIN_NETWORK_TARGET

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Nombre del dispositivo host que utilizará para el acceso a la red de administración mediante el nodo StorageGRID. Solo se admiten nombres de interfaces de red. Normalmente, se utiliza un nombre de interfaz diferente al especificado para GRID_NETWORK_TARGET o CLIENT_NETWORK_TARGET.

*Nota*: No utilice dispositivos de enlace o puente como objetivo de red. Configure una VLAN (u otra interfaz virtual) en la parte superior del dispositivo de enlace o utilice un puente y un par Ethernet virtual (veth).

*Mejor práctica*:especifique un valor aunque este nodo no tenga inicialmente una dirección IP de red de administración. Después, puede añadir una dirección IP de red de administrador más adelante, sin tener que volver a configurar el nodo en el host.

Ejemplos:

`bond0.1002`

`ens256`
 a| 
Mejor práctica

|===


==== ADMIN_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Interfaz (este es el único valor admitido.)
 a| 
Opcional

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Verdadero o Falso

Establezca la clave en "TRUE" para que el contenedor StorageGRID use la dirección MAC de la interfaz de destino del host en la red de administración.

*Mejor práctica:* en redes donde se requiera el modo promiscuo, utilice la clave ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC en su lugar.

Para obtener más detalles sobre la clonación de MAC para Linux, consultelink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Consideraciones y recomendaciones para la clonación de direcciones MAC"]
 a| 
Mejor práctica

|===


==== ADMIN_ROLE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Primario o no primario

Esta clave solo es necesaria cuando NODE_TYPE = VM_ADMIN_Node; no la especifique para otros tipos de nodos.
 a| 
Necesario cuando NODE_TYPE = VM_ADMIN_Node

Opcional de lo contrario.

|===


=== Bloquear las teclas del dispositivo



==== BLOCK_DEVICE_AUDIT_LOGS

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La ruta y el nombre del archivo especial del dispositivo de bloque que este nodo utilizará para el almacenamiento persistente de los registros de auditoría.

Ejemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
Necesario para nodos con NODE_TYPE = VM_ADMIN_Node. No lo especifique para otros tipos de nodo.

|===


==== BLOQUE_DISPOSITIVO_RANGEDB_NNNN

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Ruta y nombre del archivo especial del dispositivo de bloque que este nodo utilizará para el almacenamiento de objetos persistente. Esta clave solo es necesaria para los nodos con NODE_TYPE = VM_Storage_Node; no la especifique para otros tipos de nodos.

Sólo SE requiere BLOCK_DEVICE_RANGEDB_000; el resto es opcional. El dispositivo de bloque especificado para BLOCK_DEVICE_RANGEDB_000 debe tener al menos 4 TB; los demás pueden ser más pequeños.

No deje espacios vacíos. Si especifica BLOCK_DEVICE_RANGEDB_005, también debe especificar BLOCK_DEVICE_RANGEDB_004.

*Nota*: Para la compatibilidad con las implementaciones existentes, las claves de dos dígitos son compatibles con los nodos actualizados.

Ejemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
Obligatorio:

BLOQUE_DISPOSITIVO_RANGEDB_000

Opcional:

BLOQUE_DISPOSITIVO_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== BLOCK_DEVICE_TABLES

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Ruta y nombre del archivo especial del dispositivo de bloque que este nodo utilizará para el almacenamiento persistente de tablas de bases de datos. Esta clave solo es necesaria para los nodos con NODE_TYPE = VM_ADMIN_Node; no la especifique para otros tipos de nodos.

Ejemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
Obligatorio

|===


==== BLOCK_DEVICE_VAR_LOCAL

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Ruta de acceso y nombre del archivo especial del dispositivo de bloque Este nodo utilizará para su `/var/local` almacenamiento persistente.

Ejemplos:

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
Obligatorio

|===


=== Claves de red cliente



==== CLIENT_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
DHCP, ESTÁTICO O DESHABILITADO
 a| 
Opcional

|===


==== PUERTA_DE_ENLACE_RED_CLIENTE

[cols="4a,2a"]
|===


 a| 
Valor
 a| 
Designación



 a| 
Dirección IPv4 de la puerta de enlace de red de cliente local para este nodo, que debe estar en la subred definida por CLIENT_NETWORK_IP y CLIENT_NETWORK_MASK. Este valor se omite para redes configuradas con DHCP.

Ejemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Opcional

|===


==== IP_RED_CLIENTE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La dirección IPv4 de este nodo en la red cliente.

Esta clave solo es necesaria cuando CLIENT_NETWORK_CONFIG = STATIC; no la especifique para otros valores.

Ejemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Necesario cuando CLIENT_NETWORK_CONFIG = ESTÁTICO

Opcional de lo contrario.

|===


==== MAC_RED_CLIENTE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La dirección MAC de la interfaz de red de cliente en el contenedor.

Este campo es opcional. Si se omite, se generará automáticamente una dirección MAC.

Debe tener 6 pares de dígitos hexadecimales separados por dos puntos.

Ejemplo: `b2:9c:02:c2:27:20`
 a| 
Opcional

|===


==== MÁSCARA_RED_CLIENTE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La máscara de red IPv4 para este nodo en la red de cliente.

Especifique esta clave cuando CLIENT_NETWORK_CONFIG = STATIC; no la especifique para otros valores.

Ejemplos:

`255.255.255.0`

`255.255.248.0`
 a| 
Necesario si se especifica CLIENT_NETWORK_ip y CLIENT_NETWORK_CONFIG = ESTÁTICO

Opcional de lo contrario.

|===


==== MTU_RED_CLIENTE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La unidad de transmisión máxima (MTU) para este nodo en la red cliente. No especifique si CLIENT_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se utiliza 1500.

Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado.

*IMPORTANTE*: El valor MTU de la red debe coincidir con el valor configurado en el puerto del switch al que está conectado el nodo. De lo contrario, pueden ocurrir problemas de rendimiento de red o pérdida de paquetes.

Ejemplos:

`1500`

`8192`
 a| 
Opcional

|===


==== DESTINO_RED_CLIENTE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Nombre del dispositivo host que utilizará para el acceso a la red de cliente mediante el nodo StorageGRID. Solo se admiten nombres de interfaces de red. Normalmente, se utiliza un nombre de interfaz diferente al especificado para GRID_NETWORK_TARGET o ADMIN_NETWORK_TARGET.

*Nota*: No utilice dispositivos de enlace o puente como objetivo de red. Configure una VLAN (u otra interfaz virtual) en la parte superior del dispositivo de enlace o utilice un puente y un par Ethernet virtual (veth).

*Mejor práctica:* especifique un valor aunque este nodo no tenga inicialmente una dirección IP de red de cliente. Después puede añadir una dirección IP de red de cliente más tarde, sin tener que volver a configurar el nodo en el host.

Ejemplos:

`bond0.1003`

`ens423`
 a| 
Mejor práctica

|===


==== CLIENT_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Interfaz (solo se admite este valor.)
 a| 
Opcional

|===


==== CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Verdadero o Falso

Establezca la clave en "true" para hacer que el contenedor StorageGRID utilice la dirección MAC de la interfaz de destino del host en la red cliente.

*Mejor práctica:* en redes donde se requiera el modo promiscuo, utilice la clave CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC en su lugar.

Para obtener más detalles sobre la clonación de MAC para Linux, consultelink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Consideraciones y recomendaciones para la clonación de direcciones MAC"]
 a| 
Mejor práctica

|===


=== Claves de red de cuadrícula



==== GRID_NETWORK_CONFIG

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
ESTÁTICO o DHCP

El valor por defecto es ESTÁTICO si no se especifica.
 a| 
Mejor práctica

|===


==== PUERTA_DE_ENLACE_RED_GRID

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Dirección IPv4 de la puerta de enlace de red local para este nodo, que debe estar en la subred definida por GRID_NETWORK_IP y GRID_NETWORK_MASK. Este valor se omite para redes configuradas con DHCP.

Si la red de red es una subred única sin puerta de enlace, utilice la dirección de puerta de enlace estándar de la subred (X.30 Z.1) o el valor DE GRID_NETWORK_IP de este nodo; cualquiera de los dos valores simplificará las posibles futuras expansiones de red de cuadrícula.
 a| 
Obligatorio

|===


==== IP_RED_GRID

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Dirección IPv4 de este nodo en la red de cuadrícula. Esta clave solo es necesaria cuando GRID_NETWORK_CONFIG = STATIC; no la especifique para otros valores.

Ejemplos:

`1.1.1.1`

`10.224.4.81`
 a| 
Necesario cuando GRID_NETWORK_CONFIG = ESTÁTICO

Opcional de lo contrario.

|===


==== MAC_RED_GRID

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La dirección MAC de la interfaz de red de red del contenedor.

Debe tener 6 pares de dígitos hexadecimales separados por dos puntos.

Ejemplo: `b2:9c:02:c2:27:30`
 a| 
Opcional

Si se omite, se generará automáticamente una dirección MAC.

|===


==== GRID_NETWORK_MASK

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Máscara de red IPv4 para este nodo en la red de cuadrícula. Especifique esta clave cuando GRID_NETWORK_CONFIG = STATIC; no la especifique para otros valores.

Ejemplos:

`255.255.255.0`

`255.255.248.0`
 a| 
Necesario cuando se especifica GRID_NETWORK_ip y GRID_NETWORK_CONFIG = ESTÁTICO.

Opcional de lo contrario.

|===


==== MTU_RED_GRID

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La unidad de transmisión máxima (MTU) para este nodo en la red Grid. No especifique si GRID_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se utiliza 1500.

Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado.

*IMPORTANTE*: El valor MTU de la red debe coincidir con el valor configurado en el puerto del switch al que está conectado el nodo. De lo contrario, pueden ocurrir problemas de rendimiento de red o pérdida de paquetes.

*IMPORTANTE*: Para obtener el mejor rendimiento de red, todos los nodos deben configurarse con valores MTU similares en sus interfaces de red Grid. La alerta *Red de cuadrícula MTU* se activa si hay una diferencia significativa en la configuración de MTU para la Red de cuadrícula en nodos individuales. No es necesario que los valores de MTU sean los mismos para todos los tipos de red.

Ejemplos:

`1500`

`8192`
 a| 
Opcional

|===


==== GRID_NETWORK_TARGET

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Nombre del dispositivo host que utilizará para el acceso a la red de cuadrícula mediante el nodo StorageGRID. Solo se admiten nombres de interfaces de red. Normalmente, se utiliza un nombre de interfaz diferente al especificado para ADMIN_NETWORK_TARGET o CLIENT_NETWORK_TARGET.

*Nota*: No utilice dispositivos de enlace o puente como objetivo de red. Configure una VLAN (u otra interfaz virtual) en la parte superior del dispositivo de enlace o utilice un puente y un par Ethernet virtual (veth).

Ejemplos:

`bond0.1001`

`ens192`
 a| 
Obligatorio

|===


==== GRID_NETWORK_TARGET_TYPE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Interfaz (este es el único valor admitido.)
 a| 
Opcional

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Verdadero o Falso

Establezca el valor de la clave en "verdadero" para que el contenedor StorageGRID utilice la dirección MAC de la interfaz de destino del host en la red de red.

*Mejor práctica:* en redes donde se requiera el modo promiscuo, utilice la clave GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC en su lugar.

Para obtener más detalles sobre la clonación de MAC para Linux, consultelink:../swnodes/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["Consideraciones y recomendaciones para la clonación de direcciones MAC"]
 a| 
Mejor práctica

|===


=== Clave de contraseña de instalación (temporal)



==== CUSTOM_TEMPORARY_PASSWORD_HASH

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Para el nodo de administración principal, establezca una contraseña temporal predeterminada para la API de instalación de StorageGRID durante la instalación.

*Nota*: Establece una contraseña de instalación solo en el nodo de administración principal. Si intenta establecer una contraseña en otro tipo de nodo, la validación del archivo de configuración de nodo fallará.

La configuración de este valor no tiene efecto cuando la instalación ha finalizado.

Si se omite esta clave, de forma predeterminada no se establece ninguna contraseña temporal. Como alternativa, puede establecer una contraseña temporal con la API de instalación de StorageGRID.

Debe ser un `crypt()` hash de contraseña SHA-512 con formato `$6$<salt>$<password hash>` para una contraseña de al menos 8 y no más de 32 caracteres.

Este hash se puede generar utilizando herramientas de la CLI, como el `openssl passwd` comando en modo SHA-512.
 a| 
Mejor práctica

|===


=== Clave de interfaces



==== INTERFAZ_DESTINO_nnnn

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Nombre y descripción opcional para una interfaz adicional que se desea añadir a este nodo. Puede añadir varias interfaces adicionales a cada nodo.

Para _nnnn_, especifique un número único para cada entrada de INTERFAZ_DESTINO que agregue.

Para el valor, especifique el nombre de la interfaz física en el host de configuración básica. A continuación, de manera opcional, añada una coma y proporcione una descripción de la interfaz, que se muestra en la página interfaces VLAN y en la página grupos de alta disponibilidad.

Ejemplo: `INTERFACE_TARGET_0001=ens256, Trunk`

Si añade una interfaz troncal, debe configurar una interfaz VLAN en StorageGRID. Si agrega una interfaz de acceso, puede añadir la interfaz directamente a un grupo de alta disponibilidad; no es necesario configurar una interfaz de VLAN.
 a| 
Opcional

|===


=== Clave RAM máxima



==== RAM_MÁXIMA

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
La cantidad máxima de RAM que se permite que este nodo consuma. Si se omite esta clave, el nodo no tiene restricciones de memoria. Al establecer este campo para un nodo de nivel de producción, especifique un valor que sea al menos 24 GB y 16 a 32 GB menor que la RAM total del sistema.

*Nota*: El valor de la RAM afecta al espacio reservado real de metadatos de un nodo. Consulte la link:../admin/managing-object-metadata-storage.html["Descripción del espacio reservado de metadatos"].

El formato de este campo es `_numberunit_`, donde `_unit_` puede ser `b`, , `k`, , `m` o `g`.

Ejemplos:

`24g`

`38654705664b`

*Nota*: Si desea utilizar esta opción, debe activar el soporte de núcleo para grupos de memoria.
 a| 
Opcional

|===


=== Claves de tipo de nodo



==== TIPO_NODO

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Tipo de nodo:

* VM_Admin_Node
* VM_Storage_Node
* VM_Archive_Node
* Puerta de enlace_API_VM

 a| 
Obligatorio

|===


==== STORAGE_TYPE

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Define el tipo de objetos que contiene un nodo de almacenamiento. Para obtener más información, consulte link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nodos de almacenamiento"]. Esta clave solo es necesaria para los nodos con NODE_TYPE = VM_Storage_Node; no la especifique para otros tipos de nodos. Tipos de almacenamiento:

* combinado
* los datos
* metadatos


*Nota*: Si no se especifica el STORAGE_TYPE, el tipo de nodo de almacenamiento se establece en Combinado (datos y metadatos) por defecto.
 a| 
Opcional

|===


=== Claves de reasignación de puertos


NOTE: La compatibilidad con la reasignación de puertos está obsoleta y se eliminará en una versión futura. Para eliminar los puertos reasignados, consultelink:../maintain/removing-port-remaps-on-bare-metal-hosts.html["Quite las reasignaciones de puertos en hosts sin sistema operativo"] .



==== REASIGNAR_PUERTO

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Reasigna cualquier puerto que usa un nodo para las comunicaciones internas del nodo de grid o las comunicaciones externas. La reasignación de puertos es necesaria si las políticas de red de la empresa restringen uno o más puertos utilizados por StorageGRID, como se describe en link:../network/internal-grid-node-communications.html["Comunicaciones internas de los nodos de grid"] o link:../network/external-communications.html["Comunicaciones externas"].

*IMPORTANTE*: No reasigne los puertos que planea usar para configurar los puntos finales del equilibrador de carga.

*Nota*: Si sólo SE establece PORT_REMAPP, la asignación que especifique se utiliza tanto para comunicaciones entrantes como salientes. Si TAMBIÉN se especifica PORT_REMAPP_INBOUND, PORT_REMAPP sólo se aplica a las comunicaciones salientes.

El formato utilizado es `_network type_/_protocol_/_default port used by grid node_/_new port_`: , Donde `_network type_` es grid, admin o client, y `_protocol_` es tcp o udp.

Ejemplo: `PORT_REMAP = client/tcp/18082/443`

También puede volver a asignar varios puertos mediante una lista separada por comas.

Ejemplo: `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
Opcional

|===


==== PORT_REMAPP_INBOUND

[cols="4a,2a"]
|===
| Valor | Designación 


 a| 
Reasigna las comunicaciones entrantes al puerto especificado. Si especifica PORT_REMAP_INBOUND pero no especifica un valor para PORT_REMAP, las comunicaciones salientes para el puerto no cambian.

*IMPORTANTE*: No reasigne los puertos que planea usar para configurar los puntos finales del equilibrador de carga.

El formato utilizado es `_network type_/_protocol_/_remapped port_/_default port used by grid node_`: , Donde `_network type_` es grid, admin o client, y `_protocol_` es tcp o udp.

Ejemplo: `PORT_REMAP_INBOUND = grid/tcp/3022/22`

También puede volver a asignar varios puertos de entrada mediante una lista separada por comas.

Ejemplo: `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
Opcional

|===