= 
:allow-uri-read: 


[role="tabbed-block"]
====
.Datos replicados
--
* Para obtener un porcentaje de finalización estimado para la reparación replicada, agregue `show-replicated-repair-status` la opción al comando repair-data.
+
`repair-data show-replicated-repair-status`

* Para determinar si las reparaciones están completas:
+
.. Seleccione *Nodos* > *_Nodo de almacenamiento en reparación_* > *ILM*.
.. Revise los atributos en la sección Evaluación. Una vez completadas las reparaciones, el atributo *esperando - todo* indica 0 objetos.


* Para supervisar la reparación con más detalle:
+
.. Seleccionar *Nodos*.
.. Seleccione *_grid name_* > *ILM*.
.. Coloque el cursor sobre el gráfico de la cola ILM para ver el valor del atributo *Velocidad de escaneo (objetos/seg)*, que es la velocidad a la que se escanean los objetos en la cuadrícula y se ponen en cola para ILM.
.. En la sección Cola ILM, observe los siguientes atributos:
+
*** *Período de escaneo - Estimado*: El tiempo estimado para completar una exploración completa de ILM de todos los objetos.
+
Un escaneo completo no garantiza que ILM se haya aplicado a todos los objetos.

*** *Reparaciones intentadas*: la cantidad total de operaciones de reparación de objetos intentadas para datos replicados que se consideran de alto riesgo.  Los objetos de alto riesgo son todos aquellos que conservan una copia, ya sea por especificación de la política de ILM o como resultado de copias perdidas.  Este recuento aumenta cada vez que un nodo de almacenamiento intenta reparar un objeto de alto riesgo.  Las reparaciones de ILM de alto riesgo se priorizan si la red se sobrecarga.
+
La misma reparación del objeto podría incrementarse nuevamente si la replicación falla después de la reparación.  + Estos atributos pueden ser útiles cuando supervisa el progreso de la recuperación del volumen del nodo de almacenamiento.  Si el número de reparaciones intentadas ha dejado de aumentar y se ha completado un análisis completo, es probable que la reparación se haya completado.



.. Alternativamente, envíe una consulta de Prometheus para `storagegrid_ilm_scan_period_estimated_minutes` y `storagegrid_ilm_repairs_attempted` .




--
.Datos con código de borrado (EC)
--
Para supervisar la reparación de datos codificados mediante borrado y vuelva a intentar cualquier solicitud que pudiera haber fallado:

. Determine el estado de las reparaciones de datos codificadas por borrado:
+
** Seleccione *Soporte* > *Herramientas* > *Métricas* para ver el tiempo estimado de finalización y el porcentaje de finalización del trabajo actual.  Luego, seleccione *Descripción general de EC* en la sección Grafana.  Consulte los paneles *Tiempo estimado de finalización del trabajo de Grid EC* y *Porcentaje de trabajo de Grid EC completado*.
** Use este comando para ver el estado de una operación específica `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilice este comando para enumerar todas las reparaciones:
+
`repair-data show-ec-repair-status`

+
La salida muestra información, incluida `repair ID`, para todas las reparaciones que se estaban ejecutando anteriormente y actualmente.



. Si el resultado muestra que la operación de reparación falló, use `--repair-id` la opción para volver a intentar la reparación.
+
Este comando vuelve a intentar una reparación de nodo con fallos mediante el ID de reparación 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Este comando reintenta realizar una reparación de volumen con fallos mediante el ID de reparación 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====