---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: Puede usar el administrador de inquilinos para crear bloques S3 para los datos de objetos. 
---
= Cree un bloque de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar el administrador de inquilinos para crear bloques S3 para los datos de objetos.

.Antes de empezar
* Ha iniciado sesión en el gestor de inquilinos mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Pertenece a un grupo de usuarios que tiene acceso root o Gestionar todos los cubos link:tenant-management-permissions.html["permiso"]. Estos permisos anulan la configuración de los permisos en las políticas de grupo o bloque.
+

NOTE: Los permisos para establecer o modificar las propiedades de Bloqueo de objetos S3 de cubos u objetos pueden ser otorgados por link:../s3/bucket-and-group-access-policies.html["política de bloques o política de grupo"].

* Si tiene previsto habilitar el bloqueo de objetos de S3 para un depósito, un administrador de grid ha habilitado la configuración global de bloqueo de objetos de S3 para el sistema StorageGRID y ha revisado los requisitos para los bloques y objetos de bloqueo de objetos de S3.
* Si cada inquilino tendrá 5.000 buckets, cada nodo de almacenamiento del grid tiene un mínimo de 64 GB de RAM.
+

NOTE: Cada rejilla puede tener un máximo de 100.000 cubos.





== Acceda al asistente

.Pasos
. Seleccione *Ver cubos* en el panel de control o seleccione *ALMACENAMIENTO (S3)* > *Buckets*.
. Seleccione *Crear cucharón*.




== Introduzca los detalles

.Pasos
. Introduzca los detalles del cucharón.
+
[cols="1a,3a"]
|===
| Campo | Descripción 


 a| 
Nombre del bloque
 a| 
Un nombre para el depósito que cumple con estas reglas:

** Debe ser único en cada sistema StorageGRID (no solo dentro de la cuenta de inquilino).
** Debe ser compatible con DNS.
** Debe contener al menos 3 y no más de 63 caracteres.
** Cada etiqueta debe comenzar y terminar con una letra minúscula o un número y solo puede utilizar letras minúsculas, números y guiones.
** No debe contener periodos en las solicitudes de estilo alojadas virtuales. Los períodos provocarán problemas en la verificación del certificado comodín del servidor.


Para obtener más información, consulte la https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Documentación de Amazon Web Services (AWS) sobre reglas de nomenclatura de bloques"^].

*Nota*: No puedes cambiar el nombre del cubo después de crear el cubo.



 a| 
Región
 a| 
La región del cubo.

El administrador de StorageGRID gestiona las regiones disponibles. La región de un bloque puede afectar la política de protección de datos aplicada a los objetos. Por defecto, todos los cubos se crean en la `us-east-1` región.

*Nota*: No puedes cambiar la región después de crear el cubo.

|===
. Seleccione *continuar*.




== Gestionar configuración

.Pasos
. Opcionalmente, habilite el control de versiones del objeto para el bloque.
+
Habilite el control de versiones de objetos si desea almacenar cada versión de cada objeto en este bloque. A continuación, puede recuperar versiones anteriores de un objeto según sea necesario. Debe habilitar el control de versiones de objetos si el bloque se va a utilizar para la replicación entre grid.

. Si la opción Bloqueo de objetos S3 global está habilitada, habilite opcionalmente Bloqueo de objetos S3 para que el depósito almacene objetos utilizando un modelo WORM.
+
Habilite el bloqueo de objetos S3 para un depósito solo si necesita mantener objetos durante un tiempo fijo, por ejemplo, para cumplir con ciertos requisitos normativos. S3 Object Lock es una configuración permanente que le ayuda a evitar que los objetos se eliminen o sobrescriban durante un período de tiempo fijo o indefinidamente.

+

CAUTION: Una vez que se habilita la configuración Bloqueo de objetos S3 para un depósito, no se puede desactivar. Cualquier persona con los permisos correctos puede agregar objetos a este depósito que no se pueden cambiar. Es posible que no pueda eliminar estos objetos o el cubo en sí.

+
Si habilita S3 Object Lock para un bloque, el control de versiones de bloques se habilita automáticamente.

. Si seleccionó *Habilitar bloqueo de objetos S3*, opcionalmente habilite *Retención predeterminada* para este depósito.
+

NOTE: El administrador de grid debe darle permiso a link:../tenant/using-s3-object-lock.html["Utilice características específicas de S3 Object Lock"].

+
Cuando se habilita *Retención predeterminada*, los nuevos objetos agregados al depósito se protegerán automáticamente de ser eliminados o sobrescritos. La configuración *default retention* no se aplica a los objetos que tienen sus propios periodos de retención.

+
.. Si *Retención predeterminada* está habilitada, especifique un *Modo de retención predeterminado* para el depósito.
+
[cols="1a,2a"]
|===
| Modo de retención predeterminado | Descripción 


 a| 
Gobernanza
 a| 
*** Los usuarios con `s3:BypassGovernanceRetention` permiso pueden utilizar `x-amz-bypass-governance-retention: true` la cabecera de solicitud para omitir la configuración de retención.
*** Estos usuarios pueden suprimir una versión de objeto antes de alcanzar su fecha de retención hasta la fecha.
*** Estos usuarios pueden aumentar, disminuir o eliminar la fecha de retención de un objeto.




 a| 
Cumplimiento de normativas
 a| 
*** El objeto no se puede eliminar hasta que se alcance su fecha de retención hasta.
*** La fecha de retención del objeto se puede aumentar, pero no se puede reducir.
*** No se puede eliminar la fecha de retención del objeto hasta que se alcance esa fecha.


*Nota*: Su administrador de grid debe permitirle usar el modo de cumplimiento.

|===
.. Si *Retención predeterminada* está habilitada, especifique el *Período de retención predeterminado* para el depósito.
+
El *período de retención predeterminado* indica cuánto tiempo deben conservarse los nuevos objetos agregados a este depósito, a partir del momento en que se ingieren. Especifique un valor inferior o igual al período de retención máximo del inquilino, según lo establece el administrador de grid.

+
Un período de retención _maximum_, que puede ser un valor de 1 día a 100 años, se establece cuando el administrador de grid crea el inquilino. Cuando establece un período de retención _default_, no puede exceder el valor establecido para el período de retención máximo. Si es necesario, pida al administrador de grid que aumente o reduzca el período de retención máximo.



. [[capacity-limit]]Opcionalmente, seleccione *Enable capacity limit*.
+
El límite de capacidad es la capacidad máxima disponible para los objetos de este bloque. Este valor representa una cantidad lógica (tamaño de objeto), no una cantidad física (tamaño en disco).

+
Si no se establece ningún límite, la capacidad de este depósito es ilimitada. Consulte link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["Límite de uso de capacidad"] si desea obtener más información.

. Seleccione *Crear cucharón*.
+
El cucharón se crea y se agrega a la tabla de la página Cuches.

. Opcionalmente, seleccione *Ir a la página de detalles del depósito* para link:viewing-s3-bucket-details.html["ver detalles del período"]realizar una configuración adicional.

