---
permalink: tenant/enable-cross-origin-resource-sharing-for-management-interface.html 
sidebar: sidebar 
keywords: how to configure cross-origin resource sharing, cors, management, api, domain 
summary: 'Puede habilitar el uso compartido de recursos entre orígenes (CORS) para solicitudes de API de gestión a StorageGRID si desea que se pueda acceder a los datos en StorageGRID a través de las API de gestión de otro dominio.' 
---
= Active StorageGRID CORS para una interfaz de gestión
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar el uso compartido de recursos entre orígenes (CORS) para solicitudes de API de gestión a StorageGRID si desea que se pueda acceder a los datos en StorageGRID a través de las API de gestión de otro dominio.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* El link:tenant-management-permissions.html["Permiso de acceso raíz"] proporciona acceso a todas las solicitudes de configuración de CORS.


.Acerca de esta tarea
CORS es un mecanismo de seguridad que permite a las aplicaciones web de cliente en un dominio acceder a recursos en un dominio diferente. Por ejemplo, supongamos que desea crear un panel de control para StorageGRID en el dominio `\http://www.example.com`. Al habilitar CORS en StorageGRID para `\http://www.example.com` y Grid Manager, el dominio de StorageGRID responde a las solicitudes de API de gestión de grid de `\http://www.example.com` .

Las solicitudes de API de gestión (mgmt-api) con `application/json` o `multipart/formdata` solicitudes para `Content-Type` son compatibles con CORS.

.Pasos
. En *Red* en la página Configuración de StorageGRID, selecciona *Configuración de CORS de la interfaz de administración*.
. Seleccione *Grid Manager*, *Tenant Manager*, o ambas opciones.
+
** *Grid Manager*: Habilita CORS para solicitudes de API de administración de grid entre dominios.
** *Gestor de inquilinos*: Habilita CORS para solicitudes de API de administración de inquilinos entre dominios.


. Introduzca la URL del otro dominio en el campo *Dominios*.
+
Seleccione *Agregar otro dominio* si desea habilitar CORS en StorageGRID para más de un dominio.

. Seleccione *Guardar*.


.Información relacionada
link:configuring-cross-origin-resource-sharing-for-buckets-and-objects.html["Configurar StorageGRID CORS para cubos y objetos"]
