---
permalink: tenant/guidelines-for-configuring-openldap-server.html 
sidebar: sidebar 
keywords: how to configure open ldap 
summary: Si desea utilizar un servidor OpenLDAP para la federación de identidades, debe configurar ajustes específicos en el servidor OpenLDAP. 
---
= Instrucciones para configurar el servidor OpenLDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si desea utilizar un servidor OpenLDAP para la federación de identidades, debe configurar ajustes específicos en el servidor OpenLDAP.



== Revestimientos memberOf y reft

Se deben habilitar las superposiciones memberof y reft. Para obtener más información, consulte las instrucciones para el mantenimiento de miembros del grupo inverso en la _OpenLDAP Software Administrator's Guide_.



== Indización

Debe configurar los siguientes atributos OpenLDAP con las palabras clave de índice especificadas:

[listing]
----
olcDbIndex: objectClass eq
olcDbIndex: uid eq,pres,sub
olcDbIndex: cn eq,pres,sub
olcDbIndex: entryUUID eq
----
Además, asegúrese de que los campos mencionados en la ayuda para Nombre de usuario estén indexados para un rendimiento óptimo.

Consulte la información sobre el mantenimiento de miembros del grupo inverso en la _OpenLDAP Software Administrator's Guide_.
