---
permalink: tenant/manage-branch-buckets.html 
sidebar: sidebar 
keywords: how to create branch bucket 
summary: Un depósito de bifurcación proporciona acceso a los objetos de un depósito tal y como existían en un momento determinado, siempre y cuando todavía existan en el depósito. Utilice el gestor de inquilinos para crear y ver bloques de bifurcación. 
---
= Gestionar depósitos de bifurcación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un depósito de bifurcación proporciona acceso a los objetos de un depósito tal y como existían en un momento determinado, siempre y cuando todavía existan en el depósito. Utilice el gestor de inquilinos para crear y ver bloques de bifurcación.

Un bloque de sucursales proporciona acceso a datos protegidos, pero no sirve como backup. Para seguir protegiendo los datos, utilice estas funciones en los bloques base:

* link:../tenant/using-s3-object-lock.html["Bloqueo de objetos de S3"]
* link:../admin/grid-federation-what-is-cross-grid-replication.html["Replicación entre grid"] para cucharones base
* link:../tenant/manage-bucket-policy.html["Políticas de bloques"] para cubos con versiones para limpiar versiones de objetos antiguos


.Acerca de esta tarea
Puede crear un depósito de bifurcación a partir de un depósito existente. Después de crear un depósito de bifurcación, el depósito original desde el que se creó se denomina cubo base. Además, puede crear un depósito de bifurcación a partir de otro depósito de bifurcación. Al realizar operaciones en el depósito base, los resultados del depósito de bifurcación dependen de la operación y del tipo de depósito de bifurcación que haya creado.

Puede utilizar un depósito de bifurcación para eliminar objetos corruptos creando un depósito de bifurcación desde un punto en el tiempo anterior a la corrupción y, a continuación, apuntando las aplicaciones al depósito de bifurcación en lugar de al depósito base que contiene objetos corruptos.


CAUTION: Un bloque de sucursales no sirve como backup, pero proporciona acceso a los datos protegidos. Debe seguir usando link:../ilm/managing-objects-with-s3-object-lock.html["Bloqueo de objetos de S3"] o link:../admin/grid-federation-what-is-cross-grid-replication.html["replicación entre grid"]protegiendo los datos.

La replicación entre grid no es compatible con bloques de sucursales.

.Antes de empezar
* Ha iniciado sesión en el gestor de inquilinos mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Pertenece a un grupo de usuarios que tiene acceso root o Gestionar todos los cubos link:tenant-management-permissions.html["permiso"]. Estos permisos anulan la configuración de los permisos en las políticas de grupo o bloque.
* El cubo base desde el que desea crear una bifurcación tiene link:../tenant/changing-bucket-versioning.html["control de versiones activado"].
* Usted es el propietario del cubo base.
+

NOTE: Los permisos para establecer o modificar las propiedades de Bloqueo de objetos S3 de cubos u objetos pueden ser otorgados por link:../s3/bucket-and-group-access-policies.html["política de bloques o política de grupo"].





== Cree un cucharón de bifurcación

.Pasos
. Seleccione *Ver cubos* en el panel de control o seleccione *ALMACENAMIENTO (S3)* > *Buckets*.
. Seleccione el cubo desde el que desea crear una rama (el «cubo base»).
. En la página de detalles del cubo, selecciona *ramas* > *Crear cubo de rama*.
+
El botón *Crear cubo de rama* está desactivado si el cubo base no tiene el control de versiones activado.





== Introduzca los detalles

.Pasos
. Introduzca los detalles del segmento de bifurcación.
+
[cols="1a,3a"]
|===
| Campo | Descripción 


 a| 
Nombre del depósito de bifurcación
 a| 
Un nombre para el depósito de bifurcación que cumple con estas reglas:

** Debe ser único en cada sistema StorageGRID (no solo dentro de la cuenta de inquilino).
** Debe ser compatible con DNS.
** Debe contener al menos 3 y no más de 63 caracteres.
** Cada etiqueta debe comenzar y terminar con una letra minúscula o un número y solo puede utilizar letras minúsculas, números y guiones.
** No debe contener periodos en las solicitudes de estilo alojadas virtuales. Los períodos provocarán problemas en la verificación del certificado comodín del servidor.


Para obtener más información, consulte la https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Documentación de Amazon Web Services (AWS) sobre reglas de nomenclatura de bloques"^].

*Nota*: No puedes cambiar el nombre después de crear el cubo de la rama.



 a| 
Región (no se puede modificar para los bloques de bifurcación)
 a| 
Región del cucharón de bifurcación.

La región del cucharón de bifurcación debe coincidir con la región del cucharón base, por lo que este campo está desactivado para los cucharones de bifurcación.



 a| 
Antes de la hora
 a| 
Tiempo de corte para las versiones de objeto creadas en el cubo base a las que se puede acceder desde el cubo de bifurcación. El depósito de bifurcación proporciona acceso a las versiones de objeto creadas antes que antes.



 a| 
Tipo de período de bifurcación
 a| 
** *Leer-escribir*: Puedes agregar o eliminar objetos o versiones de objetos en el cubo de la rama.
** *Solo lectura*: No puedes modificar objetos en el cubo de la rama.


|===
. Seleccione *continuar*.




== Gestionar configuración

La configuración de un depósito de bifurcación no afecta a las versiones de objeto del depósito base.

.Pasos
. Si la configuración global Bloqueo de objetos S3 está habilitada, opcionalmente habilite Bloqueo de objetos S3 para el depósito de bifurcación. Para habilitar el bloqueo de objetos S3, el depósito de bifurcación debe ser un depósito de lectura y escritura.
+
Active el bloqueo de objetos S3 para un depósito de bifurcación sólo si necesita mantener los objetos durante un período de tiempo fijo, por ejemplo, para cumplir con ciertos requisitos normativos. S3 Object Lock es una configuración permanente que le ayuda a evitar que los objetos se eliminen o sobrescriban durante un período de tiempo fijo o indefinidamente.

+

CAUTION: Una vez que se habilita la configuración Bloqueo de objetos S3 para un depósito, no se puede desactivar. Cualquier persona con los permisos correctos puede agregar objetos al depósito de bifurcación que no se pueden cambiar. Es posible que no pueda suprimir estos objetos o el cubo de bifurcación en sí.

. Si seleccionó *Habilitar bloqueo de objetos S3*, opcionalmente habilite *Retención predeterminada* para el depósito de sucursales.
+

NOTE: El administrador de grid debe darle permiso a link:../tenant/using-s3-object-lock.html["Utilice características específicas de S3 Object Lock"].

+
Cuando se habilita *Retención predeterminada*, los nuevos objetos agregados al depósito de la sucursal se protegerán automáticamente de ser eliminados o sobrescritos. La configuración *default retention* no se aplica a los objetos que tienen sus propios periodos de retención.

+
.. Si *Retención predeterminada* está habilitada, especifique un *Modo de retención predeterminado* para el depósito de la sucursal.
+
[cols="1a,2a"]
|===
| Modo de retención predeterminado | Descripción 


 a| 
Gobernanza
 a| 
*** Los usuarios con `s3:BypassGovernanceRetention` permiso pueden utilizar `x-amz-bypass-governance-retention: true` la cabecera de solicitud para omitir la configuración de retención.
*** Estos usuarios pueden suprimir una versión de objeto antes de alcanzar su fecha de retención hasta la fecha.
*** Estos usuarios pueden aumentar, disminuir o eliminar la fecha de retención de un objeto.




 a| 
Cumplimiento de normativas
 a| 
*** El objeto no se puede eliminar hasta que se alcance su fecha de retención hasta.
*** La fecha de retención del objeto se puede aumentar, pero no se puede reducir.
*** No se puede eliminar la fecha de retención del objeto hasta que se alcance esa fecha.


*Nota*: Su administrador de grid debe permitirle usar el modo de cumplimiento.

|===
.. Si *Retención predeterminada* está habilitada, especifique el *Período de retención predeterminado* para el depósito de la sucursal.
+
El *período de retención predeterminado* indica cuánto tiempo deben conservarse los nuevos objetos agregados al depósito de la sucursal, a partir del momento en que se ingieren. Especifique un valor inferior o igual al período de retención máximo del inquilino, según lo establece el administrador de grid.

+
Un período de retención _maximum_, que puede ser un valor de 1 día a 100 años, se establece cuando el administrador de grid crea el inquilino. Cuando establece un período de retención _default_, no puede exceder el valor establecido para el período de retención máximo. Si es necesario, pida al administrador de grid que aumente o reduzca el período de retención máximo.



. [[capacity-limit]]Opcionalmente, seleccione *Enable capacity limit*.
+
El límite de capacidad es la capacidad máxima disponible para el cucharón de sucursal. Este valor representa una cantidad lógica (tamaño de objeto), no una cantidad física (tamaño en disco).

+
Si no se establece ningún límite, la capacidad del depósito de bifurcación es ilimitada. Consulte link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["Límite de uso de capacidad"] si desea obtener más información.

+

NOTE: Esta configuración se aplica sólo a los objetos que se ingieren directamente en el depósito de bifurcación y no a los objetos que se pueden ver desde el depósito base a través del depósito de bifurcación.

. Opcionalmente, seleccione *Habilitar límite de recuento de objetos*.
+
El límite de recuento de objetos es el número máximo de objetos que puede contener el cubo de bifurcación. Este valor representa una cantidad lógica (recuento de objetos). Si no se establece ningún límite, el recuento de objetos es ilimitado.

+

NOTE: Esta configuración se aplica sólo a los objetos que se ingieren directamente en el depósito de bifurcación y no a los objetos que se pueden ver desde el depósito base a través del depósito de bifurcación.

. Seleccione *Crear cucharón*.
+
El segmento de bifurcación se crea y se agrega a la tabla de la página Buckets.

. Opcionalmente, seleccione *Ir a la página de detalles del depósito* para link:viewing-s3-bucket-details.html["ver detalles de período de sucursal"]realizar una configuración adicional.
+
En la página de detalles Bucket, algunas opciones de configuración relacionadas con la modificación de los objetos están deshabilitadas para bloques de solo lectura.


