---
permalink: tenant/understanding-notifications-for-buckets.html 
sidebar: sidebar 
keywords: s3 bucket event notification, sequencer key 
summary: Puede habilitar la notificación de eventos para un bucket de S3 si desea que StorageGRID envíe notificaciones sobre eventos especificados a un clúster Kafka de destino o a Amazon Simple Notification Service. 
---
= Comprender las notificaciones para bloques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede habilitar la notificación de eventos para un bucket S3 si desea que StorageGRID envíe notificaciones sobre eventos específicos a un clúster de Kafka de destino, un punto final de webhook o Amazon Simple Notification Service.

Por ejemplo, podría configurar que se envíen alertas a administradores acerca de cada objeto agregado a un bloque, donde los objetos representan los archivos de registro asociados a un evento crítico del sistema.

Las notificaciones de eventos se crean en el bloque de origen tal y como se especifica en la configuración de notificación y se envían al destino. Si un evento asociado con un objeto se realiza correctamente, se crea una notificación sobre ese evento y se pone en cola para su entrega.

La singularidad y el orden de las notificaciones no están garantizados. Como resultado de las operaciones realizadas para garantizar el éxito en la entrega, se podría enviar más de una notificación de un evento al destino. Además, como la entrega es asíncrona, no se garantiza que la ordenación del tiempo de las notificaciones en el destino coincida con la ordenación de eventos del bloque de origen, especialmente en las operaciones que se originan en diferentes sitios de StorageGRID. Puede utilizar la `sequencer` clave en el mensaje de evento para determinar el orden de los eventos de un objeto en particular, como se describe en la documentación de Amazon S3.

Las notificaciones de eventos de StorageGRID siguen la API de Amazon S3 con algunas limitaciones.

* Se admiten los siguientes tipos de evento:
+
** S3:ObjetoCreado:
** S3:ObjectCreated:Put
** S3:ObjectCreated:Post
** S3:ObjectCreated:Copiar
** S3:ObjectCreated:CompleteMultipartUpload
** S3:ObjectRemoved:
** S3:ObjectRemoved:Eliminar
** S3:ObjectRemoved:DeleteMarkerCreated
** S3:ObjectRestore:Post


* Las notificaciones de eventos enviadas desde StorageGRID utilizan el formato JSON estándar, pero no incluyen algunas claves ni utilizan valores específicos para otros, como se muestra en la tabla:


[cols="1a,2a"]
|===
| Nombre de clave | Valor de StorageGRID 


 a| 
EventSource
 a| 
`sgws:s3`



 a| 
AwsRegion
 a| 
_no incluido_



 a| 
x-amz-id-2
 a| 
_no incluido_



 a| 
arn
 a| 
`urn:sgws:s3:::bucket_name`

|===