---
permalink: tenant/update-default-retention-settings.html 
sidebar: sidebar 
keywords: update default retention for s3 object lock bucket, default retention mode, default retention period, compliance, governance 
summary: 'Si habilitó S3 Object Lock al crear el bucket, puede editar el bucket para cambiar la configuración de retención predeterminada. Puede habilitar (o deshabilitar) la retención predeterminada y establecer un modo de retención y un período de retención predeterminados.' 
---
= Actualizar S3 Retención predeterminada de bloqueo de objetos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si habilitó S3 Object Lock al crear el bucket, puede editar el bucket para cambiar la configuración de retención predeterminada. Puede habilitar (o deshabilitar) la retención predeterminada y establecer un modo de retención y un período de retención predeterminados.

.Antes de empezar
* Ha iniciado sesión en el gestor de inquilinos mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Pertenece a un grupo de usuarios que tiene el link:tenant-management-permissions.html["Gestione todos los bloques o permisos de acceso raíz"]. Estos permisos anulan la configuración de los permisos en las políticas de grupo o bloque.
* S3 Bloqueo de objetos está habilitado globalmente para su sistema StorageGRID, y usted habilitó S3 Bloqueo de objetos al crear el bucket. Consulte link:using-s3-object-lock.html["Utilice Bloqueo de objetos S3 para retener objetos"].


.Pasos
. Seleccione *Ver cubos* en el panel de control o seleccione *ALMACENAMIENTO (S3)* > *Buckets*.
. Seleccione el nombre del cubo de la tabla.
+
Aparece la página de detalles bucket.

. En la pestaña *Opciones de cubo*, selecciona el acordeón *S3 Object Lock*.
. Opcionalmente, habilita o deshabilita *Retención predeterminada* para este depósito.
+
Los cambios realizados en esta configuración no se aplican a objetos que ya estén en el depósito ni a objetos que puedan tener sus propios períodos de retención.

. Si *Retención predeterminada* está habilitada, especifique un *Modo de retención predeterminado* para el depósito.
+
[cols="1a,2a"]
|===
| Modo de retención predeterminado | Descripción 


 a| 
Gobernanza
 a| 
** Los usuarios con `s3:BypassGovernanceRetention` permiso pueden utilizar `x-amz-bypass-governance-retention: true` la cabecera de solicitud para omitir la configuración de retención.
** Estos usuarios pueden suprimir una versión de objeto antes de alcanzar su fecha de retención hasta la fecha.
** Estos usuarios pueden aumentar, disminuir o eliminar la fecha de retención de un objeto.




 a| 
Cumplimiento de normativas
 a| 
** El objeto no se puede eliminar hasta que se alcance su fecha de retención hasta.
** La fecha de retención del objeto se puede aumentar, pero no se puede reducir.
** No se puede eliminar la fecha de retención del objeto hasta que se alcance esa fecha.


*Nota*: Su administrador de grid debe permitirle usar el modo de cumplimiento.

|===
. Si *Retención predeterminada* está habilitada, especifique el *Período de retención predeterminado* para el depósito.
+
El *período de retención predeterminado* indica cuánto tiempo deben conservarse los nuevos objetos agregados a este depósito, a partir del momento en que se ingieren. Especifique un valor inferior o igual al período de retención máximo del inquilino, según lo establece el administrador de grid.

+
Un período de retención _maximum_, que puede ser un valor de 1 día a 100 años, se establece cuando el administrador de grid crea el inquilino. Cuando establece un período de retención _default_, no puede exceder el valor establecido para el período de retención máximo. Si es necesario, pida al administrador de grid que aumente o reduzca el período de retención máximo.

. Seleccione *Guardar cambios*.

