---
permalink: tenant/viewing-your-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view your s3 access key 
summary: Si usa un inquilino de S3 y tiene el permiso correspondiente, puede ver una lista de sus claves de acceso S3. Puede ordenar la lista por tiempo de caducidad, de modo que puede determinar qué claves caducarán pronto. Según sea necesario, puede crear nuevas claves o eliminar claves que ya no utilice. 
---
= Consulte las claves de acceso de S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si está utilizando un inquilino de S3 y tiene el link:tenant-management-permissions.html["permiso apropiado"], puede ver una lista de las claves de acceso de S3. Puede ordenar la lista por tiempo de caducidad, de modo que puede determinar qué claves caducarán pronto. Según sea necesario, puede link:creating-your-own-s3-access-keys.html["crear nuevas claves"] o link:deleting-your-own-s3-access-keys.html["teclas de eliminación"] que ya no utilice.


CAUTION: Puede acceder a los bloques y los objetos de S3 que pertenecen a su cuenta mediante el ID de clave de acceso y la clave de acceso secreta que se muestra para su cuenta en el Administrador de inquilinos. Por este motivo, proteja las claves de acceso como lo haría con una contraseña. Gire las claves de acceso de forma regular, elimine las claves que no utilice de su cuenta y nunca las comparta con otros usuarios.

.Antes de empezar
* Ha iniciado sesión en el gestor de inquilinos mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Pertenece a un grupo de usuarios que tiene las credenciales Administrar sus propias credenciales S3 link:tenant-management-permissions.html["permiso"].


.Pasos
. Seleccione *ALMACENAMIENTO (S3)* > *Mis claves de acceso*.
. Desde la página Mis claves de acceso, ordene las claves de acceso existentes por *Tiempo de caducidad* o *ID de clave de acceso*.
. Según sea necesario, cree nuevas claves o elimine las claves que ya no esté utilizando.
+
Si crea claves nuevas antes de que caduquen las claves existentes, puede empezar a utilizar las nuevas claves sin perder temporalmente el acceso a los objetos de la cuenta.

+
Las claves caducadas se eliminan automáticamente.


