---
permalink: tenant/viewing-another-users-s3-access-keys.html 
sidebar: sidebar 
keywords: how to view other user access key 
summary: Si está utilizando un inquilino S3 y tiene los permisos adecuados, puede ver las claves de acceso S3 de otro usuario. Puede ordenar la lista por tiempo de caducidad para que pueda determinar qué claves caducarán pronto. Según sea necesario, puede crear nuevas claves y eliminar claves que ya no estén en uso. 
---
= Ver las claves de acceso S3 de otro usuario
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si usa un inquilino de S3 y tiene los permisos adecuados, puede ver las claves de acceso S3 de otro usuario. Puede ordenar la lista por tiempo de caducidad para que pueda determinar qué claves caducarán pronto. Según sea necesario, puede crear nuevas claves y eliminar claves que ya no estén en uso.

.Antes de empezar
* Ha iniciado sesión en el gestor de inquilinos mediante un link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:tenant-management-permissions.html["Permiso de acceso raíz"].



CAUTION: Es posible acceder a los bloques y los objetos de S3 que pertenecen a un usuario mediante el ID de clave de acceso y la clave de acceso secreta mostrada para ese usuario en el Administrador de inquilinos. Por este motivo, proteja las claves de acceso como lo haría con una contraseña. Gire las claves de acceso de forma regular, elimine las claves que no utilice de la cuenta y nunca las comparta con otros usuarios.

.Pasos
. Seleccione *ADMINISTRACIÓN de ACCESO* > *usuarios*.
. En la página Usuarios, seleccione el usuario cuyas S3 claves de acceso desea ver.
. En la página Detalles del usuario, selecciona *Teclas de acceso*.
. Ordene las teclas por *tiempo de caducidad* o *ID de clave de acceso*.
. Según sea necesario, cree nuevas claves y elimine manualmente las que ya no estén en uso.
+
Si crea claves nuevas antes de que caduquen las claves existentes, el usuario podrá empezar a utilizar las nuevas claves sin perder temporalmente el acceso a los objetos de la cuenta.

+
Las claves caducadas se eliminan automáticamente.



.Información relacionada
* link:creating-another-users-s3-access-keys.html["Cree las claves de acceso S3 de otro usuario"]
* link:deleting-another-users-s3-access-keys.html["Elimine las claves de acceso S3 de otro usuario"]

