---
permalink: vmware/automating-grid-node-deployment-in-vmware-vsphere.html 
sidebar: sidebar 
keywords: how to automate installation 
summary: Puede utilizar la herramienta OVF de VMware para automatizar la implementación de nodos de grid. También puede automatizar la configuración de StorageGRID. 
---
= Automatización de la instalación (VMware)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la herramienta OVF de VMware para automatizar la implementación de nodos de grid. También puede automatizar la configuración de StorageGRID.



== Automatice la puesta en marcha del nodo de grid

Utilice la herramienta VMware OVF para automatizar la implementación de nodos de grid.

.Antes de empezar
* Usted tiene acceso a un sistema Linux/Unix con Bash 3.2 o posterior.
* VMware vSphere tiene vCenter
* Tiene instalada y configurada correctamente la herramienta OVF de VMware 4.1.
* Conoce el nombre de usuario y la contraseña para acceder a VMware vSphere con la herramienta OVF
* Cuenta con los permisos suficientes para implementar máquinas virtuales desde archivos OVF e encenderlas, así como permisos para crear volúmenes adicionales para asociarlos a las máquinas virtuales. Consulte `ovftool` la documentación para obtener más detalles.
* Conoce la URL de infraestructura virtual (VI) para la ubicación en vSphere donde desea implementar las máquinas virtuales de StorageGRID. Esta URL será normalmente un vApp o un grupo de recursos. Por ejemplo: `vi://vcenter.example.com/vi/sgws`
+

NOTE: Puede usar la utilidad VMware `ovftool` para determinar este valor (consulte `ovftool` la documentación para obtener más detalles).

+

NOTE: Si va a implementar en un vApp, los equipos virtuales no se iniciarán automáticamente la primera vez y deberá conectarlos manualmente.

* Recogió toda la información requerida para el archivo de configuración de despliegue. Consulte link:collecting-information-about-your-deployment-environment.html["Recopile información sobre el entorno de implementación"] para obtener más información.
* Tiene acceso a los siguientes archivos desde el archivo de instalación de VMware para StorageGRID:


[cols="1a,1a"]
|===
| Nombre de archivo | Descripción 


| NetApp-SG-versión-SHA.vmdk  a| 
El archivo de disco de máquina virtual que se usa como plantilla para crear máquinas virtuales del nodo de grid.

*Nota:* Este archivo debe estar en la misma carpeta que los `.ovf` archivos y. `.mf`



| vsphere-primary-admin.ovf vsphere-primary-admin.mf  a| 
El archivo de plantilla Open Virtualization Format (`.ovf`) y el archivo de manifiesto (`.mf`) para desplegar el nodo de administración principal.



| vsphere-non-primary-admin.ovf vsphere-non-primary-admin.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) para desplegar nodos de administración no principales.



| vsphere-gateway.ovf vsphere-gateway.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) para desplegar nodos de gateway.



| vsphere-storage.ovf vsphere-storage.mf  a| 
El archivo de plantilla (`.ovf`) y el archivo de manifiesto (`.mf`) para desplegar nodos de almacenamiento basados en máquina virtual.



| deploy-vsphere-ovftool.sh  a| 
La secuencia de comandos de shell Bash utilizada para automatizar la implementación de nodos de cuadrícula virtual.



| deploy-vsphere-ovftool-sample.ini  a| 
El archivo de configuración de ejemplo para utilizar con el `deploy-vsphere-ovftool.sh` script.

|===


=== Defina el archivo de configuración para la implementación

Especifique la información necesaria para desplegar nodos de cuadrícula virtual para StorageGRID en un archivo de configuración, que utiliza el `deploy-vsphere-ovftool.sh` script Bash. Puede modificar un archivo de configuración de ejemplo para que no tenga que crear el archivo desde cero.

.Pasos
. Realice una copia del archivo de configuración de ejemplo (`deploy-vsphere-ovftool.sample.ini`). Guarde el nuevo archivo como `deploy-vsphere-ovftool.ini` en el mismo directorio que `deploy-vsphere-ovftool.sh`.
. Abrir `deploy-vsphere-ovftool.ini`.
. Especifique toda la información necesaria para poner en marcha los nodos de grid virtual de VMware.
+
Consulte <<configuration-file-settings,Ajustes del archivo de configuración>> para obtener más información.

. Cuando haya introducido y verificado toda la información necesaria, guarde y cierre el archivo.




=== Ajustes del archivo de configuración

El `deploy-vsphere-ovftool.ini` archivo de configuración contiene los ajustes necesarios para desplegar los nodos de la cuadrícula virtual.

En primer lugar, el archivo de configuración enumera los parámetros globales y, a continuación, enumera los parámetros específicos del nodo en las secciones definidas por el nombre del nodo. Cuando se utilice el archivo:

* _Parámetros globales_ se aplican a todos los nodos de cuadrícula.
* _Parámetros específicos del nodo_ anulan los parámetros globales.




==== Parámetros globales

Los parámetros globales se aplican a todos los nodos de cuadrícula, a menos que se anulen por la configuración de secciones individuales. Coloque los parámetros que se aplican a varios nodos en la sección global Parameter y, a continuación, anule estos ajustes según sea necesario en las secciones de nodos individuales.

* *OVFTOOL_ARGUMENTS*: Puede especificar OVFTOOL_ARGUMENTS como configuración global o puede aplicar argumentos individualmente a nodos específicos. Por ejemplo:
+
[listing, subs="specialcharacters,quotes"]
----
OVFTOOL_ARGUMENTS = --powerOn --noSSLVerify --diskMode=eagerZeroedThick --datastore='_datastore_name_'
----
+
Puede utilizar las `--powerOffTarget` opciones y `--overwrite` para apagar y reemplazar las máquinas virtuales existentes.

+

CAUTION: Debe implementar nodos en almacenes de datos diferentes y especificar OVFTOOL_ARGUMENTS para cada nodo, en lugar de globalmente.

* *SOURCE*: La ruta al (`.vmdk`archivo de plantilla de máquina virtual de StorageGRID ) y los `.ovf` archivos y `.mf` para los nodos de cuadrícula individuales. De forma predeterminada, se utiliza el directorio actual.
+
[listing, subs="specialcharacters,quotes"]
----
SOURCE = /downloads/StorageGRID-Webscale-_version_/vsphere
----
* *TARGET*: La URL de la infraestructura virtual (vi) de VMware vSphere para la ubicación en la que se va a implementar StorageGRID. Por ejemplo:
+
[listing]
----
TARGET = vi://vcenter.example.com/vm/sgws
----
* *GRID_NETWORK_CONFIG*: Método utilizado para adquirir direcciones IP, TANTO ESTÁTICAS como DHCP. El valor predeterminado es STATIC. Si todos o la mayoría de los nodos utilizan el mismo método para adquirir direcciones IP, puede especificar ese método aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_CONFIG = STATIC
----
* *GRID_NETWORK_TARGET*: El nombre de una red VMware existente que se utilizará para la red Grid. Si todos los nodos utilizan el mismo nombre de red, o la mayoría de ellos, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_TARGET = SG Admin Network
----
* *GRID_NETWORK_MASK*: La máscara de red para la red Grid. Si todos los nodos o la mayoría de ellos utilizan la misma máscara de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_MASK = 255.255.255.0
----
* *GRID_NETWORK_GATEWAY*: El gateway de red para la red Grid. Si todos o la mayoría de los nodos utilizan la misma puerta de enlace de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
GRID_NETWORK_GATEWAY = 10.1.0.1
----
* * GRID_NETWORK_MTU*: OPCIONAL. La unidad de transmisión máxima (MTU) en la red de red. Si se especifica, el valor debe estar entre 1280 y 9216. Por ejemplo:
+
[listing]
----
GRID_NETWORK_MTU = 9000
----
+
Si se omite, se utiliza 1400.

+
Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado.

+

NOTE: El valor de MTU de la red debe coincidir con el valor configurado en el puerto del switch virtual en vSphere al que el nodo está conectado. De lo contrario, pueden ocurrir problemas de rendimiento de red o pérdida de paquetes.

+

NOTE: Para obtener el mejor rendimiento de red, todos los nodos deben configurarse con valores MTU similares en sus interfaces de Grid Network. La alerta *Red de cuadrícula MTU* se activa si hay una diferencia significativa en la configuración de MTU para la Red de cuadrícula en nodos individuales. No es necesario que los valores de MTU sean los mismos para todos los tipos de red.

* *ADMIN_NETWORK_CONFIG*: El método utilizado para adquirir direcciones IP, YA SEA DESACTIVADAS, ESTÁTICAS o DHCP. El valor predeterminado es DISABLED. Si todos o la mayoría de los nodos utilizan el mismo método para adquirir direcciones IP, puede especificar ese método aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_CONFIG = STATIC
----
* *ADMIN_NETWORK_TARGET*: El nombre de una red VMware existente que se utilizará para la red de administración. Esta configuración es necesaria a menos que la red de administración esté deshabilitada. Si todos los nodos utilizan el mismo nombre de red, o la mayoría de ellos, puede especificarlo aquí. A diferencia de la Red de Grid, no es necesario que todos los nodos estén conectados a la misma Red de Administración. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_TARGET = SG Admin Network
----
* *ADMIN_NETWORK_MASK*: La máscara DE red para la red de administración. Este ajuste es obligatorio si se utiliza una dirección IP estática. Si todos los nodos o la mayoría de ellos utilizan la misma máscara de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_MASK = 255.255.255.0
----
* *ADMIN_NETWORK_GATEWAY*: La puerta de enlace DE red para la red de administración. Esta configuración es necesaria si está utilizando direcciones IP estáticas y especifica subredes externas en la configuración ADMIN_NETWORK_ESL. (Es decir, no es necesario si ADMIN_NETWORK_ESL está vacío.) Si todos o la mayoría de los nodos utilizan la misma puerta de enlace de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_GATEWAY = 10.3.0.1
----
* *ADMIN_NETWORK_ESL*: La lista de subredes externas (rutas) para la Red Admin, especificada como una lista separada por comas de destinos de rutas CIDR. Si todos o la mayoría de los nodos utilizan la misma lista de subredes externas, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_ESL = 172.16.0.0/21,172.17.0.0/21
----
* *ADMIN_NETWORK_MTU*: OPCIONAL. La unidad de transmisión máxima (MTU) en la red de administración. No especifique si ADMIN_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se utiliza 1400. Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado. Si todos los nodos, o la mayoría, utilizan el mismo MTU para la red administrativa, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
ADMIN_NETWORK_MTU = 8192
----
* *CLIENT_NETWORK_CONFIG*: Método utilizado para adquirir direcciones IP, YA SEA DESACTIVADAS, ESTÁTICAS o DHCP. El valor predeterminado es DISABLED. Si todos o la mayoría de los nodos utilizan el mismo método para adquirir direcciones IP, puede especificar ese método aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_CONFIG = STATIC
----
* *CLIENT_NETWORK_TARGET*: El nombre de una red VMware existente que se utilizará para la red cliente. Esta configuración es necesaria a menos que la red de cliente esté deshabilitada. Si todos los nodos utilizan el mismo nombre de red, o la mayoría de ellos, puede especificarlo aquí. A diferencia de la Red de Grid, no es necesario que todos los nodos estén conectados a la misma Red de Cliente. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_TARGET = SG Client Network
----
* *CLIENT_NETWORK_MASK*: La máscara de red para la red cliente. Este ajuste es obligatorio si se utiliza una dirección IP estática. Si todos los nodos o la mayoría de ellos utilizan la misma máscara de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_MASK = 255.255.255.0
----
* *CLIENT_NETWORK_GATEWAY*: La puerta de enlace de red para la red cliente. Este ajuste es obligatorio si se utiliza una dirección IP estática. Si todos o la mayoría de los nodos utilizan la misma puerta de enlace de red, puede especificarla aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_GATEWAY = 10.4.0.1
----
* *MTU_CLIENTE*: OPCIONAL. La unidad de transmisión máxima (MTU) en la red de cliente. No especifique si CLIENT_NETWORK_CONFIG = DHCP. Si se especifica, el valor debe estar entre 1280 y 9216. Si se omite, se utiliza 1400. Si desea utilizar tramas gigantes, establezca el MTU en un valor adecuado para tramas gigantes, como 9000. De lo contrario, mantenga el valor predeterminado. Si todos o la mayoría de los nodos utilizan el mismo MTU para la red de cliente, puede especificarlo aquí. A continuación, puede anular la configuración global especificando diferentes opciones para uno o varios nodos individuales. Por ejemplo:
+
[listing]
----
CLIENT_NETWORK_MTU = 8192
----
* *PORT_REMAPP*: Reasigna cualquier puerto utilizado por un nodo para comunicaciones internas de nodo de red o comunicaciones externas. Es necesario volver a asignar puertos si las políticas de red de la empresa restringen uno o varios puertos utilizados por StorageGRID. Para obtener la lista de puertos utilizados por StorageGRID, consulte Comunicaciones internas de nodos de cuadrícula y comunicaciones externas en link:../network/index.html["Directrices sobre redes"].
+

NOTE: No vuelva a asignar los puertos que está planeando utilizar para configurar los puntos finales del equilibrador de carga.

+

NOTE: Si sólo SE establece PORT_REMAPP, la asignación que especifique se utilizará para las comunicaciones entrantes y salientes. Si TAMBIÉN se especifica PORT_REMAPP_INBOUND, PORT_REMAPP sólo se aplica a las comunicaciones salientes.

+
El formato utilizado es `_network type/protocol/default port used by grid node/new port_`: , Donde el tipo de red es grid, admin o client, y el protocolo es tcp o udp.

+
Por ejemplo:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443
----
+
Si se utiliza solo, este ejemplo establece una asignación simétrica de las comunicaciones entrantes y salientes del nodo de cuadrícula desde el puerto 18082 al puerto 443. Si se utiliza junto con PORT_REMAPP_INBOUND, este ejemplo asigna las comunicaciones salientes del puerto 18082 al puerto 443.

+
También puede volver a asignar varios puertos mediante una lista separada por comas.

+
Por ejemplo:

+
[listing]
----
PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80
----
* *PORT_REMAPP_INBOUND*: Reasigna las comunicaciones entrantes para el puerto especificado. Si especifica PORT_REMAP_INBOUND pero no especifica un valor para PORT_REMAP, las comunicaciones salientes para el puerto no cambian.
+

NOTE: No vuelva a asignar los puertos que está planeando utilizar para configurar los puntos finales del equilibrador de carga.

+
El formato utilizado es `_network type_/_protocol/_default port used by grid node_/_new port_`: , Donde el tipo de red es grid, admin o client, y el protocolo es tcp o udp.

+
Por ejemplo:

+
[listing]
----
PORT_REMAP_INBOUND = client/tcp/443/18082
----
+
En este ejemplo se toma el tráfico que se envía al puerto 443 para pasar un firewall interno y lo dirige al puerto 18082, donde el nodo de grid está escuchando las solicitudes de S3.

+
También puede volver a asignar varios puertos de entrada mediante una lista separada por comas.

+
Por ejemplo:

+
[listing]
----
PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22
----
* *TEMPORARY_PASSWORD_TYPE*: Tipo de contraseña de instalación temporal que se utilizará al acceder a la consola de VM o a la API de instalación de StorageGRID, o al usar SSH, antes de que el nodo se una a la cuadrícula.
+

TIP: Si todos o la mayoría de los nodos utilizan el mismo tipo de contraseña de instalación temporal, especifique el tipo en la sección de parámetros globales. A continuación, de manera opcional, utilice un valor diferente para un nodo individual. Por ejemplo, si selecciona *Usar contraseña personalizada* globalmente, puede usar *CUSTOM_TEMPORARY_PASSWORD=<password>* para establecer la contraseña para cada nodo.

+
*TEMPORARY_PASSWORD_TYPE* puede ser uno de los siguientes:

+
** *Usar nombre de nodo*: El nombre de nodo se utiliza como contraseña de instalación temporal y proporciona acceso a la consola de VM, la API de instalación de StorageGRID y SSH.
** *Deshabilitar contraseña*: No se utilizará ninguna contraseña de instalación temporal. Si necesita acceder a la VM para depurar problemas de instalación, consulte link:troubleshooting-installation-issues.html["Solucionar problemas de instalación"].
** *Usar contraseña personalizada*: El valor proporcionado con *CUSTOM_TEMPORARY_PASSWORD=<password>* se utiliza como contraseña de instalación temporal y proporciona acceso a la consola de VM, la API de instalación de StorageGRID y SSH.
+

TIP: Opcionalmente, puede omitir el parámetro *TEMPORARY_PASSWORD_TYPE* y especificar únicamente *CUSTOM_TEMPORARY_PASSWORD=<password>*.



* *CUSTOM_TEMPORARY_PASSWORD=<password>* Opcional. La contraseña temporal que se debe utilizar durante la instalación al acceder a la consola de VM, la API de instalación de StorageGRID y SSH. Se ignora si *TEMPORARY_PASSWORD_TYPE* está establecido en *Usar nombre de nodo* o *Desactivar contraseña*.




==== Parámetros específicos del nodo

Cada nodo se encuentra en su propia sección del archivo de configuración. Cada nodo requiere la siguiente configuración:

* El encabezado de sección define el nombre del nodo que se mostrará en el Gestor de cuadrícula. Puede anular este valor especificando el parámetro opcional NODE_NAME para el nodo.
* *NODE_TYPE*: VM_Admin_Node, VM_Storage_Node o VM_API_Gateway_Node
* *STORAGE_TYPE*: Combinado, datos o metadatos. Este parámetro opcional para los nodos de almacenamiento se combina de forma predeterminada (datos y metadatos) si no se especifica. Para obtener más información, consulte link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nodos de almacenamiento"].
* *GRID_NETWORK_IP*: La dirección IP del nodo en la red de cuadrícula.
* *ADMIN_NETWORK_IP*: La dirección IP del nodo en la red de administración. Solo es obligatorio si el nodo está conectado a la red Admin y ADMIN_NETWORK_CONFIG se establece en STATIC.
* *IP_RED_CLIENTE*: La dirección IP del nodo en la red cliente. Es obligatorio sólo si el nodo está conectado a la red cliente y CLIENT_NETWORK_CONFIG para este nodo se establece en ESTÁTICO.
* *ADMIN_IP*: La dirección IP del nodo Admin primario de la red Grid. Utilice el valor especificado como GRID_NETWORK_IP para el nodo de administración principal. Si omite este parámetro, el nodo intenta detectar la IP del nodo de administración principal mediante mDNS. Para obtener más información, consulte link:how-grid-nodes-discover-primary-admin-node.html["La forma en que los nodos de grid detectan el nodo de administrador principal"].
+

NOTE: El parámetro ADMIN_IP se omite para el nodo de administración principal.

* Todos los parámetros que no se establecieron globalmente. Por ejemplo, si un nodo está conectado a la red de administrador y no especificó parámetros DE RED_ADMIN en todo el mundo, debe especificarlos para el nodo.


.Nodo de administrador principal
Se necesitan las siguientes configuraciones adicionales para el nodo de administración principal:

* *NODE_TYPE*: VM_Admin_Node
* *ROL_ADMINISTRADOR*: Primario


Esta entrada de ejemplo es para un nodo de administrador principal que está en las tres redes:

[listing]
----
[DC1-ADM1]
  ADMIN_ROLE = Primary
  NODE_TYPE = VM_Admin_Node
  TEMPORARY_PASSWORD_TYPE = Use custom password
  CUSTOM_TEMPORARY_PASSWORD = Passw0rd

  GRID_NETWORK_IP = 10.1.0.2
  ADMIN_NETWORK_IP = 10.3.0.2
  CLIENT_NETWORK_IP = 10.4.0.2
----
La siguiente configuración adicional es opcional para el nodo de administración principal:

* *DISCO*: De forma predeterminada, a los nodos de administración se les asignan dos discos duros adicionales de 200 GB para la auditoría y el uso de bases de datos. Es posible aumentar esta configuración con el parámetro DISK. Por ejemplo:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Para los nodos de administrador, LAS INSTANCIAS siempre deben ser iguales 2.

.Nodo de almacenamiento
Se requiere la siguiente configuración adicional para los nodos de almacenamiento:

* *NODE_TYPE*: VM_Storage_Node
+
Esta entrada de ejemplo es para un nodo de almacenamiento que se encuentra en las redes Grid y Admin, pero no en la red cliente. Este nodo utiliza LA configuración ADMIN_IP para especificar la dirección IP del nodo de administración principal en la red de grid.

+
[listing]
----
[DC1-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.0.3
  ADMIN_NETWORK_IP = 10.3.0.3

  ADMIN_IP = 10.1.0.2
----
+
Esta segunda entrada de ejemplo es para un nodo de almacenamiento en una red cliente donde la política de red empresarial del cliente establece que una aplicación cliente S3 sólo puede acceder al nodo de almacenamiento mediante el puerto 80 o 443. El archivo de configuración de ejemplo utiliza PORT_REMAP para habilitar el nodo de almacenamiento para enviar y recibir mensajes S3 en el puerto 443.

+
[listing]
----
[DC2-S1]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3
  CLIENT_NETWORK_IP = 10.4.1.3
  PORT_REMAP = client/tcp/18082/443

  ADMIN_IP = 10.1.0.2
----
+
El último ejemplo crea una reasignación simétrica para el tráfico ssh del puerto 22 al puerto 3022, pero establece explícitamente los valores para el tráfico entrante y saliente.

+
[listing]
----
[DC1-S3]
  NODE_TYPE = VM_Storage_Node

  GRID_NETWORK_IP = 10.1.1.3

  PORT_REMAP = grid/tcp/22/3022
  PORT_REMAP_INBOUND = grid/tcp/3022/22

  ADMIN_IP = 10.1.0.2
----


Las siguientes configuraciones adicionales son opcionales para los nodos de almacenamiento:

* *DISCO*: De forma predeterminada, a los nodos de almacenamiento se les asignan tres discos de 4 TB para el uso de RangeDB. Esta configuración se puede aumentar con el parámetro DISK. Por ejemplo:
+
[listing]
----
DISK = INSTANCES=16, CAPACITY=4096
----
* *STORAGE_TYPE*: De forma predeterminada, todos los nuevos nodos de almacenamiento están configurados para almacenar tanto datos como metadatos de objetos, conocidos como _combined_ Storage Node. Puede cambiar el tipo de nodo de almacenamiento para almacenar solo datos o metadatos con el parámetro STORAGE_TYPE. Por ejemplo:
+
[listing]
----
STORAGE_TYPE = data
----


.Nodo de puerta de enlace
Para los nodos de puerta de enlace se requiere la siguiente configuración adicional:

* *NODE_TYPE*: VM_API_GATEWAY


Esta entrada de ejemplo es para un nodo de puerta de enlace de ejemplo en las tres redes. En este ejemplo, no se especificó ningún parámetro de red de cliente en la sección global del archivo de configuración, por lo que se deben especificar para el nodo:

[listing]
----
[DC1-G1]
  NODE_TYPE = VM_API_Gateway

  GRID_NETWORK_IP = 10.1.0.5
  ADMIN_NETWORK_IP = 10.3.0.5

  CLIENT_NETWORK_CONFIG = STATIC
  CLIENT_NETWORK_TARGET = SG Client Network
  CLIENT_NETWORK_MASK = 255.255.255.0
  CLIENT_NETWORK_GATEWAY = 10.4.0.1
  CLIENT_NETWORK_IP = 10.4.0.5

  ADMIN_IP = 10.1.0.2
----
.Nodo de administrador no primario
Se requieren los siguientes ajustes adicionales para los nodos del administrador que no son primarios:

* *NODE_TYPE*: VM_Admin_Node
* *ROL_ADMIN*: No primario


Esta entrada de ejemplo es para un nodo de administración no primario que no está en la red de cliente:

[listing]
----
[DC2-ADM1]
  ADMIN_ROLE = Non-Primary
  NODE_TYPE = VM_Admin_Node

  GRID_NETWORK_TARGET = SG Grid Network
  GRID_NETWORK_IP = 10.1.0.6
  ADMIN_NETWORK_IP = 10.3.0.6

  ADMIN_IP = 10.1.0.2
----
La siguiente configuración adicional es opcional para los nodos de administrador que no son primarios:

* *DISCO*: De forma predeterminada, a los nodos de administración se les asignan dos discos duros adicionales de 200 GB para la auditoría y el uso de bases de datos. Es posible aumentar esta configuración con el parámetro DISK. Por ejemplo:
+
[listing]
----
DISK = INSTANCES=2, CAPACITY=300
----



NOTE: Para los nodos de administrador, LAS INSTANCIAS siempre deben ser iguales 2.



== Ejecute el script Bash

Puede utilizar `deploy-vsphere-ovftool.sh` el script bash y el archivo de configuración de deploy-vsphere-ovftool.ini que modificó para automatizar la implementación de los nodos de StorageGRID en VMware vSphere.

.Antes de empezar
Ha creado un archivo de configuración deploy-vsphere-ovftool.ini para el entorno.

Puede utilizar la ayuda disponible con el script Bash introduciendo los comandos de ayuda (`-h/--help`). Por ejemplo:

[listing]
----
./deploy-vsphere-ovftool.sh -h
----
o.

[listing]
----
./deploy-vsphere-ovftool.sh --help
----
.Pasos
. Inicie sesión en el equipo Linux que está utilizando para ejecutar el script Bash.
. Cambie al directorio en el que ha extraído el archivo de instalación.
+
Por ejemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/vsphere
----
. Para desplegar todos los nodos de cuadrícula, ejecute la secuencia de comandos Bash con las opciones adecuadas para su entorno.
+
Por ejemplo:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd ./deploy-vsphere-ovftool.ini
----
. Si un nodo de cuadrícula no se pudo implementar debido a un error, resuelva el error y vuelva a ejecutar el script Bash sólo para ese nodo.
+
Por ejemplo:

+
[listing]
----
./deploy-vsphere-ovftool.sh --username=user --password=pwd --single-node="DC1-S3" ./deploy-vsphere-ovftool.ini
----


La implementación se completa cuando se pasa el estado de cada nodo.

[listing]
----
Deployment Summary
+-----------------------------+----------+----------------------+
| node                        | attempts | status               |
+-----------------------------+----------+----------------------+
| DC1-ADM1                    |        1 | Passed               |
| DC1-G1                      |        1 | Passed               |
| DC1-S1                      |        1 | Passed               |
| DC1-S2                      |        1 | Passed               |
| DC1-S3                      |        1 | Passed               |
+-----------------------------+----------+----------------------+
----


== Automatice la configuración de StorageGRID

Después de implementar los nodos de grid, puede automatizar la configuración del sistema StorageGRID.

.Antes de empezar
* Conoce la ubicación de los siguientes archivos del archivo de instalación.
+
[cols="1a,1a"]
|===
| Nombre de archivo | Descripción 


| configure-storagegrid.py  a| 
Script Python utilizado para automatizar la configuración



| configure-storagegrid.sample.json  a| 
Archivo de configuración de ejemplo para utilizar con el script



| configure-storagegrid.blank.json  a| 
Archivo de configuración en blanco para utilizar con el script

|===
* Ha creado un `configure-storagegrid.json` archivo de configuración. Para crear este archivo, puede modificar el archivo de configuración de ejemplo (`configure-storagegrid.sample.json`) o el archivo de configuración en blanco (`configure-storagegrid.blank.json`).



CAUTION: Almacene la contraseña de administración y la frase de acceso de aprovisionamiento de la sección Contraseñas del archivo de configuración modificado `configure-storagegrid.json` en una ubicación segura. Estas contraseñas son necesarias para los procedimientos de instalación, expansión y mantenimiento. También debe realizar una copia de seguridad del archivo de configuración modificado `configure-storagegrid.json` y almacenarlo en una ubicación segura.

.Acerca de esta tarea
Puede utilizar `configure-storagegrid.py` el script de Python y `configure-storagegrid.json` el archivo de configuración de grid para automatizar la configuración de su sistema StorageGRID.

+ NOTA: También puede configurar el sistema usando el Grid Manager o la API de instalación.

.Pasos
. Inicie sesión en el equipo Linux que está utilizando para ejecutar el script Python.
. Cambie al directorio en el que ha extraído el archivo de instalación.
+
Por ejemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
 `platform`donde está debs, rpms o vsphere.

. Ejecute el script Python y utilice el archivo de configuración que ha creado.
+
Por ejemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Resultado
Durante el proceso de configuración, se genera un archivo de paquete de recuperación `.zip` y se descarga en el directorio en el que está ejecutando el proceso de instalación y configuración. Debe realizar una copia de seguridad del archivo del paquete de recuperación para poder recuperar el sistema StorageGRID en caso de que falle uno o más nodos de grid. Por ejemplo, cópielo en una ubicación de red segura y en una ubicación de almacenamiento en nube segura.


CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID.

Si especificó que se deben generar contraseñas aleatorias, abra `Passwords.txt` el archivo y busque las contraseñas necesarias para acceder al sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
El sistema StorageGRID se instala y configura cuando se muestra un mensaje de confirmación.

[listing]
----
StorageGRID has been configured and installed.
----
.Información relacionada
* link:navigating-to-grid-manager.html["Desplácese hasta Grid Manager"]
* link:overview-of-installation-rest-api.html["Instalación de la API de REST"]

