---
permalink: rhel/automating-installation.html 
sidebar: sidebar 
keywords: how to automate red hat linux installation 
summary: Puede automatizar la instalación del servicio de host de StorageGRID y la configuración de los nodos de grid. 
---
= Automatice la instalación de StorageGRID en Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede automatizar la instalación del servicio de host de StorageGRID y la configuración de los nodos de grid.

La automatización de la puesta en marcha puede ser útil en cualquiera de los siguientes casos:

* Ya utiliza un marco de orquestación estándar, como Ansible, Puppet o Chef, para poner en marcha y configurar hosts físicos o virtuales.
* Tiene pensado implementar varias instancias de StorageGRID.
* Está poniendo en marcha una instancia de StorageGRID grande y compleja.


El servicio de host StorageGRID se instala mediante un paquete y está basado en archivos de configuración. Puede crear los archivos de configuración mediante uno de estos métodos:

* link:creating-node-configuration-files.html["Cree los archivos de configuración"] interactivamente durante una instalación manual.
* Prepare los archivos de configuración por adelantado (o mediante programación) para permitir la instalación automatizada mediante marcos de orquestación estándar, como se describe en este artículo.
+
StorageGRID proporciona scripts Python opcionales para automatizar la configuración de dispositivos StorageGRID y todo el sistema StorageGRID (el «grid»). Puede utilizar estos scripts directamente o puede inspeccionarlos para aprender a utilizar link:overview-of-installation-rest-api.html["Instalación de StorageGRID API DE REST"]las herramientas de implementación y configuración de grid que usted mismo desarrolle.





== Automatizar la instalación y configuración del servicio de host de StorageGRID

Puede automatizar la instalación del servicio de host de StorageGRID mediante marcos de orquestación estándar como Ansible, Puppet, Chef, Fabric o SaltStack.

El servicio de host de StorageGRID está empaquetado en un RPM y está basado en archivos de configuración que puede prepararse con anticipación (o mediante programación) para permitir la instalación automatizada. Si ya utiliza un marco de orquestación estándar para instalar y configurar RHEL, añadir StorageGRID a sus libros de estrategia o recetas debería ser sencillo.

Consulte el rol de Ansible y el libro de estrategia del ejemplo en `/extras` la carpeta proporcionada con el archivo de instalación. el libro de estrategia de Ansible muestra cómo `storagegrid` el rol prepara el host e instala StorageGRID en los servidores de destino. Puede personalizar el rol o el libro de estrategia según sea necesario.


NOTE: el libro de aplicaciones de ejemplo no incluye los pasos necesarios para crear dispositivos de red antes de iniciar el servicio de host StorageGRID. Añada estos pasos antes de finalizar y utilizar el libro de estrategia.

Es posible automatizar todos los pasos para preparar los hosts y implementar nodos de grid virtual.



=== Ejemplo de rol y libro de estrategia de Ansible

el rol de Ansible y el libro de estrategia de ejemplo se proporcionan con el archivo de instalación en la `/extras` carpeta. el libro de estrategia de Ansible muestra cómo `storagegrid` el rol prepara los hosts e instala StorageGRID en los servidores de destino. Puede personalizar el rol o el libro de estrategia según sea necesario.

Las tareas de instalación del ejemplo de rol proporcionado `storagegrid` utilizan el `ansible.builtin.dnf` módulo para realizar la instalación desde los archivos RPM locales o desde un repositorio Yum remoto. Si el módulo no está disponible o no es compatible, es posible que tenga que editar las tareas de Ansible adecuadas en los siguientes archivos para utilizar el `yum` módulo o `ansible.builtin.yum`:

* `roles/storagegrid/tasks/rhel_install_from_repo.yml`
* `roles/storagegrid/tasks/rhel_install_from_local.yml`




== Automatice la configuración de StorageGRID

Después de implementar los nodos de grid, puede automatizar la configuración del sistema StorageGRID.

.Antes de empezar
* Conoce la ubicación de los siguientes archivos del archivo de instalación.
+
[cols="1a,1a"]
|===
| Nombre de archivo | Descripción 


| configure-storagegrid.py  a| 
Script Python utilizado para automatizar la configuración



| configure-storagegrid.sample.json  a| 
Archivo de configuración de ejemplo para utilizar con el script



| configure-storagegrid.blank.json  a| 
Archivo de configuración en blanco para utilizar con el script

|===
* Ha creado un `configure-storagegrid.json` archivo de configuración. Para crear este archivo, puede modificar el archivo de configuración de ejemplo (`configure-storagegrid.sample.json`) o el archivo de configuración en blanco (`configure-storagegrid.blank.json`).



CAUTION: Almacene la contraseña de administración y la frase de acceso de aprovisionamiento de la sección Contraseñas del archivo de configuración modificado `configure-storagegrid.json` en una ubicación segura. Estas contraseñas son necesarias para los procedimientos de instalación, expansión y mantenimiento. También debe realizar una copia de seguridad del archivo de configuración modificado `configure-storagegrid.json` y almacenarlo en una ubicación segura.

.Acerca de esta tarea
Puede utilizar `configure-storagegrid.py` el script de Python y `configure-storagegrid.json` el archivo de configuración para automatizar la configuración de su sistema StorageGRID.


NOTE: También puede configurar el sistema mediante Grid Manager o la API de instalación.

.Pasos
. Inicie sesión en el equipo Linux que está utilizando para ejecutar el script Python.
. Cambie al directorio en el que ha extraído el archivo de instalación.
+
Por ejemplo:

+
[listing]
----
cd StorageGRID-Webscale-version/platform
----
+
donde `platform` está `debs` `rpms` , o `vsphere`.

. Ejecute el script Python y utilice el archivo de configuración que ha creado.
+
Por ejemplo:

+
[listing]
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----


.Resultado
Durante el proceso de configuración, se genera un archivo de paquete de recuperación `.zip` y se descarga en el directorio en el que está ejecutando el proceso de instalación y configuración. Debe realizar una copia de seguridad del archivo del paquete de recuperación para poder recuperar el sistema StorageGRID en caso de que falle uno o más nodos de grid. Por ejemplo, cópielo en una ubicación de red segura y en una ubicación de almacenamiento en nube segura.


CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID.

Si especificó que se generarán contraseñas aleatorias, abra `Passwords.txt` el archivo y busque las contraseñas necesarias para acceder al sistema StorageGRID.

[listing]
----
######################################################################
##### The StorageGRID "Recovery Package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----
El sistema StorageGRID se instala y configura cuando se muestra un mensaje de confirmación.

[listing]
----
StorageGRID has been configured and installed.
----
.Información relacionada
link:overview-of-installation-rest-api.html["Instalación de la API de REST"]
