---
permalink: rhel/installing-linux.html 
sidebar: sidebar 
keywords: how to install on red hat linux 
summary: Debe instalar StorageGRID en todos los hosts Grid de Red Hat Enterprise Linux. Para ver una lista de las versiones admitidas, use la herramienta de matriz de interoperabilidad de NetApp. 
---
= Instale Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe instalar StorageGRID en todos los hosts Grid de Red Hat Enterprise Linux. Para ver una lista de las versiones admitidas, use la herramienta de matriz de interoperabilidad de NetApp.

.Antes de empezar
Asegúrese de que su sistema operativo cumple con los requisitos mínimos de versión de núcleo de StorageGRID, como se indica a continuación. Utilice el comando `uname -r` para obtener la versión de kernel de su sistema operativo o póngase en contacto con su proveedor del sistema operativo.

[cols="1a,2a,2a"]
|===
| Versión de Red Hat Enterprise Linux | Versión mínima del núcleo | Nombre del paquete del núcleo 


 a| 
8,8 (obsoleto)
 a| 
4.18.0-477.10.1.el8_8.x86_64
 a| 
kernel-4.18.0-477.10.1.el8_8.x86_64



 a| 
8,10
 a| 
4.18.0-553.el8_10.x86_64
 a| 
kernel-4.18.0-553.el8_10.x86_64



 a| 
9,0 (obsoleto)
 a| 
5.14.0-70.22.1.el9_0.x86_64
 a| 
kernel-5.14.0-70.22.1.el9_0.x86_64



 a| 
9,2 (obsoleto)
 a| 
5.14.0-284.11.1.el9_2.x86_64
 a| 
kernel-5.14.0-284.11.1.el9_2.x86_64



 a| 
9,4
 a| 
5.14.0-427.18.1.el9_4.x86_64
 a| 
kernel-5.14.0-427.18.1.el9_4.x86_64

|===
.Pasos
. Instalar Linux en todos los hosts de grid físicos o virtuales de acuerdo con las instrucciones del mayorista o del procedimiento estándar.
+

NOTE: Si utiliza el instalador estándar de Linux, seleccione la configuración de software para «nodo de computación», si está disponible o el entorno de base «instalación mínima». No instale ningún entorno de escritorio gráfico.

. Asegúrese de que todos los hosts tengan acceso a repositorios de paquetes, incluido el canal Extras.
+
Es posible que necesite estos paquetes adicionales más adelante en este procedimiento de instalación.

. Si el intercambio está activado:
+
.. Ejecute el siguiente comando: `$ sudo swapoff --all`
.. Elimine todas las entradas de intercambio de `/etc/fstab` para mantener la configuración.


+

NOTE: Si no se deshabilita por completo el intercambio, el rendimiento se puede reducir considerablemente.


