---
permalink: rhel/software-requirements.html 
sidebar: sidebar 
keywords: software requirements 
summary: Es posible usar una máquina virtual para alojar cualquier tipo de nodo StorageGRID. Se necesita una máquina virtual para cada nodo de grid. 
---
= Requisitos de software para Red Hat Enterprise Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible usar una máquina virtual para alojar cualquier tipo de nodo StorageGRID. Se necesita una máquina virtual para cada nodo de grid.

Para instalar StorageGRID en Red Hat Enterprise Linux (RHEL), debe instalar algunos paquetes de software de terceros. Algunas distribuciones de Linux soportadas no contienen estos paquetes por defecto. Las versiones del paquete de software en las que se han probado las instalaciones de StorageGRID incluyen las que se indican en esta página.

Si selecciona una opción de instalación en tiempo de ejecución de contenedor y distribución de Linux que requiera alguno de estos paquetes y la distribución de Linux no los instala automáticamente, instale una de las versiones que se enumeran aquí, si está disponible en su proveedor o en el proveedor de soporte para su distribución de Linux. De lo contrario, utilice las versiones de paquete predeterminadas disponibles en su proveedor.

Todas las opciones de instalación requieren Podman o Docker. No instale ambos paquetes. Instale solo el paquete requerido por su opción de instalación.


NOTE: La compatibilidad con Docker como motor de contenedor para puestas en marcha de solo software queda obsoleta. En una futura versión, Docker se sustituirá por otro motor de contenedor.



== Versiones de Python probadas

* 3.5.2-2
* 3.6.8-2
* 3.6.8-38
* 3.6.9-1
* 3.7.3-1
* 3,8.10-0
* 3.9.2-1
* 3.9.10-2
* 3.9.16-1
* 3.10.6-1
* 3.11.2-6




== Versiones de Podman probadas

* 3,2.3-0
* 3,4.4+ds1
* 4.1.1-7
* 4.2.0-11
* 4,3.1+ds1-8+b1
* 4.4.1-8
* 4.4.1-12




== Versiones de Docker probadas


IMPORTANT: La compatibilidad de Docker está obsoleta y se eliminará en un lanzamiento futuro.

* Docker-CE 20.10.7
* Docker-CE 20.10.20-3
* Docker-CE 23,0.6-1
* Docker-CE 24,0.2-1
* Docker-CE 24,0.4-1
* Docker-CE 24,0.5-1
* Docker-CE 24,0.7-1
* 1,5-2

