---
permalink: admin/changing-your-password.html 
sidebar: sidebar 
keywords: change password, grid manager password 
summary: Si es un usuario local de Grid Manager, puede cambiar su propia contraseña. 
---
= Cambie la contraseña
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si es un usuario local de Grid Manager, puede cambiar su propia contraseña.

.Antes de empezar
Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].

.Acerca de esta tarea
Si inicia sesión en StorageGRID como usuario federado o si está habilitado el inicio de sesión único (SSO), no podrá cambiar la contraseña en Grid Manager. En su lugar, debe cambiar la contraseña en el origen de identidad externo, por ejemplo, Active Directory u OpenLDAP.

.Pasos
. En el encabezado de Grid Manager, seleccione *_su nombre_* > *Cambiar contraseña*.
. Introduzca su contraseña actual.
. Escriba una nueva contraseña.
+
La contraseña debe contener al menos 8 caracteres y no más de 32. Las contraseñas distinguen mayúsculas de minúsculas.

. Vuelva a introducir la nueva contraseña.
. Seleccione *Guardar*.

