---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: Al cambiar las contraseñas de acceso SSH para los nodos de administración, también se actualizan los conjuntos únicos de claves SSH internas de cada nodo del grid. El nodo de administración principal utiliza estas claves SSH para acceder a los nodos utilizando una autenticación segura y sin contraseña. 
---
= Cambiar las contraseñas de acceso SSH para los nodos de administración
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al cambiar las contraseñas de acceso SSH para los nodos de administración, también se actualizan los conjuntos únicos de claves SSH internas de cada nodo del grid. El nodo de administración principal utiliza estas claves SSH para acceder a los nodos utilizando una autenticación segura y sin contraseña.

Utilice una clave SSH para iniciar sesión en un nodo `admin` como o para el usuario raíz en una máquina virtual o una conexión de consola física.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"].
* Tiene la clave de acceso de aprovisionamiento actual.


.Acerca de esta tarea
Las nuevas contraseñas de acceso para los nodos de administración y las nuevas claves internas para cada nodo se almacenan en el `Passwords.txt` archivo en el paquete de recuperación.  Las claves se enumeran en la columna Contraseña de ese archivo.

Hay contraseñas de acceso SSH separadas para las claves SSH que se usan para la comunicación entre nodos. Estos no se modifican con este procedimiento.



== Acceda al asistente

.Pasos
. Seleccione *Configuración* > *Control de acceso* > *Contraseñas de red*.
. En *Cambiar claves SSH*, selecciona *Hacer un cambio*.




== [[download-current]]Descargue el paquete de recuperación actual

Antes de cambiar las claves de acceso SSH, descargue el paquete de recuperación actual.  Puede utilizar las claves de este archivo si el proceso de cambio de clave falla para algún nodo.

.Pasos
. Introduzca la clave de acceso de aprovisionamiento para el grid.
. Seleccione *Descargar paquete de recuperación*.
. Copiar el archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .

. Seleccione *continuar*.
. Cuando aparezca el cuadro de diálogo de confirmación, seleccione *Sí* si está listo para comenzar a cambiar las claves de acceso SSH.
+

CAUTION: No puede cancelar este proceso una vez que se inicia.





== Cambiar las claves de acceso SSH

Cuando se inicia el proceso de cambio de claves de acceso SSH, se genera un nuevo paquete de recuperación que incluye las nuevas claves.  Luego, las claves se actualizan en cada nodo.

.Pasos
. Espere a que se genere el nuevo paquete de recuperación, lo que puede tardar unos minutos.
. Cuando el botón Descargar nuevo paquete de recuperación esté habilitado, seleccione *Descargar nuevo paquete de recuperación* y guarde el archivo del nuevo paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
. Cuando finalice la descarga:
+
.. Abra el `.zip` archivo.
.. Confirme que puede acceder al contenido, incluido `Passwords.txt` el archivo, que contiene las nuevas claves de acceso SSH.
.. Copiar el nuevo archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: No sobrescriba el paquete de recuperación antiguo.

+
El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .



. Espere a que las claves se actualicen en cada nodo, lo que puede tardar unos minutos.
+
Si se cambian las claves para todos los nodos, aparece un banner verde correcto.

+
Si se produce un error durante el proceso de actualización, un mensaje de banner muestra el número de nodos que no pudieron cambiar sus claves. El sistema volverá a intentar automáticamente el proceso en cualquier nodo que no haya cambiado su clave. Si el proceso termina con algunos nodos que aún no tienen una clave cambiada, aparece el botón *Reintentar*.

+
Si la actualización de clave falló para uno o más nodos:

+
.. Revise los mensajes de error que aparecen en la tabla.
.. Resuelva los problemas.
.. Seleccione *Reintentar*.
+
El reintento sólo cambia las claves de acceso SSH en los nodos que han fallado durante los intentos de cambio de clave anteriores.



. Después de cambiar las claves de acceso SSH para todos los nodos, elimine el archivo<<download-current,primer paquete de recuperación que descargaste>> .
. Opcionalmente, seleccione *Mantenimiento* > *Sistema* > *Paquete de recuperación* para descargar una copia adicional del nuevo paquete de recuperación.

