---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: Cada nodo de su red tiene una contraseña de consola de nodo, que usted utiliza para iniciar sesión en el nodo.  De forma predeterminada, cada nodo tiene una contraseña única.  Puede cambiar cada contraseña por una nueva contraseña única o puede cambiar la contraseña de cada nodo para utilizar una contraseña global.  Las contraseñas se almacenan en el paquete de recuperación. 
---
= Cambie las contraseñas de la consola de los nodos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cada nodo de su red tiene una contraseña de consola de nodo, que usted utiliza para iniciar sesión en el nodo.  De forma predeterminada, cada nodo tiene una contraseña única.  Puede cambiar cada contraseña por una nueva contraseña única o puede cambiar la contraseña de cada nodo para utilizar una contraseña global.  Las contraseñas se almacenan en el paquete de recuperación.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"].
* Tiene la clave de acceso de aprovisionamiento actual.


.Acerca de esta tarea
Utilice una contraseña de consola de nodo para iniciar sesión en un nodo como "admin" mediante SSH, o como usuario root en una conexión de consola física/VM.  Puede cambiar las contraseñas de la consola del nodo utilizando una de estas opciones:

* Aplicar automáticamente contraseñas aleatorias a cada nodo
* Especifique y aplique una contraseña global a todos los nodos
* Especificar y aplicar una contraseña única a uno o más nodos


Las contraseñas se almacenan de forma actualizada. `Passwords.txt` archivo en el paquete de recuperación.  Las contraseñas se enumeran en la columna Contraseña del archivo.


NOTE: Ellink:../admin/change-ssh-access-passwords.html["Contraseñas de acceso SSH"] Las claves SSH utilizadas para la comunicación entre nodos son independientes de las contraseñas de la consola del nodo.  Este procedimiento no cambia las contraseñas de acceso SSH.



== Acceda al asistente

.Pasos
. Seleccione *Configuración* > *Control de acceso* > *Contraseñas de red*.
. En *Cambiar contraseñas de consola de nodo*, selecciona *Hacer un cambio*.




== [[download-current]]Descargue el paquete de recuperación actual

Antes de cambiar las contraseñas de la consola del nodo, descargue el paquete de recuperación actual.  Puede utilizar las contraseñas de este archivo si el proceso de cambio de contraseña falla para algún nodo.

.Pasos
. Introduzca la clave de acceso de aprovisionamiento para el grid.
. Seleccione *Descargar paquete de recuperación*.
. Copiar el archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: El archivo del paquete de recuperación debe estar protegido porque contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .

. Seleccione *continuar*.




== Proporcionar nuevas contraseñas

. Seleccione el método de cambio de contraseña que desea utilizar.
+
** *Automático*: StorageGRID asigna automáticamente una nueva contraseña de consola aleatoria a todos los nodos.
** *Personalizado*: proporcionas contraseñas de consola.




[role="tabbed-block"]
====
.Automático
--
. Seleccione *continuar*.


--
.Personalizado
--
. Seleccione una de las siguientes opciones:
+
** *Contraseña de consola global*: aplica la misma contraseña de consola a todos los nodos.
** *Contraseñas de consola únicas*: aplique una contraseña diferente en uno o más nodos.


. Si seleccionó *Contraseña de consola global*, ingrese la contraseña que desea usar para todos los nodos.
. Si seleccionó *Contraseñas de consola únicas*, ingrese una contraseña única para uno o más nodos.
. Seleccione *continuar*.


--
====


== Completar el cambio de contraseña

. Cuando aparezca el cuadro de diálogo de confirmación, seleccione *Sí* si está listo para que StorageGRID comience a cambiar las contraseñas de la consola del nodo.
+

NOTE: No puede cancelar este proceso una vez que se inicia.

+
StorageGRID genera un nuevo paquete de recuperación que contiene la nueva contraseña.

. Cuando el nuevo paquete de recuperación esté listo, seleccione *Descargar nuevo paquete de recuperación* y guarde el paquete de recuperación.
. Abra el `.zip` archivo.
. Confirme que puede acceder al contenido, incluido `Passwords.txt` el archivo, que contiene las nuevas contraseñas de la consola del nodo.
. Copiar el nuevo archivo del paquete de recuperación(`.zip` ) a dos lugares seguros, protegidos y separados.
+

CAUTION: No sobrescriba el paquete de recuperación antiguo.

+
Debe proteger el archivo de recuperación, ya que contiene claves de cifrado y contraseñas que se pueden utilizar para obtener datos del sistema StorageGRID .

. Seleccione la casilla de verificación para indicar que ha descargado el nuevo paquete de recuperación y verificado el contenido.
. Seleccione *continuar*.
+
StorageGRID actualiza la contraseña de cada nodo.

+
Si hay un error durante el proceso de actualización, la barra de progreso enumera la cantidad de nodos cuyas contraseñas no se pudieron cambiar.  El sistema volverá a intentar automáticamente el proceso en cualquier nodo cuya contraseña no se haya podido cambiar.  Si el proceso finaliza con algunos nodos que aún no tienen la contraseña cambiada, aparece el botón *Reintentar*.

. Si la actualización de la contraseña falló para uno o más nodos:
+
.. Revise los mensajes de error que aparecen en la tabla.
.. Resuelva los problemas.
.. Seleccione *Reintentar*.
+

NOTE: Al volver a intentar solo se cambian las contraseñas de la consola de nodos en los nodos que fallaron durante los intentos anteriores de cambio de contraseña.



. Cuando la barra de progreso indique que no quedan actualizaciones, seleccione *Finalizar*.
. Después de cambiar las contraseñas de la consola de nodo para todos los nodos, elimine el archivo<<download-current,primer paquete de recuperación que descargaste>> .

