---
permalink: admin/configuring-client-connections.html 
sidebar: sidebar 
keywords: s3 connection, connect to storagegrid, s3 setup wizard 
summary: Como administrador de grid, usted administra las opciones de configuración que controlan cómo las aplicaciones cliente S3 se conectan al sistema StorageGRID para almacenar y recuperar datos. 
---
= Configure las conexiones de cliente S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Como administrador de grid, usted administra las opciones de configuración que controlan cómo las aplicaciones cliente S3 se conectan al sistema StorageGRID para almacenar y recuperar datos.


TIP: Se han eliminado los detalles de Swift de esta versión del sitio del documento. Consulte https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-client-connections.html["StorageGRID 11,8: Configure las conexiones de clientes S3 y Swift"^].



== Tareas de configuración

. Realice tareas de requisitos previos en StorageGRID, según cómo se conectará la aplicación cliente a StorageGRID.


[role="tabbed-block"]
====
.Tareas requeridas
--
Debe obtener:

* Direcciones IP
* Nombres de dominio
* Certificado SSL


--
.Tareas opcionales
--
Opcionalmente, configure:

* federación de identidades
* SSO


--
====
. Utilice StorageGRID para obtener los valores que la aplicación necesita para conectarse a la cuadrícula. Puede utilizar el asistente de configuración de S3 o configurar cada entidad de StorageGRID manualmente. +


[role="tabbed-block"]
====
.Utilice el asistente de configuración de S3
--
Siga los pasos del asistente de configuración de S3.

--
.Configura manualmente
--
. Cree un grupo de alta disponibilidad
. Crear punto final de equilibrador de carga
. Cree una cuenta de inquilino
. Crear bloque y claves de acceso
. Configurar la regla y la política de ILM


--
====
. Utilice la aplicación S3 para completar la conexión a StorageGRID. Cree entradas DNS para asociar direcciones IP a cualquier nombre de dominio que desee utilizar.
+
Si es necesario, realice una configuración de aplicación adicional.

. Realice tareas continuas en la aplicación y en StorageGRID para gestionar y supervisar el almacenamiento de objetos a lo largo del tiempo.




== Información necesaria para asociar StorageGRID a una aplicación cliente

Para poder asociar StorageGRID a una aplicación cliente S3, debe realizar pasos de configuración en StorageGRID y obtener cierto valor.



=== ¿Qué valores necesito?

La siguiente tabla muestra los valores que debe configurar en StorageGRID y dónde los utilizan la aplicación S3 y el servidor DNS.

[cols="1a,1a,1a"]
|===
| Valor | Donde se configura el valor | Donde se utiliza el valor 


 a| 
Direcciones IP virtuales (VIP)
 a| 
StorageGRID > Grupo de alta disponibilidad
 a| 
Entrada DNS



 a| 
Puerto
 a| 
StorageGRID > Punto final del equilibrador de carga
 a| 
Aplicación cliente



 a| 
Certificado SSL
 a| 
StorageGRID > Punto final del equilibrador de carga
 a| 
Aplicación cliente



 a| 
Nombre del servidor (FQDN)
 a| 
StorageGRID > Punto final del equilibrador de carga
 a| 
* Aplicación cliente
* Entrada DNS




 a| 
S3 ID de clave de acceso y clave de acceso secreta
 a| 
StorageGRID > inquilino y bloque
 a| 
Aplicación cliente



 a| 
Nombre de cubo/contenedor
 a| 
StorageGRID > inquilino y bloque
 a| 
Aplicación cliente

|===


=== ¿Cómo obtengo estos valores?

Dependiendo de sus requisitos, puede hacer cualquiera de los siguientes pasos para obtener la información que necesita:

* *Utilice el link:use-s3-setup-wizard.html["S3 Asistente de configuración"]*. El asistente de configuración de S3 le ayuda a configurar rápidamente los valores necesarios en StorageGRID y genera uno o dos archivos que puede utilizar al configurar la aplicación S3. El asistente le guiará por los pasos necesarios y le ayudará a garantizar que la configuración cumple las prácticas recomendadas de StorageGRID.
+

NOTE: Si está configurando una aplicación S3, se recomienda utilizar el asistente de configuración de S3 a menos que sepa que tiene requisitos especiales o que su implementación requerirá una personalización significativa.

* *Utilice el link:../fabricpool/use-fabricpool-setup-wizard.html["Asistente de configuración de FabricPool"]*. De forma similar al asistente de configuración de S3, el asistente de configuración de FabricPool ayuda a configurar rápidamente los valores necesarios y genera un archivo que se puede usar al configurar un nivel de cloud de FabricPool en ONTAP.
+

NOTE: Si va a utilizar StorageGRID como sistema de almacenamiento de objetos para un nivel cloud de FabricPool, se recomienda utilizar el asistente de configuración de FabricPool, a menos que sepa que tiene requisitos especiales o que su implementación requerirá una gran personalización.

* *Configurar artículos manualmente*. Si se conecta a una aplicación S3 y prefiere no utilizar el asistente de configuración de S3, puede obtener los valores necesarios realizando la configuración manualmente. Siga estos pasos:
+
.. Configure el grupo de alta disponibilidad (HA) que desee utilizar para la aplicación S3. Consulte link:configure-high-availability-group.html["Configuración de grupos de alta disponibilidad"].
.. Cree el punto final de equilibrio de carga que utilizará la aplicación S3. Consulte link:configuring-load-balancer-endpoints.html["Configurar puntos finales del equilibrador de carga"].
.. Cree la cuenta de inquilino que utilizará la aplicación S3. Consulte link:creating-tenant-account.html["Cree una cuenta de inquilino"].
.. Para un inquilino de S3, inicie sesión en la cuenta de inquilino y genere un ID de clave de acceso y una clave de acceso secreta para cada usuario que acceda a la aplicación. Consulte link:../tenant/creating-your-own-s3-access-keys.html["Cree sus propias claves de acceso"].
.. Cree uno o varios bloques de S3 dentro de la cuenta de inquilino. Para S3, consulte link:../tenant/creating-s3-bucket.html["Crear bloque de S3"].
.. Para agregar instrucciones de ubicación específicas para los objetos que pertenecen al inquilino o bloque/contenedor nuevo, cree una regla de ILM nueva y active una nueva política de ILM para utilizar esa regla. Consulte link:../ilm/access-create-ilm-rule-wizard.html["Cree la regla de ILM"] y link:../ilm/creating-ilm-policy.html["Cree una política de ILM"].



