---
permalink: admin/configure-sso.html 
sidebar: sidebar 
keywords: use sandbox mode for sso, how to test single sign-on 
summary: 'Puede seguir el asistente de configuración de SSO e ingresar al modo sandbox para configurar y probar el inicio de sesión único \(SSO\) antes de habilitarlo para todos los usuarios de StorageGRID. Una vez habilitado SSO, puede volver al modo sandbox cuando sea necesario para cambiar o volver a probar la configuración.' 
---
= Configurar SSO
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede seguir el asistente de configuración de SSO e introducir el modo sandbox para configurar y probar el inicio de sesión único (SSO) antes de habilitarlo para todos los usuarios de StorageGRID. Una vez habilitado SSO, puede volver al modo sandbox cuando sea necesario para cambiar o volver a probar la configuración.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:admin-group-permissions.html["Permiso de acceso raíz"].
* Configuró la federación de identidades para el sistema StorageGRID.
* Para el tipo de servicio *LDAP de federación de identidades*, ha seleccionado Active Directory o Entra ID, en función del proveedor de identidad SSO que desea utilizar.
+
[cols="1a,1a"]
|===
| Se ha configurado el tipo de servicio LDAP | Opciones para el proveedor de identidades SSO 


 a| 
Servicio de Federación de Active Directory (AD FS)
 a| 
** Active Directory
** ID Entra
** PingFederate




 a| 
ID Entra
 a| 
ID Entra

|===


.Acerca de esta tarea
Cuando se habilita el inicio de sesión único y un usuario intenta iniciar sesión en un nodo de administración, StorageGRID envía una solicitud de autenticación al proveedor de identidades de SSO. A su vez, el proveedor de identidades SSO envía una respuesta de autenticación a StorageGRID para indicar si la solicitud de autenticación se ha realizado correctamente. Para solicitudes correctas:

* La respuesta de Active Directory o PingFederate incluye un identificador único universal (UUID) para el usuario.
* La respuesta de Entra ID incluye un nombre principal de usuario (UPN).


Para permitir que StorageGRID (el proveedor de servicios) y el proveedor de identidad SSO se comuniquen de forma segura sobre las solicitudes de autenticación de usuarios, completará estas tareas:

. Configure los ajustes en StorageGRID.
. Utilice el software del proveedor de identidad SSO para crear una confianza de parte de confianza (AD FS), una aplicación empresarial (Entra ID) o un proveedor de servicios (PingFederate) para cada nodo de administración.
. Vuelva a StorageGRID para activar SSO.


El modo de recinto de seguridad facilita la realización de esta configuración de fondo y la realización de pruebas de todos los ajustes antes de habilitar SSO. Al utilizar el modo sandbox, los usuarios no pueden iniciar sesión con SSO.



== Acceda al asistente

.Pasos
. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Single Sign-On*. Aparecerá la página Single Sign-On.
+

NOTE: Si el botón Configurar configuración de SSO está desactivado, confirme que ha configurado el proveedor de identidad como origen de identidad federado. Consulte link:requirements-for-sso.html["Requisitos y consideraciones para el inicio de sesión único"].

. Selecciona *Configurar configuración de SSO*. Aparecerá la página Proporcionar detalles de proveedor de identidad.




== Proporcione los detalles del proveedor de identidades

.Pasos
. Seleccione *Tipo SSO* en la lista desplegable.
. Si seleccionó Active Directory como tipo de SSO, introduzca el *nombre del servicio de federación* para el proveedor de identidad, exactamente como aparece en el Servicio de federación de Active Directory (AD FS).
+

NOTE: Para buscar el nombre del servicio de federación, vaya al Administrador de Windows Server. Seleccione *Herramientas* > *Administración AD FS*. En el menú Acción, seleccione *Editar propiedades del servicio de Federación*. El nombre del servicio de Federación se muestra en el segundo campo.

. Especifique qué certificado TLS se utilizará para proteger la conexión cuando el proveedor de identidades envíe información de configuración de SSO en respuesta a las solicitudes de StorageGRID.
+
** *Utilizar certificado CA* del sistema operativo: Utilice el certificado CA predeterminado instalado en el sistema operativo para asegurar la conexión.
** *Utilizar certificado de CA personalizado*: Utilice un certificado de CA personalizado para proteger la conexión.
+
Si selecciona esta configuración, copie el texto del certificado personalizado y péguelo en el cuadro de texto *Certificado CA*.

** *No utilice TLS*: No utilice un certificado TLS para garantizar la conexión.
+

CAUTION: Si cambia el certificado de CA, inmediatamente link:../maintain/starting-or-restarting-service.html["Reinicie el servicio mgmt-api en los nodos de administración"] y prueba un SSO correcto en Grid Manager.



. Seleccione *continuar*. Aparece la página Proporcionar identificador de parte de confianza.




== [[enter-sandbox-mode]]Proporcionar identificador de parte de confianza

. Rellene los campos de la página Proporcionar identificador de parte de confianza según el tipo de SSO seleccionado.
+
[role="tabbed-block"]
====
.Active Directory
--
.. Especifique el *identificador de parte de confianza* para StorageGRID. Este valor controla el nombre que utiliza para cada confianza de parte que confía en AD FS.
+
*** Por ejemplo, si el grid solo tiene un nodo de administración y no prevé agregar más nodos de administración en el futuro, introduzca `SG` o `StorageGRID`.
*** Si el grid incluye más de un nodo de administración, incluya la cadena `[HOSTNAME]` en el identificador. Por ejemplo, `SG-[HOSTNAME]`. Al incluir esta cadena, se obtiene una tabla que muestra el identificador de parte de confianza para cada nodo de administración de la cuadrícula, en función del nombre de host del nodo.
+

NOTE: Debe crear una confianza de parte de confianza para cada nodo de administrador en el sistema StorageGRID. Tener una confianza de parte que confía en cada nodo de administración garantiza que los usuarios puedan iniciar sesión de forma segura desde y hacia cualquier nodo de administración.



.. Selecciona *Guardar e ingresa al modo sandbox*.


--
.ID Entra
--
.. En la sección aplicación de empresa, especifique *Nombre de aplicación de empresa* para StorageGRID. Este valor controla el nombre que se utiliza para cada aplicación de empresa en Entra ID.
+
*** Por ejemplo, si el grid solo tiene un nodo de administración y no prevé agregar más nodos de administración en el futuro, introduzca `SG` o `StorageGRID`.
*** Si el grid incluye más de un nodo de administración, incluya la cadena `[HOSTNAME]` en el identificador. Por ejemplo, `SG-[HOSTNAME]`. Al incluir esta cadena, se obtiene una tabla que muestra un nombre de aplicación de empresa para cada nodo de administración del sistema, según el nombre de host del nodo.
+

NOTE: Debe crear una aplicación empresarial para cada nodo administrador en el sistema StorageGRID. Disponer de una aplicación empresarial para cada nodo de administración garantiza que los usuarios puedan iniciar sesión de forma segura en cualquier nodo de administración.



.. Siga los pasos de link:../admin/creating-enterprise-application-entra-id.html["Cree aplicaciones empresariales en Entra ID"] para crear una aplicación de empresa para cada nodo de administración que se muestra en la tabla.
.. En Entra ID, copie la URL de metadatos de federación para cada aplicación de empresa. A continuación, pegue esta URL en el campo *URL* de metadatos de Federación correspondiente de StorageGRID.
.. Después de haber copiado y pegado una URL de metadatos de federación para todos los nodos de administración, seleccione *Guardar e ingrese al modo sandbox*.


--
.PingFederate
--
.. En la sección Proveedor de servicios (SP), especifique *ID de conexión SP* para StorageGRID. Este valor controla el nombre que utiliza para cada conexión SP en PingFederate.
+
*** Por ejemplo, si el grid solo tiene un nodo de administración y no prevé agregar más nodos de administración en el futuro, introduzca `SG` o `StorageGRID`.
*** Si el grid incluye más de un nodo de administración, incluya la cadena `[HOSTNAME]` en el identificador. Por ejemplo, `SG-[HOSTNAME]`. Al incluir esta cadena, se obtiene una tabla que muestra el identificador de conexión de SP para cada nodo de administración del sistema, según el nombre de host del nodo.
+

NOTE: Debe crear una conexión de SP para cada nodo de administrador en el sistema StorageGRID. Tener una conexión de SP para cada nodo de administrador garantiza que los usuarios puedan iniciar sesión de forma segura en cualquier nodo de administrador.



.. Especifique la dirección URL de metadatos de federación para cada nodo de administración en el campo *URL de metadatos de Federación*.
+
Utilice el siguiente formato:

+
[listing]
----
https://<Federation Service Name>:<port>/pf/federation_metadata.ping?PartnerSpId=<SP Connection ID>
----
.. Selecciona *Guardar e ingresa al modo sandbox*.


--
====




== Configurar las confianzas de partes de confianza, las aplicaciones de la empresa o las conexiones de SP

Después de guardar la configuración y entrar en el modo sandbox, puede completar y probar la configuración para el tipo de SSO seleccionado.

StorageGRID puede permanecer en modo de recinto limitado siempre que sea necesario. Sin embargo, solo los usuarios federados y los usuarios locales pueden iniciar sesión.

[role="tabbed-block"]
====
.Active Directory
--
.Pasos
. Vaya a Servicios de Federación de Active Directory (AD FS).
. Cree una o más confianzas de parte de confianza para StorageGRID, utilizando cada identificador de parte de confianza que se muestra en la tabla de la página Configurar SSO.
+
Debe crear una confianza para cada nodo de administrador que se muestra en la tabla.

+
Para obtener instrucciones, vaya a link:../admin/creating-relying-party-trusts-in-ad-fs.html["Crear confianzas de parte de confianza en AD FS"].



--
.ID Entra
--
.Pasos
. En la página Single Sign-On del nodo de administrador al que ha iniciado sesión actualmente, seleccione el botón para descargar y guardar los metadatos SAML.
. A continuación, para cualquier otro nodo de administrador en el grid, repita estos pasos:
+
.. Inicie sesión en el nodo.
.. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Single Sign-On*.
.. Descargue y guarde los metadatos de SAML de ese nodo.


. Vaya al portal de Azure.
. Siga los pasos de link:../admin/creating-enterprise-application-entra-id.html["Cree aplicaciones empresariales en Entra ID"] para cargar el archivo de metadatos SAML para cada nodo de administración en su aplicación empresarial Entra ID correspondiente.


--
.PingFederate
--
.Pasos
. En la página Single Sign-On del nodo de administrador al que ha iniciado sesión actualmente, seleccione el botón para descargar y guardar los metadatos SAML.
. A continuación, para cualquier otro nodo de administrador en el grid, repita estos pasos:
+
.. Inicie sesión en el nodo.
.. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Single Sign-On*.
.. Descargue y guarde los metadatos de SAML de ese nodo.


. Vaya a PingFederate.
. link:../admin/creating-sp-connection-ping.html["Cree una o varias conexiones de proveedor de servicios (SP) para StorageGRID"]. Utilice el identificador de conexión de SP para cada nodo de administración (que se muestra en la tabla de la página Configurar SSO) y los metadatos de SAML que descargó para ese nodo de administración.
+
Debe crear una conexión de SP para cada nodo de administrador que se muestra en la tabla.



--
====


== [[TEST-sso]]Configuración de prueba

Antes de aplicar el uso de inicio de sesión único para todo el sistema StorageGRID, confirme que el inicio de sesión único y el cierre de sesión único estén configurados correctamente para cada nodo de administración.

[role="tabbed-block"]
====
.Active Directory
--
.Pasos
. En la página Configure SSO, busque el enlace en el paso Test configuration del asistente.
+
La dirección URL se deriva del valor introducido en el campo *Nombre de servicio de Federación*.

. Seleccione el enlace, o copie y pegue la URL en un navegador para acceder a la página de inicio de sesión del proveedor de identidades.
. Para confirmar que puede utilizar SSO para iniciar sesión en StorageGRID, seleccione *Iniciar sesión en uno de los siguientes sitios*, seleccione el identificador de la parte que confía para su nodo de administración principal y seleccione *Iniciar sesión*.
. Introduzca el nombre de usuario y la contraseña federados.
+
** Si las operaciones de inicio de sesión y cierre de sesión SSO se realizan correctamente, se muestra un mensaje de éxito.
** Si la operación de SSO se realiza sin errores, se muestra un mensaje de error. Solucione el problema, borre las cookies del navegador e inténtelo de nuevo.


. Repita estos pasos para verificar la conexión SSO para cada nodo de administrador en el grid.


--
.ID Entra
--
.Pasos
. Vaya a la página Single Sign-On del portal de Azure.
. Seleccione *probar esta aplicación*.
. Introduzca las credenciales de un usuario federado.
+
** Si las operaciones de inicio de sesión y cierre de sesión SSO se realizan correctamente, se muestra un mensaje de éxito.
** Si la operación de SSO se realiza sin errores, se muestra un mensaje de error. Solucione el problema, borre las cookies del navegador e inténtelo de nuevo.


. Repita estos pasos para verificar la conexión SSO para cada nodo de administrador en el grid.


--
.PingFederate
--
.Pasos
. En la página Configure SSO, seleccione el primer enlace del mensaje de modo sandbox.
+
Seleccione y pruebe un enlace cada vez.

. Introduzca las credenciales de un usuario federado.
+
** Si las operaciones de inicio de sesión y cierre de sesión SSO se realizan correctamente, se muestra un mensaje de éxito.
** Si la operación de SSO se realiza sin errores, se muestra un mensaje de error. Solucione el problema, borre las cookies del navegador e inténtelo de nuevo.


. Seleccione el siguiente enlace para verificar la conexión de SSO para cada nodo de administrador de la cuadrícula.
+
Si ve un mensaje Página caducada, seleccione el botón *Atrás* de su explorador y vuelva a enviar sus credenciales.



--
====


== Active el inicio de sesión único

Una vez que haya confirmado que puede usar SSO para iniciar sesión en cada nodo de administración, puede habilitar SSO en todo el sistema StorageGRID.


TIP: Cuando SSO está habilitado, todos los usuarios deben utilizar SSO para acceder a Grid Manager, al arrendatario Manager, a la API de gestión de grid y a la API de gestión de inquilinos. Los usuarios locales ya no pueden acceder a StorageGRID.

.Pasos
. En el paso Configuración de prueba del asistente de configuración de SSO, seleccione *Habilitar SSO*.
. Revise el mensaje de advertencia y seleccione *Habilitar SSO*.
+
El inicio de sesión único ahora está activado. Aparece la página Single Sign-On y ahora incluye los detalles del SSO que acaba de configurar.

. Para editar la configuración, seleccione *Editar*.
. Para desactivar el inicio de sesión único, seleccione *Desactivar SSO*.



TIP: Si utiliza el portal de Azure y accede a StorageGRID desde el mismo equipo que utiliza para acceder a Entra ID, asegúrese de que el usuario del portal de Azure también es un usuario autorizado de StorageGRID (un usuario de un grupo federado que se ha importado a StorageGRID o cierre sesión del portal de Azure antes de intentar iniciar sesión en StorageGRID.
