---
permalink: admin/copying-storagegrid-system-ca-certificate.html 
sidebar: sidebar 
keywords: grid ca certificate, copy certificate 
summary: 'StorageGRID utiliza una entidad de certificación interna \(CA\) para proteger el tráfico interno. Este certificado no cambia si carga sus propios certificados.' 
---
= Copie el certificado de la CA de cuadrícula
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID utiliza una entidad de certificación (CA) interna para proteger el tráfico interno. Este certificado no cambia si carga sus propios certificados.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Tienes link:admin-group-permissions.html["permisos de acceso específicos"].


.Acerca de esta tarea
Si se ha configurado un certificado de servidor personalizado, las aplicaciones cliente deben verificar el servidor mediante el certificado de servidor personalizado. No deben copiar el certificado de CA desde el sistema StorageGRID.

.Pasos
. Seleccione *CONFIGURACIÓN* > *Seguridad* > *certificados* y, a continuación, seleccione la ficha *CA* de cuadrícula.
. En la sección *Certificado PEM*, descargue o copie el certificado.
+
[role="tabbed-block"]
====
.Descargue el archivo de certificado
--
Descargue el archivo de certificado `.pem`.

.. Seleccione *Descargar certificado*.
.. Especifique el nombre del archivo de certificado y la ubicación de descarga. Guarde el archivo con la extensión `.pem`.
+
Por ejemplo: `storagegrid_certificate.pem`



--
.PEM de certificado de copia
--
Copie el texto del certificado que se va a pegar en otro lugar.

.. Seleccione *Copiar certificado PEM*.
.. Pegue el certificado copiado en un editor de texto.
.. Guarde el archivo de texto con la extensión `.pem`.
+
Por ejemplo: `storagegrid_certificate.pem`



--
====

