---
permalink: admin/creating-enterprise-application-entra-id.html 
sidebar: sidebar 
keywords: enterprise application, entra id, single sign on, sso 
summary: Utilice Entra ID para crear una aplicación de empresa para cada nodo de administración del sistema. 
---
= Cree aplicaciones empresariales en Entra ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilice Entra ID para crear una aplicación de empresa para cada nodo de administración del sistema.

.Antes de empezar
* Ha comenzado a configurar el inicio de sesión único para StorageGRID y ha seleccionado *Entra ID* como tipo SSO.
* Ya link:../admin/configure-sso.html#enter-sandbox-mode["se ha introducido el modo sandbox"] está en Grid Manager.
* Tiene el *Nombre de la aplicación de empresa* para cada nodo de administración de su sistema. Puede copiar estos valores de la tabla de detalles Nodo de administración de la página Configurar SSO.
+

NOTE: Debe crear una aplicación empresarial para cada nodo administrador en el sistema StorageGRID. Disponer de una aplicación empresarial para cada nodo de administración garantiza que los usuarios puedan iniciar sesión de forma segura en cualquier nodo de administración.

* Tiene experiencia en la creación de aplicaciones empresariales en Entra ID.
* Tiene una cuenta de Azure con una suscripción activa.
* Tiene uno de los siguientes roles en la cuenta de Entra ID: Administrador global, Administrador de aplicaciones en la nube, Administrador de aplicaciones o propietario del principal de servicio.




== Acceda a Entra ID

.Pasos
. Inicie sesión en el https://portal.azure.com["Portal de Azure"^].
. Navegar a https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["ID Entra"^].
. Seleccione https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Aplicaciones de negocio"^].




== Creación de aplicaciones empresariales y guardado de la configuración de SSO de StorageGRID

Para guardar la configuración de inicio de sesión único para el identificador de entra en StorageGRID, debe utilizar el identificador de entra para crear una aplicación de empresa para cada nodo de administración. Copiarás las URL de metadatos de federación desde Entra ID y las pegarás en los campos correspondientes de la URL de metadatos de *Federation* en la página Configurar SSO.

.Pasos
. Repita los siguientes pasos para cada nodo de administrador.
+
.. En el panel de aplicaciones de Entra ID Enterprise, seleccione *Nueva aplicación*.
.. Seleccione *Crear su propia aplicación*.
.. Para el nombre, introduzca el nombre de la aplicación *Enterprise* que copió de la tabla de detalles del nodo de administración en la página Configurar SSO.
.. Deje seleccionada la opción *integrar cualquier otra aplicación que no encuentre en la galería (no galería)*.
.. Seleccione *Crear*.
.. Seleccione el enlace *Get Started* en *2. Configure el cuadro de inicio de sesión único en* o seleccione el enlace *Single Sign-On* en el margen izquierdo.
.. Seleccione la casilla *SAML*.
.. Copie la URL * metadatos de Federación de aplicaciones*, que puede encontrar en *Paso 3 Certificado de firma SAML*.
.. Vaya a la página Configurar SSO y pegue la URL en el campo *URL de metadatos de federación* que corresponde al nombre de la aplicación *Enterprise* que utilizó.


. Después de haber pegado una URL de metadatos de federación para cada nodo de administración y haber realizado todos los demás cambios necesarios en la configuración de SSO, seleccione *Guardar* en la página Configurar SSO.




== Descargue los metadatos de SAML para cada nodo de administración

Una vez guardada la configuración de SSO, puede descargar un archivo de metadatos SAML para cada nodo de administrador del sistema StorageGRID.

.Pasos
. Repita estos pasos para cada nodo de administración.
+
.. Inicie sesión en StorageGRID desde el nodo de administrador.
.. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Single Sign-On*.
.. Seleccione el botón para descargar los metadatos de SAML de ese nodo de administración.
.. Guarde el archivo, que cargará en Entra ID.






== Cargue metadatos de SAML en cada aplicación empresarial

Después de descargar un archivo de metadatos SAML para cada nodo de administración de StorageGRID, realice los siguientes pasos en Entra ID:

.Pasos
. Vuelva al portal de Azure.
. Repita estos pasos con cada aplicación de empresa:
+

NOTE: Es posible que deba actualizar la página aplicaciones de empresa para ver las aplicaciones que ha agregado anteriormente en la lista.

+
.. Vaya a la página Propiedades de la aplicación de empresa.
.. Establezca *asignación requerida* en *no* (a menos que desee configurar las asignaciones por separado).
.. Vaya a la página Single Sign-On.
.. Complete la configuración de SAML.
.. Seleccione el botón *Upload metadata file* y seleccione el archivo de metadatos SAML que descargó para el nodo de administración correspondiente.
.. Después de cargar el archivo, seleccione *Guardar* y, a continuación, seleccione *X* para cerrar el panel. Volverá a la página Set up Single Sign-On with SAML.


. link:../admin/configure-sso.html#test-sso["Pruebe cada aplicación"].

