---
permalink: admin/creating-enterprise-application-azure.html 
sidebar: sidebar 
keywords: enterprise application, azure ad, single sign on, sso 
summary: Puede usar Azure AD para crear una aplicación empresarial para cada nodo de administrador del sistema. 
---
= Cree aplicaciones empresariales en Azure AD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede usar Azure AD para crear una aplicación empresarial para cada nodo de administrador del sistema.

.Antes de empezar
* Ha empezado a configurar el inicio de sesión único para StorageGRID y ha seleccionado *Azure* como tipo de SSO.
* *Modo Sandbox* está seleccionado en la página Single Sign-On de Grid Manager. Consulte link:../admin/using-sandbox-mode.html["Utilizar el modo de recinto de seguridad"].
* Tiene el *Nombre de la aplicación de empresa* para cada nodo de administración de su sistema. Se pueden copiar estos valores de la tabla de detalles Admin Node en la página StorageGRID Single Sign-On.
+

NOTE: Debe crear una aplicación empresarial para cada nodo administrador en el sistema StorageGRID. Disponer de una aplicación empresarial para cada nodo de administración garantiza que los usuarios puedan iniciar sesión de forma segura en cualquier nodo de administración.

* Tiene experiencia en la creación de aplicaciones empresariales en Azure Active Directory.
* Tiene una cuenta de Azure con una suscripción activa.
* Tiene uno de los siguientes roles en la cuenta de Azure: Administrador global, administrador de aplicaciones de cloud, administrador de aplicaciones o propietario del director del servicio.




== Acceda a Azure AD

.Pasos
. Inicie sesión en el https://portal.azure.com["Portal de Azure"^].
. Navegar a https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade["Active Directory para Azure"^].
. Seleccione https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/["Aplicaciones de negocio"^].




== Creación de aplicaciones empresariales y guardado de la configuración de SSO de StorageGRID

Para guardar la configuración de SSO para Azure en StorageGRID, debe usar Azure para crear una aplicación empresarial para cada nodo de administración. Copiará las URL de metadatos de federación de Azure y las pegará en los campos de la URL* de metadatos de Federación correspondientes de la página de inicio de sesión único de StorageGRID.

.Pasos
. Repita los siguientes pasos para cada nodo de administrador.
+
.. En el panel aplicaciones de Azure Enterprise, seleccione *Nueva aplicación*.
.. Seleccione *Crear su propia aplicación*.
.. Para el nombre, introduzca el *Nombre de la aplicación de empresa* que ha copiado de la tabla de detalles del nodo de administración en la página Inicio de sesión único de StorageGRID.
.. Deje seleccionada la opción *integrar cualquier otra aplicación que no encuentre en la galería (no galería)*.
.. Seleccione *Crear*.
.. Seleccione el enlace *Get Started* en *2. Configure el cuadro de inicio de sesión único en* o seleccione el enlace *Single Sign-On* en el margen izquierdo.
.. Seleccione la casilla *SAML*.
.. Copie la URL * metadatos de Federación de aplicaciones*, que puede encontrar en *Paso 3 Certificado de firma SAML*.
.. Vaya a la página Inicio de sesión único de StorageGRID y pegue la dirección URL en el campo *URL* de metadatos de Federación que corresponda al *Nombre de aplicación de empresa* que ha utilizado.


. Una vez que haya pegado una URL de metadatos de federación para cada nodo de administración y realizado todos los demás cambios necesarios en la configuración de SSO, seleccione *Guardar* en la página Inicio de sesión único de StorageGRID.




== Descargue los metadatos de SAML para cada nodo de administración

Una vez guardada la configuración de SSO, puede descargar un archivo de metadatos SAML para cada nodo de administrador del sistema StorageGRID.

.Pasos
. Repita estos pasos para cada nodo de administración.
+
.. Inicie sesión en StorageGRID desde el nodo de administrador.
.. Seleccione *CONFIGURACIÓN* > *Control de acceso* > *Single Sign-On*.
.. Seleccione el botón para descargar los metadatos de SAML de ese nodo de administración.
.. Guarde el archivo, que cargará en Azure AD.






== Cargue metadatos de SAML en cada aplicación empresarial

Después de descargar un archivo de metadatos SAML para cada nodo de administrador de StorageGRID, siga estos pasos en Azure AD:

.Pasos
. Vuelva al portal de Azure.
. Repita estos pasos con cada aplicación de empresa:
+

NOTE: Es posible que deba actualizar la página aplicaciones de empresa para ver las aplicaciones que ha agregado anteriormente en la lista.

+
.. Vaya a la página Propiedades de la aplicación de empresa.
.. Establezca *asignación requerida* en *no* (a menos que desee configurar las asignaciones por separado).
.. Vaya a la página Single Sign-On.
.. Complete la configuración de SAML.
.. Seleccione el botón *Upload metadata file* y seleccione el archivo de metadatos SAML que descargó para el nodo de administración correspondiente.
.. Después de cargar el archivo, seleccione *Guardar* y, a continuación, seleccione *X* para cerrar el panel. Volverá a la página Set up Single Sign-On with SAML.


. Siga los pasos de link:../admin/using-sandbox-mode.html["Utilizar el modo de recinto de seguridad"] para probar cada aplicación.

