---
permalink: admin/disabling-single-sign-on.html 
sidebar: sidebar 
keywords: disable sso, disable single sign on 
summary: 'Puede deshabilitar el inicio de sesión único \(SSO\) si ya no desea utilizar esta funcionalidad. Debe deshabilitar el inicio de sesión único antes de poder deshabilitar la federación de identidades.' 
---
= Deshabilitar SSO
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ya no desea usar esta funcionalidad, puede deshabilitar el inicio de sesión único (SSO). Debe deshabilitar el inicio de sesión único antes de poder deshabilitar la federación de identidades.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Tienes link:admin-group-permissions.html["permisos de acceso específicos"].


.Pasos
. Seleccione *Configuración* > *Control de acceso* > *Inicio de sesión único*.
+
Aparece la página Single Sign-On.

. Seleccione *Deshabilitar SSO*.
. Seleccione *Sí*.
+
Aparece un mensaje de advertencia que indica que los usuarios locales podrán iniciar sesión.



La próxima vez que inicie sesión en StorageGRID, aparecerá la página Inicio de sesión en StorageGRID, donde deberá introducir el nombre de usuario y la contraseña de un usuario de StorageGRID local o federado.
