---
permalink: admin/how-sso-works.html 
sidebar: sidebar 
keywords: single sign on, sso, SAML 
summary: 'Cuando el inicio de sesión único (SSO) está habilitado, los usuarios pueden acceder a Grid Manager, Tenant Manager, Grid Management API o Tenant Management API solo si sus credenciales están autorizadas mediante el proceso de inicio de sesión SSO implementado por su organización.  Los usuarios locales no pueden iniciar sesión en StorageGRID.' 
---
= Cómo funciona el SSO
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando el inicio de sesión único (SSO) está habilitado, los usuarios pueden acceder a Grid Manager, Tenant Manager, Grid Management API o Tenant Management API solo si sus credenciales están autorizadas mediante el proceso de inicio de sesión SSO implementado por su organización.  Los usuarios locales no pueden iniciar sesión en StorageGRID.

El sistema StorageGRID admite el inicio de sesión único (SSO) con el estándar de lenguaje de marcado de aserción de seguridad 2.0 (SAML 2.0).

Antes de habilitar el inicio de sesión único (SSO), revise cómo se ven afectados los procesos de inicio de sesión y cierre de sesión de StorageGRID cuando se habilita SSO.



== Inicie sesión cuando SSO esté habilitado

Cuando se habilita SSO y usted inicia sesión en StorageGRID, se le redirigirá a la página SSO de su organización para validar sus credenciales.

.Pasos
. Introduzca el nombre de dominio o la dirección IP completos de cualquier nodo de administración de StorageGRID en un navegador web.
+
Aparece la página Inicio de sesión de StorageGRID.

+
** Si es la primera vez que accede a la URL en este navegador, se le solicitará un ID de cuenta.
** Si ya ha accedido al Administrador de red o al Administrador de inquilinos, se le solicitará que seleccione una cuenta reciente o que ingrese un ID de cuenta.
+

NOTE: La página de inicio de sesión de StorageGRID no se muestra cuando se introduce la dirección URL completa para una cuenta de inquilino (es decir, un nombre de dominio completo o una dirección IP seguida de `/?accountId=_20-digit-account-id_`). En su lugar, se le redirigirá inmediatamente a la página de inicio de sesión de SSO de su organización, donde puede <<signin_sso,Inicie sesión con sus credenciales de SSO>>.



. Indique si desea acceder al administrador de grid o al responsable de inquilinos:
+
** Para acceder a Grid Manager, deje el campo *ID de cuenta* en blanco, introduzca *0* como ID de cuenta o seleccione *Gestor de cuadrícula* si aparece en la lista de cuentas recientes.
** Para acceder al Administrador de arrendatarios, introduzca el ID de cuenta de arrendatario de 20 dígitos o seleccione un arrendatario por nombre si aparece en la lista de cuentas recientes.


. Seleccione *Iniciar sesión*
+
StorageGRID le redirige a la página de inicio de sesión con SSO de su organización. Por ejemplo:

. [[entrar_sso]]inicia sesión con sus credenciales de SSO.
+
Si sus credenciales de SSO son correctas:

+
.. El proveedor de identidades (IDP) ofrece una respuesta de autenticación a StorageGRID.
.. StorageGRID valida la respuesta de autenticación.
.. Si la respuesta es válida y pertenece a un grupo federado con permisos de acceso a StorageGRID, se ha iniciado sesión en el Gestor de grid o el Gestor de inquilinos, según la cuenta seleccionada.
+

NOTE: Si no se puede acceder a la cuenta de servicio, puede iniciar sesión siempre que sea un usuario existente que pertenezca a un grupo federado con permisos de acceso StorageGRID.



. Opcionalmente, acceda a otros nodos de administración o acceda al administrador de grid o al administrador de inquilinos, si dispone de los permisos adecuados.
+
No es necesario volver a introducir las credenciales de SSO.





== Cierre sesión cuando SSO esté habilitado

Cuando se habilita SSO en StorageGRID, lo que sucede cuando se inicia sesión depende de lo que se haya iniciado sesión y del lugar en el que se está cerrando sesión.

.Pasos
. Localice el enlace *Sign Out* en la esquina superior derecha de la interfaz de usuario.
. Selecciona *Cerrar sesión*.
+
Aparece la página Inicio de sesión de StorageGRID. La lista desplegable *Cuentas recientes* se actualiza para incluir *Grid Manager* o el nombre del inquilino, por lo que puede acceder a estas interfaces de usuario más rápidamente en el futuro.

+

TIP: La tabla resume lo que sucede cuando se inicia sesión si está utilizando una sola sesión del navegador. Si ha iniciado sesión en StorageGRID en varias sesiones de explorador, debe cerrar la sesión en todas las sesiones de explorador por separado.

+
[cols="1a,1a,1a"]
|===
| Si ha iniciado sesión en... | Y salir de... | Se ha cerrado sesión en... 


 a| 
Grid Manager en uno o varios nodos de administrador
 a| 
Grid Manager en cualquier nodo de administrador
 a| 
Grid Manager en todos los nodos de administración

*Nota:* Si usa Entra ID para SSO, puede que tome algunos minutos cerrar sesión en todos los nodos de administración.



 a| 
Administrador de inquilinos en uno o varios nodos de administrador
 a| 
Inquilino Manager en cualquier nodo de administrador
 a| 
Administrador de inquilinos en todos los nodos de administrador



 a| 
Tanto Grid Manager como Inquilino Manager
 a| 
Administrador de grid
 a| 
Sólo Grid Manager. También debe cerrar sesión en el Administrador de inquilinos para cerrar la sesión de SSO.



 a| 
Administrador de inquilinos
 a| 
Sólo el administrador de arrendatarios. También debe cerrar sesión en Grid Manager para cerrar la sesión en SSO.

|===

