---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 'Una cuenta de inquilino permite usar la API DE REST Simple Storage Service \(S3\) para almacenar y recuperar objetos en un sistema StorageGRID.' 
---
= ¿Qué son las cuentas de inquilinos?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una cuenta de inquilino permite usar la API DE REST DE Simple Storage Service (S3) para almacenar y recuperar objetos en un sistema StorageGRID.


TIP: Se han eliminado los detalles de Swift de esta versión del sitio del documento. Consulte https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11,8: Gestión de inquilinos"^].

Como administrador de grid, crea y gestiona las cuentas de tenant que los clientes S3 utilizan para almacenar y recuperar objetos.

Cada cuenta de inquilino tiene grupos locales o federados, usuarios, bloques de S3 y objetos.

Las cuentas de arrendatario se pueden utilizar para segregar objetos almacenados por diferentes entidades. Por ejemplo, pueden utilizarse varias cuentas de inquilino en cualquiera de estos casos de uso:

* *Caso de uso empresarial:* Si administra un sistema StorageGRID en una aplicación empresarial, es posible que desee segregar el almacenamiento de objetos de la red por los diferentes departamentos de la organización. En este caso, podría crear cuentas de inquilino para el departamento de marketing, el departamento de soporte al cliente, el departamento de recursos humanos, etc.
+

NOTE: Si utiliza el protocolo de cliente S3, puede utilizar bloques S3 y políticas de bloques para segregar objetos entre los departamentos de una empresa. No es necesario utilizar cuentas de inquilino. Consulte las instrucciones de implantación para link:../s3/bucket-and-group-access-policies.html["Bloques de S3 y políticas de bloques"]obtener más información.

* *Caso de uso del proveedor de servicios:* Si administra un sistema StorageGRID como proveedor de servicios, puede segregar el almacenamiento de objetos de la red por las diferentes entidades que alquile el almacenamiento en la red. En este caso, creará cuentas de inquilino para la empresa A, la empresa B, la empresa C, etc.


Para obtener más información, consulte link:../tenant/index.html["Usar una cuenta de inquilino"].



== ¿Cómo se crea una cuenta de inquilino?

Utilice Grid Manager para crear una cuenta de inquilino. Al crear una cuenta de inquilino, especifique la siguiente información:

* Información básica, como el nombre del inquilino, el tipo de cliente (S3) y la cuota de almacenamiento opcional.
* Permisos para la cuenta de inquilino, como si la cuenta de inquilino puede usar los servicios de la plataforma S3, configurar su propio origen de identidad, usar S3 Select o usar una conexión de federación de grid.
* Acceso raíz inicial para el inquilino, basado en si el sistema StorageGRID utiliza usuarios y grupos locales, federación de identidades o inicio de sesión único (SSO).


Además, puede habilitar la configuración Bloqueo de objetos S3 para el sistema StorageGRID si las cuentas de arrendatario S3 necesitan cumplir con los requisitos normativos. Cuando se habilita el bloqueo de objetos S3, todas las cuentas de inquilinos S3 pueden crear y gestionar bloques conforme a la normativa.



== ¿Para qué se utiliza el gestor de inquilinos?

Después de crear la cuenta de inquilino, los usuarios de inquilino pueden iniciar sesión en el Administrador de inquilinos para realizar tareas como las siguientes:

* Configurar la federación de identidades (a menos que el origen de identidad se comparta con la cuadrícula)
* Gestionar grupos y usuarios
* Utilice la federación de grid para la clonación de cuentas y la replicación entre grid
* Gestión de claves de acceso de S3
* Cree y gestione bloques de S3
* Utilice los servicios de la plataforma S3
* Utilice S3 Select
* Supervise el uso del almacenamiento



TIP: Mientras que los usuarios inquilinos de S3 pueden crear y gestionar la clave de acceso y los depósitos S3 con el administrador de inquilinos, deben usar una aplicación cliente S3 para ingerir y gestionar objetos. Consulte link:../s3/index.html["USE LA API DE REST DE S3"] para obtener más información.
