---
permalink: admin/supported-ciphers-for-outgoing-tls-connections.html 
sidebar: sidebar 
keywords: tls cipher suites, transport layer security connections 
summary: 'El sistema StorageGRID admite un conjunto limitado de conjuntos de cifrado para conexiones de seguridad de la capa de transporte \(TLS\) a los sistemas externos utilizados para la federación de identidades y los pools de almacenamiento en cloud.' 
---
= Cifrados compatibles para conexiones TLS salientes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El sistema StorageGRID es compatible con un conjunto limitado de conjuntos de cifrado para conexiones TLS (seguridad de la capa de transporte) con los sistemas externos utilizados para la federación de identidades y los pools de almacenamiento en cloud.



== Versiones compatibles de TLS

StorageGRID admite TLS 1.2 y TLS 1.3 para conexiones a sistemas externos que se utilizan para la federación de identidades y los pools de almacenamiento en cloud.

Los cifrados TLS compatibles con el uso de sistemas externos se han seleccionado para garantizar la compatibilidad con una variedad de sistemas externos.  La lista es más grande que la lista de cifrados compatibles para su uso con aplicaciones cliente S3.  Para configurar cifrados, vaya a *Configuración* > *Seguridad* > *Configuración de seguridad* y seleccione *Políticas TLS y SSH*.


NOTE: Las opciones de configuración de TLS, como las versiones de protocolos, los cifrados, los algoritmos de intercambio de claves y los algoritmos MAC, no se pueden configurar en StorageGRID. Si tiene solicitudes específicas sobre esta configuración, póngase en contacto con su representante de cuenta de NetApp.
