---
permalink: admin/updating-storagegrid-license-information.html 
sidebar: sidebar 
keywords: storagegrid license, update license, add storage capacity 
summary: Debe actualizar la información de licencia del sistema de StorageGRID en cualquier momento que cambien las condiciones de su licencia. Por ejemplo, debe actualizar la información de la licencia si adquiere capacidad de almacenamiento adicional para su grid. 
---
= Actualice la información de licencia de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe actualizar la información de licencia del sistema de StorageGRID en cualquier momento que cambien las condiciones de su licencia. Por ejemplo, debe actualizar la información de la licencia si adquiere capacidad de almacenamiento adicional para su grid.

.Antes de empezar
* Tiene un nuevo archivo de licencia que se aplicará al sistema StorageGRID.
* Tienes link:admin-group-permissions.html["permisos de acceso específicos"].
* Tiene la clave de acceso de aprovisionamiento.


.Pasos
. Seleccione *Mantenimiento* > *Sistema* > *Licencia*.
. En la sección Actualizar licencia, seleccione *Examinar*.
. Busque y seleccione el nuevo archivo de licencia (`.txt`).
+
El nuevo archivo de licencia se valida y muestra.

. Introduzca la clave de acceso de aprovisionamiento.
. Seleccione *Guardar*.

