---
permalink: s3/get-bucket-metadata-notification-configuration-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, GET bucket metadata notification configuration 
summary: La solicitud de configuración DE notificación DE metadatos GET Bucket permite recuperar el XML de configuración que se utiliza para configurar la integración de búsqueda de bloques individuales. 
---
= OBTENGA la configuración de notificación de metadatos del bloque de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La solicitud de configuración DE notificación DE metadatos GET Bucket permite recuperar el XML de configuración que se utiliza para configurar la integración de búsqueda de bloques individuales.

Para completar esta operación, debe tener el permiso s3:GetBucketMetadataNotification, o ser raíz de la cuenta.



== Ejemplo de solicitud

Esta solicitud recupera la configuración de notificación de metadatos para el depósito denominado `bucket`.

[listing, subs="specialcharacters,quotes"]
----
GET /bucket?x-ntap-sg-metadata-notification HTTP/1.1
Date: _date_
Authorization: _authorization string_
Host: _host_
----


== Respuesta

El cuerpo de la respuesta incluye la configuración de notificación de metadatos para el bloque. La configuración de notificaciones de metadatos permite determinar cómo se configura el bloque para la integración de búsquedas. Es decir, permite determinar a qué objetos se indexan y a qué extremos se envían los metadatos de sus objetos.

[listing]
----
<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>rule-status</Status>
        <Prefix>key-prefix</Prefix>
        <Destination>
           <Urn>arn:aws:es:_region:account-ID_:domain/_mydomain/myindex/mytype_</Urn>
        </Destination>
    </Rule>
    <Rule>
        <ID>Rule-2</ID>
         ...
    </Rule>
     ...
</MetadataNotificationConfiguration>
----
Cada configuración de notificación de metadatos incluye una o varias reglas. Cada regla especifica los objetos a los que se aplica y el destino al que StorageGRID debe enviar metadatos de objetos. Los destinos se deben especificar con el URN de un extremo de StorageGRID.

[cols="1a,2a,1a"]
|===
| Nombre | Descripción | Obligatorio 


 a| 
MetadataNotificationConfiguration
 a| 
Etiqueta de contenedor para las reglas que se usan para especificar los objetos y el destino de las notificaciones de metadatos.

Contiene uno o más elementos Regla.
 a| 
Sí



 a| 
Regla
 a| 
Código de contenedor de una regla que identifica los objetos cuyos metadatos deben agregarse a un índice especificado.

Se rechazan las reglas con prefijos superpuestos.

Incluido en el elemento MetadataNotificationConfiguration.
 a| 
Sí



 a| 
ID
 a| 
Identificador único de la regla.

Incluido en el elemento Regla.
 a| 
No



 a| 
Estado
 a| 
El estado puede ser "activado" o "desactivado". No se toman medidas para las reglas que están desactivadas.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
Prefijo
 a| 
Los objetos que coinciden con el prefijo se ven afectados por la regla y sus metadatos se envían al destino especificado.

Para hacer coincidir todos los objetos, especifique un prefijo vacío.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
Destino
 a| 
Etiqueta de contenedor para el destino de una regla.

Incluido en el elemento Regla.
 a| 
Sí



 a| 
No
 a| 
URN del destino donde se envían los metadatos del objeto. Debe ser URN de un extremo de StorageGRID con las siguientes propiedades:

* `es` debe ser el tercer elemento.
* El URN debe terminar con el índice y el tipo donde se almacenan los metadatos, en la forma `domain-name/myindex/mytype`.


Los extremos se configuran con el administrador de inquilinos o la API de gestión de inquilinos. Tienen el siguiente formato:

* `arn:aws:es:_region:account-ID_:domain/mydomain/myindex/mytype`
* `urn:mysite:es:::mydomain/myindex/mytype`


El punto final debe estar configurado antes de enviar el XML de configuración o la configuración fallará con un error 404.

El valor de urn se incluye en el elemento Destination.
 a| 
Sí

|===


== Ejemplo de respuesta

El XML incluido entre las  `<MetadataNotificationConfiguration></MetadataNotificationConfiguration>` etiquetas muestra cómo se configura la integración con un punto final de integración de búsqueda para el bloque. En este ejemplo, los metadatos del objeto se envían a un índice de Elasticsearch denominado `current` y tipo denominado `2017` que se aloja en un dominio de AWS denominado `records`.

[listing]
----
HTTP/1.1 200 OK
Date: Thu, 20 Jul 2017 18:24:05 GMT
Connection: KEEP-ALIVE
Server: StorageGRID/11.0.0
x-amz-request-id: 3832973499
Content-Length: 264
Content-Type: application/xml

<MetadataNotificationConfiguration>
    <Rule>
        <ID>Rule-1</ID>
        <Status>Enabled</Status>
        <Prefix>2017</Prefix>
        <Destination>
           <Urn>arn:aws:es:us-east-1:3333333:domain/records/current/2017</Urn>
        </Destination>
    </Rule>
</MetadataNotificationConfiguration>
----
.Información relacionada
link:../tenant/index.html["Usar una cuenta de inquilino"]
