---
permalink: s3/upload-part.html 
sidebar: sidebar 
keywords: s3 UploadPart operation 
summary: La operación UploadPart carga una pieza en una carga de varias partes para un objeto. 
---
= Cabeceras de solicitud admitidas y no admitidas para operaciones S3 UploadPart en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La operación UploadPart carga una pieza en una carga de varias partes para un objeto.



[[supported-request-headers]]
== Encabezados de solicitud admitidos

Se admiten los siguientes encabezados de solicitud:

* Encabezados de solicitud de suma de comprobación:
+
--
** `x-amz-checksum-crc32`
** `x-amz-checksum-crc32c`
** `x-amz-checksum-crc64nvme`
** `x-amz-checksum-sha256`


--
+
Si especificaste una suma de comprobación CRC-32, CRC-32C, CRC-64/NVME o SHA-256 durante la solicitud CreateMultipartUpload, también debes incluir el encabezado de solicitud de suma de comprobación en cada solicitud UploadPart.

+

NOTE: Si una solicitud CreateMultipartUpload no especifica una suma de comprobación, StorageGRID no calcula una suma de comprobación CRC-64/NVME por defecto para un objeto.

* `Content-Length`
* `Content-MD5`




[[request-headers-for-server-side-encryption]]
== Solicitar encabezados para el cifrado del servidor

Si especificó el cifrado SSE-C para la solicitud CreateMultipartUpload, también debe incluir los siguientes encabezados de solicitud en cada solicitud UploadPart:

* `x-amz-server-side-encryption-customer-algorithm`: Especificar `AES256`.
* `x-amz-server-side-encryption-customer-key`: Especifique la misma clave de cifrado que proporcionó en la solicitud CreateMultipartUpload.
* `x-amz-server-side-encryption-customer-key-MD5`: Especifique el mismo resumen de MD5 que proporcionó en la solicitud CreateMultipartUpload.



CAUTION: Las claves de cifrado que proporcione no se almacenan nunca. Si pierde una clave de cifrado, perderá el objeto correspondiente. Antes de utilizar las claves proporcionadas por el cliente para proteger los datos de objetos, revise las consideraciones en link:using-server-side-encryption.html["Usar cifrado del servidor"].



[[unsupported-request-headers]]
== Encabezados de solicitud no compatibles

No se admiten las siguientes cabeceras de solicitud:

* `x-amz-sdk-checksum-algorithm`
* `x-amz-trailer`
* `x-amz-checksum-md5`
* `x-amz-checksum-sha1`
* `x-amz-checksum-sha512`
* `x-amz-checksum-xxhash3`
* `x-amz-checksum-xxhash64`
* `x-amz-checksum-xxhash128`




[[versioning]]
== Creación de versiones

La carga de varias partes consiste en operaciones independientes para iniciar la carga, enumerar cargas, cargar piezas, ensamblar las piezas cargadas y completar la carga. Los objetos se crean (y se versionan si corresponde) cuando se realiza la operación CompleteMultipartUpload.
