---
permalink: monitor/access-snmp-mib.html 
sidebar: sidebar 
keywords: mib, snmp, monitoring 
summary: Los archivos MIB contienen definiciones e información sobre las propiedades de los recursos y servicios gestionados para los nodos en el grid. Es posible acceder a los archivos MIB que definen los objetos y las notificaciones para StorageGRID. Estos archivos pueden ser útiles para supervisar la cuadrícula. 
---
= Acceda a los archivos MIB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los archivos MIB contienen definiciones e información sobre las propiedades de los recursos y servicios gestionados para los nodos en el grid. Es posible acceder a los archivos MIB que definen los objetos y las notificaciones para StorageGRID. Estos archivos pueden ser útiles para supervisar la cuadrícula.

Consulte link:using-snmp-monitoring.html["Usar supervisión de SNMP"] para obtener más información acerca de los archivos SNMP y MIB.



== Acceda a los archivos MIB

Siga estos pasos para acceder a los archivos MIB.

.Pasos
. Seleccione *CONFIGURACIÓN* > *Supervisión* > *Agente SNMP*.
. En la página del agente SNMP, seleccione el archivo que desee descargar:
+
** *NETAPP-STORAGEGRID-MIB.txt*: Define la tabla de alertas y las notificaciones (traps) a las que se puede acceder en todos los nodos de administración.
** *ES-NETAPP-06-MIB.mib*: Define objetos y notificaciones para dispositivos basados en E-Series.
** *MIB_1_10.zip*: Define objetos y notificaciones para dispositivos con interfaz BMC.
+
[]
====

TIP: También puede acceder a los archivos MIB en la siguiente ubicación en cualquier nodo StorageGRID: `/usr/share/snmp/mibs`

====


. Para extraer los OID de StorageGRID del archivo MIB:
+
.. Obtenga el OID de la raíz de la MIB de StorageGRID:
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`

+
Resultado: `.1.3.6.1.4.1.789.28669` (`28669` Es siempre el OID de StorageGRID)

.. Grep para el OID de StorageGRID en todo el árbol (utilizando `paste` para unir líneas):
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`






TIP: El `snmptranslate` comando tiene muchas opciones que son útiles para explorar la MIB. Este comando está disponible en cualquier nodo StorageGRID.



== Contenido del archivo MIB

Todos los objetos están bajo el OID de StorageGRID.

[cols="1a,1a,2a"]
|===
| Nombre del objeto | ID Objeto (OID) | Descripción 


| .iso.org.dod.internet. + private.enterprises. + netapp.storagegrid | .1.3.6.1.4.1.789.28669  a| 
Módulo MIB para entidades de NetApp StorageGRID.

|===


== Objetos MIB

[cols="1a,1a,2a"]
|===
| Nombre del objeto | ID Objeto (OID) | Descripción 


| Active AlertCount | .1,3.6,1.4,1. + 789.28669.1.3  a| 
El número de alertas activas en activeAlertTable.



| Active AlertTable | .1,3.6,1.4,1. + 789.28669.1.4  a| 
Una tabla de alertas activas en StorageGRID.



| Active AlertId | .1,3.6,1.4,1. + 789.28669.1.4.1.1  a| 
El ID de la alerta. Solo es único en el conjunto actual de alertas activas.



| Active AlertName | .1,3.6,1.4,1. + 789.28669.1.4.1.2  a| 
El nombre de la alerta.



| Active AlertInstance | .1,3.6,1.4,1. + 789.28669.1.4.1.3  a| 
El nombre de la entidad que generó la alerta, generalmente el nombre del nodo.



| Active AlertSeverity | .1,3.6,1.4,1. + 789.28669.1.4.1.4  a| 
La gravedad de la alerta.



| Active AlertStartTime | .1,3.6,1.4,1. + 789.28669.1.4.1.5  a| 
La fecha y la hora en la que se activó la alerta.

|===


== Tipos de notificación (retos)

Todas las notificaciones incluyen las siguientes variables como varbinds:

* Active AlertId
* Active AlertName
* Active AlertInstance
* Active AlertSeverity
* Active AlertStartTime


[cols="1a,1a,2a"]
|===
| Tipo de notificación | ID Objeto (OID) | Descripción 


| ActiveMinorAlert | .1,3.6,1.4,1. + 789.28669.0.6  a| 
Una alerta de gravedad menor



| Active MajorAlert | .1,3.6,1.4,1. + 789.28669.0.7  a| 
Una alerta de gravedad importante



| ActiveCriticalAlert | .1,3.6,1.4,1. + 789.28669.0.8  a| 
Una alerta con gravedad crítica

|===