---
permalink: monitor/autosupport-package-failure-handling.html 
sidebar: sidebar 
keywords: troubleshoot autosupport, asup package 
summary: Consulta la lista de acciones que realiza StorageGRID si falla un intento de enviar un paquete AutoSupport. 
---
= Cómo gestiona StorageGRID los errores de paquetes de AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Consulta la lista de acciones que realiza StorageGRID si falla un intento de enviar un paquete AutoSupport.

StorageGRID realiza diferentes acciones en función del tipo de paquete AutoSupport. Puedes comprobar el estado de los paquetes AutoSupport seleccionando *Soporte* > *Herramientas* > *AutoSupport* > *Resultados*.

Cuando el paquete AutoSupport no se envía, aparece “Failure” en la pestaña *Results* de la página *AutoSupport*.


NOTE: Si has configurado un servidor proxy para redirigir los paquetes de AutoSupport a NetApp, link:../admin/configuring-admin-proxy-settings.html["compruebe que los valores de configuración del servidor proxy son correctos"].



[[weekly-autosupport-package-failure]]
== Fallo del paquete AutoSupport semanal

Si no se puede enviar un paquete AutoSupport semanal, el sistema StorageGRID realiza las siguientes acciones:

. Actualiza el atributo de resultado más reciente a Reintentando.
. Intenta reenviar el paquete AutoSupport 15 veces cada cuatro minutos durante una hora.
. Después de una hora de errores de envío, actualiza el atributo de resultado más reciente a error.
. Intenta enviar un paquete de AutoSupport de nuevo a la siguiente hora programada.
. Mantiene la programación regular de AutoSupport si el paquete falla porque el servicio NMS no está disponible y si un paquete se envía antes de que pasen los siete días.
. Cuando el servicio NMS vuelve a estar disponible, envía un paquete AutoSupport inmediatamente si un paquete no se ha enviado durante siete días o más.




[[user-triggered-or-event-triggered-autosupport-package-failure]]
== Error del paquete AutoSupport activado por el usuario o activado por un evento

Si no se envía un paquete de AutoSupport activado por el usuario o activado por un evento, el sistema StorageGRID realiza las siguientes acciones:

. Muestra un mensaje de error si se conoce el error. Por ejemplo, si un usuario selecciona el protocolo SMTP sin proporcionar la configuración de correo electrónico correcta, se muestra el siguiente error: `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`
. No intenta enviar el paquete de nuevo.
. Registra el error en `nms.log`.


Si se produce un error y el protocolo seleccionado es SMTP, es posible que aparezca el siguiente mensaje de error en la página AutoSupport: `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`

Aprenda a link:../monitor/email-alert-notifications.html["configure los ajustes del servidor de correo electrónico"].



[[correct-an-autosupport-package-failure]]
== Corrija un error de paquete AutoSupport

Si se produce un error y el protocolo seleccionado es SMTP, comprueba que el servidor de correo electrónico del sistema StorageGRID esté correctamente configurado y que tu servidor de correo electrónico esté en funcionamiento. Es posible que aparezca el siguiente mensaje de error en la página AutoSupport: AutoSupport no se pueden enviar paquetes mediante el protocolo SMTP debido a una configuración incorrecta en la página Servidor de correo electrónico.
