---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Puede recuperar archivos de registro y datos del sistema de StorageGRID , incluidos los datos de configuración, y enviarlos al soporte técnico. 
---
= Recopilar archivos de registro y datos del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede recuperar archivos de registro y datos del sistema de StorageGRID , incluidos los datos de configuración, y enviarlos al soporte técnico.

.Antes de empezar
* Ha iniciado sesión en el Administrador de cuadrícula en cualquier nodo de administración mediante unlink:../admin/web-browser-requirements.html["navegador web compatible"] .
* Tienes link:../admin/admin-group-permissions.html["permisos de acceso específicos"].
* Tiene la clave de acceso de aprovisionamiento.


.Acerca de esta tarea
Utilice el Administrador de cuadrícula para recopilarlink:logs-files-reference.html["archivos de registro"] , datos del sistema y datos de configuración de cualquier nodo de la red durante el período de tiempo que seleccione.  Los datos se recopilan y archivan en un `.tar.gz` archivo que luego puede descargar a su computadora local o enviar al soporte técnico.

Opcionalmente, puede cambiar el destino de los registros de auditoría y enviar información de auditoría a un servidor syslog externo.  Los registros locales de registros de auditoría continúan generándose y almacenándose cuando se configura un servidor syslog externo. Ver link:../monitor/configure-log-management.html["Configurar la gestión de registros y el servidor syslog externo"] .

.Pasos
. Seleccione *Soporte* > *Herramientas* > *Recopilación de registros*.  Se muestra una tabla de nodos.
. Seleccione los nodos de grid para los que desea recoger archivos de registro.
+
Puede ordenar por nombre de nodo, sitio y tipo de nodo.  Las columnas de tipo de sitio y nodo contienen filtros para seleccionar por sitios individuales y tipos de nodo.

. Seleccione *continuar*.
. Seleccione el rango de fecha y hora de los datos que se incluirán en los archivos de registro.
+
Si selecciona un período de tiempo muy largo o recopila registros de todos los nodos en una cuadrícula grande, el archivo de registros podría volverse demasiado grande para almacenarse en un nodo o demasiado grande para que un nodo de administración lo recopile para descargarlo.  Si ocurre cualquiera de los escenarios, reinicie la recopilación de registros con un conjunto de datos más pequeño.

. Seleccione los tipos de registros que desea recoger.
+
** *Registros de aplicaciones*: registros específicos de la aplicación que el soporte técnico utiliza con mayor frecuencia para solucionar problemas.  Los registros recopilados son un subconjunto de los registros de aplicaciones disponibles.
** *Registros de auditoría*: Registros que contienen los mensajes de auditoría generados durante el funcionamiento normal del sistema.
** *Rastreo de red*: registros utilizados para la depuración de red.
** *Base de datos Prometheus*: métricas de series temporales de los servicios en todos los nodos.


. Opcionalmente, utilice el cuadro de texto *Notas* para ingresar notas sobre los archivos de registro que está recopilando.
+
Puede usar estas notas para brindar información de soporte técnico acerca del problema que le pidió que recopile los archivos de registro. Las notas se agregan a un archivo llamado `info.txt`, junto con otra información sobre la recopilación de archivos de registro.  `info.txt`El archivo se guarda en el paquete de archivo de registro.

. En el cuadro de texto *Frase de contraseña de aprovisionamiento*, ingrese la frase de contraseña de aprovisionamiento para su sistema StorageGRID .
. Seleccione *Recopilar registros*.
+
Puede utilizar la página de Recopilación de registros para supervisar el progreso de la recopilación de archivos de registro para cada nodo de la cuadrícula.

+
Si recibe un mensaje de error acerca del tamaño del registro, intente recopilar registros por un periodo más corto de tiempo o para menos nodos.

. Si falla la recopilación de registros:
+
** Si aparece el mensaje "Error en la recopilación de registros", puede volver a intentar la recopilación de registros o finalizar la sesión sin volver a intentarlo.
** Si aparece el mensaje "La recopilación de registros falló parcialmente", puede volver a intentar la recopilación de registros, finalizar la sesión, descargar el archivo de registro parcial o enviar el archivo de registro parcial a AutoSupport.


. Cuando se complete la recopilación de archivos de registro:
+
** Seleccione *Descargar* para descargar el `.tar.gz` archivo.
** Seleccione *Enviar a AutoSupport* para enviar el `.tar.gz` archivo al soporte técnico.
+
El `.tar.gz` El archivo contiene todos los archivos de registro de todos los nodos de la red donde la recopilación de registros fue exitosa.  El combinado `.tar.gz` El archivo contiene un archivo de registro para cada nodo de la red.

+
El tema del paquete AutoSupport es `USER_TRIGGERED_SUPPORT_BUNDLE` .



. Seleccione *Finalizar*.
+

CAUTION: El `.tar.gz` El archivo se elimina cuando selecciona *Finalizar*.  Asegúrese de descargar o enviar el archivo primero.


