---
permalink: monitor/collecting-log-files-and-system-data.html 
sidebar: sidebar 
keywords: how to collect system data, how to collect logs 
summary: Puede recuperar archivos de registro y datos del sistema de StorageGRID, incluidos los datos de configuración, y enviarlos al soporte técnico. 
---
= Recopilar archivos de registro y datos del sistema
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede recuperar archivos de registro y datos del sistema de StorageGRID, incluidos los datos de configuración, y enviarlos al soporte técnico.

.Antes de empezar
* Ha iniciado sesión en Grid Manager en el nodo de administración principal mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Tienes link:../admin/admin-group-permissions.html["permisos de acceso específicos"].
* Tiene la clave de acceso de aprovisionamiento.


.Acerca de esta tarea
Utilice Grid Manager para recopilar link:logs-files-reference.html["archivos de registro"], datos del sistema y datos de configuración de cualquier nodo de cuadrícula durante el período de tiempo seleccionado. Los datos se recogen y se archivan en `.tar.gz` un archivo que puede descargar en su equipo local o enviar al soporte técnico.

De manera opcional, se puede cambiar el destino de los registros de auditoría y enviar información de auditoría a un servidor de syslog externo. Se siguen generando y almacenando registros locales de registros de auditoría cuando se configura un servidor de syslog externo. Consulte link:../monitor/configure-audit-messages.html["Configure los mensajes de auditoría y el servidor de syslog externo"].

.Pasos
. Seleccione *SUPPORT* > *Tools* > *Logs*. Se muestra una tabla de nodos.
. Seleccione los nodos de grid para los que desea recoger archivos de registro.
+
Puede ordenar por nombre de nodo, sitio y tipo de nodo. Las columnas Site y Node Type contienen filtros para seleccionar por sitios y tipos de nodo individuales.

. Seleccione *continuar*.
. Seleccione el intervalo de fecha y hora de los datos que se incluirán en los archivos de registro.
+
Si selecciona un período de tiempo muy largo o recopila registros de todos los nodos de un grid grande, el archivo de registro puede ser demasiado grande para almacenarse en un nodo o demasiado grande para recogerlo en el nodo de administración principal para su descarga. Si se produce alguna de las situaciones, reinicie la recopilación de registros con un conjunto de datos más pequeño.

. Seleccione los tipos de registros que desea recoger.
+
** *Registros de aplicaciones*: Registros específicos de aplicaciones que el soporte técnico utiliza con más frecuencia para la resolución de problemas. Los registros recopilados son un subconjunto de los registros de aplicación disponibles.
** *Registros de auditoría*: Registros que contienen los mensajes de auditoría generados durante el funcionamiento normal del sistema.
** *Rastreo de red*: Registros utilizados para la depuración de red.
** *Base de datos Prometheus*: Métricas de series temporales de los servicios en todos los nodos.


. Opcionalmente, use el cuadro de texto *Notas* para ingresar notas sobre los archivos de registro que está recopilando.
+
Puede usar estas notas para brindar información de soporte técnico acerca del problema que le pidió que recopile los archivos de registro. Las notas se agregan a un archivo llamado `info.txt`, junto con otra información sobre la recopilación de archivos de registro.  `info.txt`El archivo se guarda en el paquete de archivo de registro.

. En el cuadro de texto *Provisionar frase de contraseña*, ingrese la frase de contraseña de aprovisionamiento para su sistema StorageGRID.
. Selecciona *Recoger registros*.
+
Puede utilizar la página Logs para supervisar el progreso de la recopilación de archivos de registro de cada nodo de cuadrícula.

+
Si recibe un mensaje de error acerca del tamaño del registro, intente recopilar registros por un periodo más corto de tiempo o para menos nodos.

. Si la recopilación de registros falla:
+
** Si aparece un mensaje que indica que la recopilación de registros ha fallado, puede volver a intentar la recopilación de registros o finalizar la sesión sin volver a intentarlo.
** Si aparece un mensaje que indica que la recopilación de registros ha fallado parcialmente, puede volver a intentar la recopilación de registros, finalizar la sesión, descargar el archivo de registro parcial o enviar el archivo de registro parcial a AutoSupport.


. Cuando se complete la recopilación de archivos log:
+
** Seleccione *Descargar* para descargar el `.tar.gz` archivo.
** Seleccione *Enviar a AutoSupport* para enviar el `.tar.gz` archivo al soporte técnico.
+
El `.tar.gz` archivo contiene todos los archivos log de todos los nodos de cuadrícula en los que la recopilación de logs se ha realizado correctamente. El archivo combinado `.tar.gz` contiene un archivo de registro para cada nodo de cuadrícula.

+
El tema del paquete AutoSupport es `USER_TRIGGERED_SUPPORT_BUNDLE`.



. Seleccione *Finalizar*.
+

CAUTION: El `.tar.gz` archivo se elimina al seleccionar *Finalizar*. Asegúrese de descargar o enviar el archivo primero.


