---
permalink: monitor/configure-log-management.html 
sidebar: sidebar 
keywords: log management, audit level, external syslog server, log destinations 
summary: Según sea necesario, configure los niveles de auditoría, los encabezados de protocolo y la ubicación de los mensajes y registros de auditoría. 
---
= Configurar la gestión de registros
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Según sea necesario, configure los niveles de auditoría, los encabezados de protocolo y la ubicación de los mensajes y registros de auditoría.

Todos los nodos de StorageGRID generan mensajes de auditoría y registros para rastrear la actividad y los eventos del sistema.  Los mensajes y registros de auditoría son herramientas esenciales para la supervisión y la solución de problemas.

Opcionalmente, puedeslink:../monitor/considerations-for-external-syslog-server.html["configurar un servidor syslog externo"] para guardar información de auditoría de forma remota.  El uso de un servidor externo minimiza el impacto en el rendimiento del registro de mensajes de auditoría sin reducir la integridad de los datos de auditoría.  Un servidor syslog externo es especialmente útil si tiene una red grande, utiliza múltiples tipos de aplicaciones S3 o desea conservar todos los datos de auditoría.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:../admin/admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"].
* Si planea configurar un servidor syslog externo, ha revisado y seguido laslink:../monitor/considerations-for-external-syslog-server.html["consideraciones que tener en cuenta sobre el uso de un servidor de syslog externo"] .
* Si planea configurar un servidor de syslog externo con el protocolo TLS o RELP/TLS, tendrá los certificados de CA de servidor y de cliente requeridos, así como la clave privada de cliente.




== Cambiar los niveles de mensajes de auditoría

Se puede establecer un nivel de auditoría diferente para cada una de las siguientes categorías de mensajes en el registro de auditoría:

[cols="1a,1a,1a"]
|===
| Categoría de auditoría | Configuración predeterminada | Más información 


 a| 
Sistema
 a| 
Normal
 a| 
link:../audit/system-audit-messages.html["Mensajes de auditoría del sistema"]



 a| 
Reducida
 a| 
Error
 a| 
link:../audit/object-storage-audit-messages.html["Mensajes de auditoría del almacenamiento de objetos"]



 a| 
Gestión
 a| 
Normal
 a| 
link:../audit/management-audit-message.html["Mensaje de auditoría de gestión"]



 a| 
El cliente lee
 a| 
Normal
 a| 
link:../audit/client-read-audit-messages.html["El cliente lee los mensajes de auditoría"]



 a| 
Escrituras del cliente
 a| 
Normal
 a| 
link:../audit/client-write-audit-messages.html["El cliente escribe mensajes de auditoría"]



 a| 
ILM
 a| 
Normal
 a| 
link:../audit/ilm-audit-messages.html["Mensajes de auditoría de ILM"]



 a| 
Replicación entre grid
 a| 
Error
 a| 
link:../audit/cgrr-cross-grid-replication-request.html["CGRR: Solicitud de Replicación de Cuadrícula Cruzada"]

|===

NOTE: Durante las actualizaciones, las configuraciones de nivel de auditoría no serán efectivas de inmediato.

.Pasos
. Seleccione *Configuración* > *Monitoreo* > *Administración de registros*.
. Para cada categoría de mensaje de auditoría, seleccione un nivel de auditoría de la lista desplegable:
+
[cols="1a,3a"]
|===
| Nivel de auditoría | Descripción 


 a| 
Apagado
 a| 
No se registran mensajes de auditoría de la categoría.



 a| 
Error
 a| 
Sólo se registran los mensajes de error: mensajes de auditoría para los cuales el código de resultado no fue "exitoso" (SUCS).



 a| 
Normal
 a| 
Se registran los mensajes transaccionales estándar: Los mensajes que aparecen en estas instrucciones para la categoría.



 a| 
Depurar
 a| 
Obsoleto. Este nivel se comporta como el nivel de auditoría normal.

|===
+
Los mensajes incluidos para cualquier nivel particular incluyen los que se registrarán en los niveles superiores. Por ejemplo, el nivel normal incluye todos los mensajes de error.

+

NOTE: Si no necesita un registro detallado de las operaciones de lectura del cliente para sus aplicaciones S3, cambie opcionalmente la configuración *Lecturas del cliente* a *Error* para disminuir la cantidad de mensajes de auditoría registrados en el registro de auditoría.

. Seleccione *Guardar*.




== Definir cabeceras de solicitud HTTP

Opcionalmente, puede definir cualquier encabezado de solicitud HTTP que desee incluir en los mensajes de auditoría de lectura y escritura del cliente.

.Pasos
. En la sección *Cabeceras de protocolo de auditoría*, defina los encabezados de solicitud HTTP que desea incluir en los mensajes de auditoría de lectura y escritura del cliente.
+
Utilice un asterisco (\*) como comodín para que coincida con cero o más caracteres. Utilice la secuencia de escape (\*) para que coincida con un asterisco literal.

. Seleccione *Agregar otro encabezado* para crear encabezados adicionales, si es necesario.
+
Cuando se encuentran encabezados HTTP en una solicitud, se incluyen en el mensaje de auditoría en el campo HTRH.

+

NOTE: Los encabezados de solicitud de protocolo de auditoría se registran solo si el nivel de auditoría para *Lecturas de cliente* o *Escrituras de cliente* no está *Desactivado*.

. Seleccione *Guardar*




== Configurar la ubicación del registro

De forma predeterminada, los mensajes de auditoría y los registros se guardan en los nodos donde se generan.  Se rotan periódicamente y finalmente se eliminan para evitar que consuman demasiado espacio en disco.  Si desea guardar mensajes de auditoría y un subconjunto de registros de forma externa,<<use-external-syslog-server,utilizar un servidor syslog externo>> .

Si desea guardar los archivos de registro internamente, elija un inquilino y un depósito para el almacenamiento de registros y habilite el archivado de registros.



=== [[use-external-syslog-server]]Utilice un servidor syslog externo

De manera opcional, es posible configurar un servidor de syslog externo para guardar registros de auditoría, registros de aplicaciones y registros de eventos de seguridad en una ubicación fuera del grid.


NOTE: Si no desea utilizar un servidor syslog externo, omita este paso y vaya a<<select-log-location,Seleccionar la ubicación del registro>> .


TIP: Si las opciones de configuración disponibles en este procedimiento no son lo suficientemente flexibles para satisfacer sus requisitos, se pueden aplicar opciones de configuración adicionales mediante los `audit-destinations` puntos finales, que se encuentran en la sección API privada de link:../admin/using-grid-management-api.html["API de gestión de grid"]. Por ejemplo, puede usar la API si desea usar diferentes servidores de syslog para diferentes grupos de nodos.



==== Introduzca la información de syslog

Acceda al asistente Configurar servidor de syslog externo y proporcione la información que StorageGRID necesita para acceder al servidor de syslog externo.

.Pasos
. Desde la pestaña Nodo local y servidor externo, seleccione *Configurar servidor syslog externo*.  O bien, si ha configurado previamente un servidor syslog externo, seleccione *Editar servidor syslog externo*.
+
Aparece el asistente Configurar servidor de syslog externo.

. Para el paso *Enter syslog info* del asistente, introduzca un nombre de dominio completo válido o una dirección IPv4 o IPv6 para el servidor syslog externo en el campo *Host*.
. Introduzca el puerto de destino en el servidor de syslog externo (debe ser un entero entre 1 y 65535). El puerto predeterminado es 514.
. Seleccione el protocolo utilizado para enviar información de auditoría al servidor de syslog externo.
+
Se recomienda usar *TLS* o *RELP/TLS*. Debe cargar un certificado de servidor para usar cualquiera de estas opciones. El uso de certificados ayuda a proteger las conexiones entre el grid y el servidor de syslog externo. Para obtener más información, consulte link:../admin/using-storagegrid-security-certificates.html["Gestionar certificados de seguridad"].

+
Todas las opciones de protocolo requieren compatibilidad con el servidor de syslog externo y su configuración. Debe elegir una opción que sea compatible con el servidor de syslog externo.

+

NOTE: El protocolo de registro de eventos fiable (RELP) amplía la funcionalidad del protocolo syslog para proporcionar una entrega fiable de los mensajes de eventos. El uso de RELP puede ayudar a evitar la pérdida de información de auditoría si el servidor syslog externo tiene que reiniciarse.

. Seleccione *continuar*.
. [[attach-certificate]]Si seleccionó *TLS* o *RELP/TLS*, cargue los certificados de CA del servidor, el certificado de cliente y la clave privada del cliente.
+
.. Seleccione *Buscar* para el certificado o la clave que desee utilizar.
.. Seleccione el certificado o el archivo de claves.
.. Seleccione *Abrir* para cargar el archivo.
+
Aparece una comprobación verde junto al certificado o el nombre del archivo de claves, notificándole que se ha cargado correctamente.



. Seleccione *continuar*.




==== Permite gestionar el contenido de syslog

Puede seleccionar la información que desea enviar al servidor de syslog externo.

.Pasos
. Para el paso *Administrar contenido syslog* del asistente, seleccione cada tipo de información de auditoría que desee enviar al servidor syslog externo.
+
** *Enviar registros de auditoría*: Envía eventos StorageGRID y actividades del sistema
** *Enviar eventos de seguridad*: Envía eventos de seguridad como cuando un usuario no autorizado intenta iniciar sesión o un usuario inicia sesión como root
** *Enviar registros de aplicaciones*: Envía link:../monitor/storagegrid-software-logs.html["Archivos de registro del software de StorageGRID"] útiles para la solución de problemas, incluyendo:
+
*** `bycast-err.log`
*** `bycast.log`
*** `jaeger.log`
*** `nms.log` (Solo nodos de administración)
*** `prometheus.log`
*** `raft.log`
*** `hagroups.log`


** *Enviar registros de acceso*: Envía registros de acceso HTTP para solicitudes externas a Grid Manager, Tenant Manager, endpoints de equilibrio de carga configurados y solicitudes de federación de grid desde sistemas remotos.


. Utilice los menús desplegables para seleccionar la gravedad y la utilidad (tipo de mensaje) para cada categoría de información de auditoría que desee enviar.
+
La definición de valores de gravedad y de utilidad puede ayudarle a agregar los registros de formas personalizables para facilitar el análisis.

+
.. Para *Gravedad*, selecciona *Passthrough*, o selecciona un valor de gravedad entre 0 y 7.
+
Si selecciona un valor, el valor seleccionado se aplicará a todos los mensajes de este tipo. La información sobre diferentes gravedades se perderá si se sustituye la gravedad por un valor fijo.

+
[cols="1a,3a"]
|===
| Gravedad | Descripción 


 a| 
Paso a través
 a| 
Cada mensaje enviado al syslog externo para tener el mismo valor de gravedad que cuando se registró localmente en el nodo:

*** Para los registros de auditoría, la gravedad es «info».
*** Para eventos de seguridad, los valores de gravedad se generan en la distribución de Linux en los nodos.
*** Para los registros de aplicaciones, las gravedades varían entre “info” y “notice”, dependiendo de cuál sea el problema. Por ejemplo, agregar un servidor NTP y configurar un grupo de alta disponibilidad proporciona un valor de «info», mientras que detener intencionalmente el servicio SSM o RSM proporciona un valor de «notice».
*** Para los registros de acceso, la gravedad es «info».




 a| 
0
 a| 
Emergencia: El sistema no se puede utilizar



 a| 
1
 a| 
Alerta: La acción se debe realizar de inmediato



 a| 
2
 a| 
Crítico: Condiciones críticas



 a| 
3
 a| 
Error: Condiciones de error



 a| 
4
 a| 
Advertencia: Condiciones de aviso



 a| 
5
 a| 
Aviso: Condición normal pero significativa



 a| 
6
 a| 
Informativo: Mensajes informativos



 a| 
7
 a| 
Debug: Mensajes de nivel de depuración

|===
.. Para *Facilty*, selecciona *Passthrough*, o selecciona un valor entre 0 y 23.
+
Si selecciona un valor, se aplicará a todos los mensajes de este tipo. La información sobre las diferentes instalaciones se perderá si se sustituye la instalación por un valor fijo.

+
[cols="1a,3a"]
|===
| Centro | Descripción 


 a| 
Paso a través
 a| 
Cada mensaje enviado al syslog externo para tener el mismo valor de instalación que cuando se registró localmente en el nodo:

*** Para los registros de auditoría, la instalación enviada al servidor de syslog externo es «local7».
*** Para los eventos de seguridad, los valores de las instalaciones se generan mediante la distribución de linux en los nodos.
*** Para los registros de aplicaciones, los registros de aplicaciones enviados al servidor syslog externo tienen los siguientes valores de utilidad:
+
**** `bycast.log`: usuario o daemon
**** `bycast-err.log`: usuario, daemon, local3 o local4
**** `jaeger.log`: local2
**** `nms.log`: local3
**** `prometheus.log`: local4
**** `raft.log`: local5
**** `hagroups.log`: local6


*** Para los registros de acceso, la instalación enviada al servidor syslog externo es “local0”.




 a| 
0
 a| 
kern (mensajes del núcleo)



 a| 
1
 a| 
usuario (mensajes de usuario)



 a| 
2
 a| 
correo



 a| 
3
 a| 
daemon (daemons del sistema)



 a| 
4
 a| 
auth (mensajes de seguridad/autorización)



 a| 
5
 a| 
syslog (mensajes generados internamente por syslogd)



 a| 
6
 a| 
lpr (subsistema de impresora de líneas)



 a| 
7
 a| 
noticias (subsistema de noticias de red)



 a| 
8
 a| 
UCP



 a| 
9
 a| 
cron (daemon de reloj)



 a| 
10
 a| 
seguridad (mensajes de seguridad/autorización)



 a| 
11
 a| 
FTP



 a| 
12
 a| 
NTP



 a| 
13
 a| 
auditoría de registro (auditoría de registros)



 a| 
14
 a| 
alerta de registro (alerta de registro)



 a| 
15
 a| 
reloj (daemon de reloj)



 a| 
16
 a| 
local0



 a| 
17
 a| 
local1



 a| 
18
 a| 
local2



 a| 
19
 a| 
local3



 a| 
20
 a| 
local4



 a| 
21
 a| 
local5



 a| 
22
 a| 
local6



 a| 
23
 a| 
local7

|===


. Seleccione *continuar*.




==== Enviar mensajes de prueba

Antes de iniciar el uso de un servidor de syslog externo, debe solicitar que todos los nodos de la cuadrícula envíen mensajes de prueba al servidor de syslog externo. Se deben usar estos mensajes de prueba para ayudar a validar toda la infraestructura de recogida de registros antes de comprometerse a enviar datos al servidor de syslog externo.


CAUTION: No use la configuración del servidor de syslog externo hasta que confirme que el servidor de syslog externo recibió un mensaje de prueba de cada nodo del grid y que el mensaje se procesó como se esperaba.

.Pasos
. Si no desea enviar mensajes de prueba porque está seguro de que su servidor syslog externo está configurado correctamente y puede recibir información de auditoría de todos los nodos de la cuadrícula, seleccione *Omitir y finalizar*.
+
Un banner verde indica que se ha guardado la configuración.

. De lo contrario, seleccione *Enviar mensajes de prueba* (recomendado).
+
Los resultados de la prueba aparecen continuamente en la página hasta que se detiene la prueba. Mientras la prueba está en curso, los mensajes de auditoría siguen enviarse a los destinos configurados anteriormente.

. Si recibe algún error durante la configuración del servidor syslog o en el tiempo de ejecución, corríjalo y seleccione *Enviar mensajes de prueba* nuevamente.
+
Consulte link:../troubleshoot/troubleshooting-syslog-server.html["Solucione problemas de un servidor de syslog externo"] para ayudarle a resolver cualquier error.

. Espere hasta que vea un banner verde que indica que todos los nodos han superado la prueba.
. Compruebe el servidor de syslog para determinar si se reciben y procesan los mensajes de prueba según lo esperado.
+

NOTE: Si está utilizando UDP, verifique toda su infraestructura de recopilación de registros.  El protocolo UDP no permite una detección de errores tan rigurosa como los otros protocolos.

. Seleccione *Detener y finalizar*.
+
Volverá a la página *Audit and syslog Server*. Un banner de color verde indica que se guardó la configuración del servidor de syslog.

+

NOTE: La información de auditoría de StorageGRID no se envía al servidor syslog externo hasta que seleccione un destino que incluya el servidor syslog externo.





=== Seleccionar la ubicación del registro

Puede especificar dónde se guardan los registros de auditoría y los registros de eventos de seguridad.link:../monitor/storagegrid-software-logs.html["Registros de aplicaciones de StorageGRID"] , y se envían registros de acceso.

[NOTE]
====
StorageGRID toma por defecto los destinos de auditoría de nodo local y almacena la información de auditoría en `/var/local/log/localaudit.log`.

Al utilizar `/var/local/log/localaudit.log`, las entradas del registro de auditoría de Grid Manager y Tenant Manager se pueden enviar a un nodo de almacenamiento. Puede encontrar el nodo que tiene las entradas más recientes mediante `run-each-node --parallel "zgrep MGAU /var/local/log/localaudit.log | tail"` el comando.

Algunos destinos solo están disponibles si se configuró un servidor de syslog externo.

====
.Pasos
. Seleccione *Ubicación del registro* > *Nodo local y servidor externo*.
. Para cambiar la ubicación del registro para los tipos de registro, seleccione una opción diferente.
+

TIP: *Solo nodos locales* y *Servidor syslog externo* típicamente proporcionan un mejor rendimiento.

+
[cols="1a,2a"]
|===
| Opción | Descripción 


 a| 
Sólo Nodos Locales (valor por defecto)
 a| 
Los mensajes de auditoría, los registros de eventos de seguridad y los registros de aplicaciones no se envían a los nodos de administración.  En cambio, se guardan únicamente en los nodos que los generaron ("el nodo local").  La información de auditoría generada en cada nodo local se almacena en `/var/local/log/localaudit.log` .

*Nota*: StorageGRID elimina periódicamente los registros locales en una rotación para liberar espacio.  Cuando el archivo de registro de un nodo alcanza 1 GB, se guarda el archivo existente y se inicia un nuevo archivo de registro.  El límite de rotación del registro es de 21 archivos.  Cuando se crea la versión 22 del archivo de registro, se elimina el archivo de registro más antiguo.  En promedio, se almacenan alrededor de 20 GB de datos de registro en cada nodo.  Para almacenar registros durante un período de tiempo prolongado,<<use-bucket,Utilice un inquilino y un depósito para el almacenamiento de registros>> .



 a| 
Nodos de administración/nodos locales
 a| 
Los mensajes de auditoría se envían al registro de auditoría en los nodos de administración, y los registros de eventos de seguridad y los registros de aplicaciones se almacenan en los nodos que los generaron. La información de auditoría se almacena en los siguientes archivos:

** Nodos de administración (principales y no principales): `/var/local/audit/export/audit.log`
** Todos los nodos: El `/var/local/log/localaudit.log` archivo suele estar vacío o faltar. Puede contener información secundaria, como una copia adicional de algunos mensajes.




 a| 
Servidor de syslog externo
 a| 
La información de auditoría se envía a un servidor syslog externo y se guarda en los nodos locales(`/var/local/log/localaudit.log` ).  El tipo de información enviada depende de cómo haya configurado el servidor syslog externo.  Esta opción se habilita solo después de haber<<use-external-syslog-server,configuró un servidor syslog externo>> .



 a| 
Nodos de administración y servidor syslog externo
 a| 
Los mensajes de auditoría se envían al registro de auditoría.(`/var/local/audit/export/audit.log` ) en los nodos de administración y la información de auditoría se envía al servidor syslog externo y se guarda en el nodo local(`/var/local/log/localaudit.log` ).  El tipo de información enviada depende de cómo haya configurado el servidor syslog externo.  Esta opción se habilita solo después de haber<<use-external-syslog-server,configuró un servidor syslog externo>> .

|===
. Seleccione *Guardar*.
+
Aparecerá un mensaje de advertencia.

. Seleccione *OK* para confirmar que desea cambiar el destino para la información de auditoría.
+
Los nuevos registros se envían a los destinos seleccionados. Los registros existentes permanecen en su ubicación actual.





=== [[use-bucket]]Usa un cubo

Los registros se rotan periódicamente.  Utilice un bucket S3 en la misma red para almacenar registros durante un período de tiempo prolongado.

. Seleccione *Ubicación del registro* > *Usar un depósito*.
. Seleccione la casilla de verificación *Habilitar registros de archivo*.
. Si el inquilino y el depósito enumerados no son los que desea utilizar, seleccione *Cambiar inquilino y depósito* y luego seleccione *Crear inquilino y depósito* o *Seleccionar inquilino y depósito*.
+
[role="tabbed-block"]
====
.Crear inquilino y depósito
--
.. Introduzca un nuevo nombre de inquilino.
.. Ingrese y confirme una contraseña para el nuevo inquilino.
.. Introduzca un nuevo nombre de depósito.
.. Seleccione *Crear y habilitar*.


--
.Seleccione tenant and bucket
--
.. Seleccione un nombre de inquilino del menú desplegable.
.. Seleccione un depósito del menú desplegable.
.. Seleccione *Seleccionar y habilitar*.


--
====


. Seleccione *Guardar*.
+
Los registros se almacenarán en el inquilino y en el depósito que usted especifique.  El nombre de la clave del objeto para los registros tiene este formato:

+
[listing]
----
system-logs/{node_hostname}/{absolute_path_to_log_file_on_node}--{last_modified_time}.gz
----
+
Por ejemplo:

+
[listing]
----
system-logs/DC1-SN1/var/local/log/localaudit.log--2025-05-12_13:41:44.gz
----

