---
permalink: monitor/using-task-tab.html 
sidebar: sidebar 
keywords: Tasks tab, rename node, reboot node, storage state, maintenance mode 
summary: La pestaña Tareas se muestra para todos los nodos. Puede usar esta pestaña para cambiar el nombre de un nodo o reiniciarlo, o para poner un nodo de dispositivo en modo de mantenimiento. En el caso de los nodos de almacenamiento, puede establecer el estado de almacenamiento. 
---
= Utilice la pestaña Tareas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pestaña Tareas se muestra para todos los nodos. Puede usar esta pestaña para cambiar el nombre de un nodo o reiniciarlo, o para poner un nodo de dispositivo en modo de mantenimiento. En el caso de los nodos de almacenamiento, puede establecer el estado de almacenamiento.

Para conocer los requisitos e instrucciones completos para cada opción de esta pestaña, consulte lo siguiente:

* link:../maintain/rename-grid-site-node-overview.html["Cambie el nombre de cuadrícula, sitios y nodos"]
* link:../maintain/rebooting-grid-node-from-grid-manager.html["Reinicie el nodo de cuadrícula"]
* https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/placing-appliance-into-maintenance-mode.html["Coloque el dispositivo en modo de mantenimiento"^]
* Verifique o establezca el estado de almacenamiento de un nodo de almacenamiento después de añadir volúmenes SAN o de conexión directa al nodo de almacenamiento, o después de recuperar un nodo de almacenamiento. Esas instrucciones están disponibles en los temas que describen estas tareas.

