---
permalink: maintain/all-node-types-replacing-vmware-node.html 
sidebar: sidebar 
keywords: replace VMware node 
summary: Cuando se recupera un nodo StorageGRID con fallos que se encontraba en VMware, se elimina el nodo fallido y se implementa un nodo de recuperación. 
---
= Sustituya el nodo VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se recupera un nodo StorageGRID con fallos que se encontraba en VMware, se elimina el nodo fallido y se implementa un nodo de recuperación.

.Antes de empezar
Ha determinado que la máquina virtual no se puede restaurar y debe reemplazarse.

.Acerca de esta tarea
Se utiliza VMware vSphere Web Client para quitar primero la máquina virtual asociada con el nodo de grid que ha fallado. A continuación, puede implementar una nueva máquina virtual.

Este procedimiento es solo un paso del proceso de recuperación del nodo de cuadrícula. El procedimiento de eliminación y puesta en marcha de nodos es el mismo para todos los nodos de VMware, incluidos los nodos de administración, los nodos de almacenamiento y los nodos de pasarela.

.Pasos
. Inicie sesión en VMware vSphere Web Client.
. Acceda a la máquina virtual del nodo de grid donde se ha producido el error.
. Tome nota de toda la información necesaria para poner en marcha el nodo de recuperación.
+
.. Haga clic con el botón derecho del ratón en la máquina virtual, seleccione la ficha *Editar configuración* y anote la configuración en uso.
.. Seleccione la ficha *vApp Options* para ver y registrar la configuración de red del nodo de cuadrícula.


. Si el nodo de almacenamiento Grid en el que se ha producido el fallo es un nodo de almacenamiento, determine si alguno de los discos duros virtuales utilizados para el almacenamiento de datos no está dañado y conservarlos para volver a conectarlos al nodo de grid recuperado.
. Apague la máquina virtual.
. Seleccione *Acciones* > *Todas las acciones de vCenter* > *Eliminar del disco* para eliminar la máquina virtual.
. Implemente una nueva máquina virtual para que sea el nodo de reemplazo y conéctela a una o más redes StorageGRID .  Para obtener instrucciones, consultelink:../swnodes/deploying-storagegrid-node-as-virtual-machine.html["Poner en marcha un nodo de StorageGRID como máquina virtual"] .
+
Al poner en marcha el nodo, tiene la opción de reasignar puertos de nodo o aumentar las opciones de CPU o memoria.

+

NOTE: Después de implementar el nuevo nodo, puede agregar nuevos discos virtuales de acuerdo con sus requisitos de almacenamiento, volver a conectar los discos duros virtuales conservados desde el nodo de cuadrícula con error que se quitó anteriormente, o ambos.

. Complete el procedimiento de recuperación de nodos, según el tipo de nodo que se está recuperando.
+
[cols="1a,2a"]
|===
| Tipo de nodo | Vaya a. 


 a| 
Nodo de administrador principal
 a| 
link:configuring-replacement-primary-admin-node.html["Configure el nodo de administración principal de reemplazo"]



 a| 
Nodo de administrador no primario
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Seleccione Start Recovery para configurar el nodo de administrador que no es primario"]



 a| 
Nodo de puerta de enlace
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["Seleccione Start Recovery para configurar Gateway Node"]



 a| 
Nodo de almacenamiento
 a| 
link:selecting-start-recovery-to-configure-storage-node.html["Seleccione Start Recovery para configurar Storage Node"]

|===

