---
permalink: maintain/all-node-types-replacing-linux-node.html 
sidebar: sidebar 
keywords: replace linux node 
summary: Si un fallo requiere implementar uno o más hosts físicos o virtuales nuevos, o reinstalar Linux en un host existente, implemente y configure el host de reemplazo antes de poder recuperar el nodo de grid. Este procedimiento es un paso del proceso de recuperación de nodos de grid para todos los tipos de nodos de grid. 
---
= Sustituya el nodo Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un fallo requiere implementar uno o más hosts físicos o virtuales nuevos, o reinstalar Linux en un host existente, implemente y configure el host de reemplazo antes de poder recuperar el nodo de grid. Este procedimiento es un paso del proceso de recuperación de nodos de grid para todos los tipos de nodos de grid.

"Linux" se refiere a una implementación de Red Hat® Enterprise Linux® (RHEL), Ubuntu® o Debian®.  Para obtener una lista de las versiones compatibles, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] .

Este procedimiento sólo se realiza como un paso del proceso de recuperación de nodos de almacenamiento basados en software, nodos de administración primarios o no primarios, o nodos de puerta de enlace. Los pasos son idénticos independientemente del tipo de nodo de cuadrícula que se esté recuperando.

Si hay más de un nodo de grid alojado en un host físico o virtual Linux, es posible recuperar los nodos de grid en cualquier orden. Sin embargo, si se recupera primero un nodo de administración principal, si existe, impide que se cale el resto de nodos de grid, ya que intentan ponerse en contacto con el nodo de administración principal para registrarse para la recuperación.
