---
permalink: maintain/checking-storage-state-after-recovering-sga.html 
sidebar: sidebar 
keywords: storagegrid, recovery, node recovery, storage state 
summary: Después de recuperar un nodo de almacenamiento de dispositivo, debe comprobar que el estado deseado del nodo de almacenamiento del dispositivo está establecido en online y que el estado estará en línea de forma predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento. 
---
= Compruebe el estado de almacenamiento después de recuperar el nodo de almacenamiento del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de recuperar un nodo de almacenamiento de dispositivo, debe comprobar que el estado deseado del nodo de almacenamiento del dispositivo está establecido en online y que el estado estará en línea de forma predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* El nodo de almacenamiento se ha recuperado y se completó la recuperación de datos.


.Pasos
. Seleccione *Nodos* > *_Nodo de almacenamiento_* > *Tareas*.
. Si la lista desplegable *Estado de almacenamiento* está configurada en Solo lectura o Sin conexión, seleccione *En línea*.
. Seleccione *Guardar*.

