---
permalink: maintain/checking-data-repair-jobs.html 
sidebar: sidebar 
keywords: storagegrid, data repair 
summary: Antes de retirar un nodo de cuadrícula, debe confirmar que no hay ningún trabajo de reparación de datos activo. Si alguna reparación ha fallado, debe reiniciarla y dejar que se complete antes de realizar el procedimiento de retirada. 
---
= Revisa los trabajos de reparación de datos en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de desmantelar o expandir un nodo de red, debe confirmar que no haya trabajos de reparación de datos activos.  Si alguna reparación ha fallado, debe reiniciarla y dejar que se complete antes de realizar el procedimiento de desmantelamiento.

* Referirse alink:../expand/index.html["Tipos de expansión"] para obtener detalles sobre cómo expandir un nodo de la cuadrícula.
* Usa el Grid Manager para supervisar los procesos de restauración en curso y mostrar el historial de restauraciones. Consulta estos procedimientos:
+
** link:../maintain/restoring-object-data-to-storage-volume-for-appliance.html["Restaure datos de objetos al volumen de almacenamiento de dispositivo"]
** link:../maintain/restoring-object-data-to-storage-volume-where-system-drive-is-intact.html["Restaure los datos de objetos al volumen de almacenamiento donde la unidad del sistema esté intacta"]
** link:../maintain/restoring-object-data-to-storage-volume.html["Restauración de los datos de objetos en un volumen de almacenamiento (fallo de unidad de sistema)"]



