---
permalink: maintain/checking-storage-state-after-recovering-storage-volumes.html 
sidebar: sidebar 
keywords: storagegrid, storage volume recovery, storage state, storage volume 
summary: Después de recuperar los volúmenes de almacenamiento, debe comprobar que el estado deseado del nodo de almacenamiento está establecido en online y que el estado estará en línea de forma predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento. 
---
= Comprobar el estado del almacenamiento después de recuperar los volúmenes de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de recuperar los volúmenes de almacenamiento, debe comprobar que el estado deseado del nodo de almacenamiento está establecido en online y que el estado estará en línea de forma predeterminada cada vez que se reinicie el servidor del nodo de almacenamiento.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* El nodo de almacenamiento se ha recuperado y se completó la recuperación de datos.


.Pasos
. Seleccione *Nodos* > *_Nodo de almacenamiento_* > *Tareas*.
. Si la lista desplegable *Estado de almacenamiento* está configurada en Solo lectura o Sin conexión, seleccione *En línea*.
. Seleccione *Guardar*.

