---
permalink: maintain/convert-to-data-only-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, stop services, power down host, power off host 
summary: Para aumentar el rendimiento, puede convertir nodos de almacenamiento que no sean ADC más lentos en nodos de almacenamiento de solo datos. 
---
= Convertir un nodo de almacenamiento en un nodo solo de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para aumentar el rendimiento, puede convertir nodos de almacenamiento que no sean ADC más lentos en nodos de almacenamiento de solo datos.

El uso exclusivo de un nodo de almacenamiento para los datos puede ser lógico si los nodos de almacenamiento tienen diferentes características de rendimiento. Por ejemplo, para aumentar potencialmente el rendimiento, podría tener nodos de almacenamiento en disco giratorio de alta capacidad y solo de datos acompañados por nodos de almacenamiento de alto rendimiento solo de metadatos.

Además, es posible obtener más capacidad de metadatos eliminando los nodos bajos de RAM de Cassandra, lo que aumenta el límite de capacidad de metadatos por nodo. Consulte link:../admin/managing-object-metadata-storage.html["Gestione el almacenamiento de metadatos de objetos"].

Al instalar nodos de solo datos, la cuadrícula debe contener lo siguiente:

* Un mínimo de dos nodos de almacenamiento combinados o solo de datos por grid
* Al menos un nodo de almacenamiento combinado o solo de datos por sitio
* Un mínimo de tres nodos de almacenamiento combinados o solo de metadatos por sitio


.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"].
* El nodo de almacenamiento que desea convertir no contiene el servicio ADC o tiene link:../maintain/move-adc-service.html["Se ha movido el servicio ADC"]otro nodo.
* El nodo de almacenamiento no es un nodo solo de metadatos ni un nodo solo de datos.
* Hay suficiente espacio de metadatos en otros nodos del sitio para acomodar los metadatos que se migrarán del nodo de almacenamiento que se está convirtiendo.


.Acerca de esta tarea
Utilice este procedimiento para convertir uno o más nodos de almacenamiento combinados o de solo metadatos que no contienen el servicio ADC en nodos de solo datos. Los nodos de almacenamiento deben estar en el mismo sitio.

Además de convertir el nodo de almacenamiento, este procedimiento desinstala Cassandra del nodo. Todos los metadatos migrarán a nodos de almacenamiento combinados o solo de metadatos. Dependiendo de la cantidad de metadatos que necesite migrar, este procedimiento puede tardar hasta varios días por nodo en completarse.


TIP: Por lo general, puede convertir hasta 10 nodos a la vez si el uso de metadatos por nodo es inferior a 1 TB. Si el uso de metadatos por nodo supera los 1 TB, convierta hasta 5 nodos por procedimiento.

.Pasos
. Registre los ID de nodo de los nodos de almacenamiento no ADC que desea convertir.
. En la parte superior de Grid Manager, selecciona el icono de ayuda y selecciona *Documentación de API*.
. Seleccione *Ir a documentación privada de API*.
. Seleccione `POST /private/convert-to-data-only-node/start` la operación. Consulte link:../admin/using-grid-management-api.html#issue-api-requests["Emita solicitudes API"] si desea obtener más información.
+
Cada nodo se reiniciará durante el procedimiento.

. Puede utilizar `GET /private/convert-to-data-only-node` para supervisar el procedimiento. Si se producen errores, `POST /private/convert-to-data-only-node/retry` seleccione para volver a intentar el procedimiento.
. link:../maintain/downloading-recovery-package.html["Descargue un paquete de recuperación"] después de completar este procedimiento.

