---
permalink: maintain/gathering-required-materials-node-decom.html 
sidebar: sidebar 
keywords: storagegrid, node decommission, decommission 
summary: Antes de realizar un desmantelamiento de un nodo de cuadrícula, debe obtener la siguiente información. 
---
= Reúna los materiales necesarios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de realizar un desmantelamiento de un nodo de cuadrícula, debe obtener la siguiente información.

[cols="1a,2a"]
|===
| Elemento | Notas 


 a| 
Paquete de recuperación `.zip` archivo
 a| 
Usted debelink:downloading-recovery-package.html["Descargue el paquete de recuperación más reciente"] `.zip` archivo(`sgws-recovery-package-_id-revision_.zip` ).  Puede utilizar el archivo del paquete de recuperación para restaurar el sistema si ocurre una falla.



 a| 
`Passwords.txt` archivo
 a| 
Este archivo contiene las contraseñas necesarias para acceder a los nodos de la red en la línea de comandos y está incluido en el paquete de recuperación.



 a| 
Clave de acceso de aprovisionamiento
 a| 
La frase de contraseña se crea y documenta cuando se instala el sistema StorageGRID por primera vez. La clave de acceso de aprovisionamiento no está en `Passwords.txt` el archivo.



 a| 
Descripción de la topología del sistema StorageGRID antes de decomisionar
 a| 
Si está disponible, obtenga cualquier documentación que describa la topología actual del sistema.

|===
.Información relacionada
link:../admin/web-browser-requirements.html["Requisitos del navegador web"]
