---
permalink: maintain/modifying-dns-configuration-for-single-grid-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, dns, modify dns 
summary: En lugar de configurar el DNS globalmente para toda la implementación, puede ejecutar un script para configurar DNS de manera diferente para cada nodo de grid. 
---
= Modifique la configuración de DNS para un solo nodo de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En lugar de configurar el DNS globalmente para toda la implementación, puede ejecutar un script para configurar DNS de manera diferente para cada nodo de grid.

En general, debe utilizar la opción *Mantenimiento* > *Red* > *Servidores DNS* en el Administrador de Grid para configurar servidores DNS.  Utilice el siguiente script solo si necesita utilizar diferentes servidores DNS para diferentes nodos de la red.

.Pasos
. El acceso SSH externo está bloqueado de forma predeterminada.  Si es necesario,link:../admin/manage-external-ssh-access.html["permitir el acceso temporalmente"] .
. Inicie sesión en el nodo de administración principal:
+
.. Introduzca el siguiente comando: `ssh admin@_primary_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a raíz: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
+
Al iniciar sesión como root, la petición de datos cambia de `$` a `#`.

.. Añada la clave privada SSH al agente SSH. Introduzca: `ssh-add`
.. Introduzca la contraseña de acceso SSH que aparece en `Passwords.txt` el archivo.


. [[LOG_IN_TO_NODE]]Inicie sesión en el nodo que desea actualizar con una configuración de DNS personalizada: `ssh _node_IP_address_`
. Ejecute el script de configuración de DNS: `setup_resolv.rb.`
+
El script responde con la lista de comandos admitidos.

+
[listing]
----
Tool to modify external name servers

available commands:
  add search <domain>
               add a specified domain to search list
               e.g.> add search netapp.com
  remove search <domain>
               remove a specified domain from list
               e.g.> remove search netapp.com
  add nameserver <ip>
               add a specified IP address to the name server list
               e.g.> add nameserver 192.0.2.65
  remove nameserver <ip>
               remove a specified IP address from list
               e.g.> remove nameserver 192.0.2.65
  remove nameserver all
               remove all nameservers from list
  save         write configuration to disk and quit
  abort        quit without saving changes
  help         display this help message


Current list of name servers:
    192.0.2.64
Name servers inherited from global DNS configuration:
    192.0.2.126
    192.0.2.127
Current list of search entries:
    netapp.com

Enter command [`add search <domain>|remove search <domain>|add nameserver <ip>`]
              [`remove nameserver <ip>|remove nameserver all|save|abort|help`]
----
. Agregue la dirección IPv4 de un servidor que proporciona el servicio de nombre de dominio para la red: `add <nameserver IP_address>`
. Repita `add nameserver` el comando para agregar servidores de nombres.
. Siga las instrucciones que se le indiquen para otros comandos.
. Guarde los cambios y salga de la aplicación: `save`
. [[close_cmd_shell]]Cierre el shell de comandos en el servidor: `exit`
. Para cada nodo de cuadrícula, repita los pasos de <<log_in_to_node,inicie sesión en el nodo>> a <<close_cmd_shell,cierre del shell de comandos>>.
. Cuando ya no necesite un acceso sin contraseñas a otros servidores, quite la clave privada del agente SSH. Introduzca: `ssh-add -D`
. Si ha permitido el acceso SSH externo,link:../admin/manage-external-ssh-access.html["bloquear el acceso"] cuando haya terminado de modificar la configuración de DNS.

