---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'Puede supervisar el estado de los trabajos de reparación mediante `repair-data` el script de la línea de comandos.' 
---
= Supervisar trabajos de datos de reparación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar el estado de los trabajos de reparación mediante `repair-data` el script de la línea de comandos.

Entre ellos se incluyen trabajos iniciados manualmente o trabajos que StorageGRID inició automáticamente como parte de un procedimiento de retirada.


NOTE: Si ejecuta trabajos de restauración de volúmenes, link:../maintain/restoring-volume.html["Supervise el progreso y vea un historial de esos trabajos en Grid Manager"] en lugar de eso.

Monitoree el estado de `repair-data` los trabajos en función de si usa *datos replicados*, *datos con código de borrado (EC)*, o ambos.

[role="tabbed-block"]
====
.Datos replicados
--
* Para obtener un porcentaje de finalización estimado para la reparación replicada, agregue `show-replicated-repair-status` la opción al comando repair-data.
+
`repair-data show-replicated-repair-status`

* Para determinar si las reparaciones están completas:
+
.. Seleccione *NODES* > *_Storage Node que se está reparando_* > *ILM*.
.. Revise los atributos en la sección Evaluación. Una vez completadas las reparaciones, el atributo *esperando - todo* indica 0 objetos.


* Para supervisar la reparación con más detalle:
+
.. Selecciona *NODOS*.
.. Seleccione *_grid name_* > *ILM*.
.. Coloque el cursor sobre el gráfico de cola ILM para ver el valor del atributo *Tasa de exploración (objetos/seg)*, que es la velocidad a la que los objetos de la cuadrícula se escanean y se ponen en cola para ILM.
.. En la sección ILM Queue, observe los siguientes atributos:
+
*** *Período de escaneo - Estimado*: El tiempo estimado para completar una exploración completa de ILM de todos los objetos.
+
Un análisis completo no garantiza que ILM se haya aplicado a todos los objetos.

*** *Reparaciones intentadas*: El número total de operaciones de reparación de objetos para los datos replicados que se han intentado. Este número aumenta cada vez que un nodo de almacenamiento intenta reparar un objeto de riesgo alto. Si el Grid está ocupado, se da prioridad a las reparaciones de ILM de alto riesgo.
+
La misma reparación de objeto puede volver a incrementarse si la replicación ha fallado después de la reparación. + Estos atributos pueden ser útiles cuando está supervisando el progreso de la recuperación del volumen del nodo de almacenamiento. Si el número de reparaciones que se intentaron ha dejado de aumentar y se ha completado una exploración completa, es probable que la reparación haya finalizado.



.. Alternativamente, envíe una consulta de Prometheus para `storagegrid_ilm_scan_period_estimated_minutes` y. `storagegrid_ilm_repairs_attempted`




--
.Datos con código de borrado (EC)
--
Para supervisar la reparación de datos codificados mediante borrado y vuelva a intentar cualquier solicitud que pudiera haber fallado:

. Determine el estado de las reparaciones de datos codificadas por borrado:
+
** Seleccione *SUPPORT* > *Tools* > *Metrics* para ver el tiempo estimado hasta la finalización y el porcentaje de finalización del trabajo actual. A continuación, seleccione *EC Overview* en la sección Grafana. Consulte los paneles *tiempo estimado de trabajo de Grid EC hasta finalización* y *Porcentaje de trabajo de Grid EC completado*.
** Use este comando para ver el estado de una operación específica `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilice este comando para enumerar todas las reparaciones:
+
`repair-data show-ec-repair-status`

+
La salida muestra información, incluida `repair ID`, para todas las reparaciones que se estaban ejecutando anteriormente y actualmente.



. Si el resultado muestra que la operación de reparación falló, use `--repair-id` la opción para volver a intentar la reparación.
+
Este comando vuelve a intentar una reparación de nodo con fallos mediante el ID de reparación 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Este comando reintenta realizar una reparación de volumen con fallos mediante el ID de reparación 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====