---
permalink: maintain/monitor-repairs.html 
sidebar: sidebar 
keywords: restore replicated data, restore erasure-coded data, recover appliance storage node, recover storage volume 
summary: 'Puede supervisar el estado de los trabajos de reparación mediante `repair-data` el script de la línea de comandos.' 
---
= Supervisar trabajos de datos de reparación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede supervisar el estado de los trabajos de reparación mediante `repair-data` el script de la línea de comandos.

Entre ellos se incluyen trabajos iniciados manualmente o trabajos que StorageGRID inició automáticamente como parte de un procedimiento de retirada.


NOTE: Si ejecuta trabajos de restauración de volúmenes, link:../maintain/restoring-volume.html["Supervise el progreso y vea un historial de esos trabajos en Grid Manager"] en lugar de eso.

Monitoree el estado de `repair-data` los trabajos en función de si usa *datos replicados*, *datos con código de borrado (EC)*, o ambos.

[role="tabbed-block"]
====
.Datos replicados
--
* Para obtener un porcentaje de finalización estimado para la reparación replicada, agregue `show-replicated-repair-status` la opción al comando repair-data.
+
`repair-data show-replicated-repair-status`

* Para determinar si las reparaciones están completas:
+
.. Seleccione *NODES* > *_Storage Node que se está reparando_* > *ILM*.
.. Revise los atributos en la sección Evaluación. Una vez completadas las reparaciones, el atributo *esperando - todo* indica 0 objetos.


* Para supervisar la reparación con más detalle:
+
.. Seleccione *SUPPORT* > *Tools* > *Topología de cuadrícula*.
.. Seleccione *_grid_* > *_nodo de almacenamiento que se está reparando_* > *LDR* > *almacén de datos*.
.. Utilice una combinación de los siguientes atributos para determinar, como sea posible, si las reparaciones replicadas se han completado.
+

NOTE: Puede haber incoherencias en Cassandra y no se realiza un seguimiento de las reparaciones fallidas.

+
*** *Reparaciones intentadas (XRPA)*: Utilice este atributo para realizar un seguimiento del progreso de las reparaciones replicadas. Este atributo aumenta cada vez que un nodo de almacenamiento intenta reparar un objeto de alto riesgo. Cuando este atributo no aumenta durante un período más largo que el período de exploración actual (proporcionado por el atributo *período de exploración -- estimado*), significa que el análisis de ILM no encontró objetos de alto riesgo que necesitan ser reparados en ningún nodo.
+

NOTE: Los objetos de alto riesgo son objetos que corren el riesgo de perderse por completo. Esto no incluye objetos que no cumplen con la configuración de ILM.

*** *Período de exploración -- estimado (XSCM)*: Utilice este atributo para estimar cuándo se aplicará un cambio de directiva a objetos ingeridos previamente. Si el atributo *reparos intentados* no aumenta durante un período más largo que el período de adquisición actual, es probable que se realicen reparaciones replicadas. Tenga en cuenta que el período de adquisición puede cambiar. El atributo *período de exploración -- estimado (XSCM)* se aplica a toda la cuadrícula y es el máximo de todos los periodos de exploración de nodos. Puede consultar el historial de atributos *período de exploración -- Estimated* de la cuadrícula para determinar un intervalo de tiempo adecuado.






--
.Datos con código de borrado (EC)
--
Para supervisar la reparación de datos codificados mediante borrado y vuelva a intentar cualquier solicitud que pudiera haber fallado:

. Determine el estado de las reparaciones de datos codificadas por borrado:
+
** Seleccione *SUPPORT* > *Tools* > *Metrics* para ver el tiempo estimado hasta la finalización y el porcentaje de finalización del trabajo actual. A continuación, seleccione *EC Overview* en la sección Grafana. Consulte los paneles *tiempo estimado de trabajo de Grid EC hasta finalización* y *Porcentaje de trabajo de Grid EC completado*.
** Use este comando para ver el estado de una operación específica `repair-data`:
+
`repair-data show-ec-repair-status --repair-id repair ID`

** Utilice este comando para enumerar todas las reparaciones:
+
`repair-data show-ec-repair-status`

+
La salida muestra información, incluida `repair ID`, para todas las reparaciones que se estaban ejecutando anteriormente y actualmente.



. Si el resultado muestra que la operación de reparación falló, use `--repair-id` la opción para volver a intentar la reparación.
+
Este comando vuelve a intentar una reparación de nodo con fallos mediante el ID de reparación 6949309319275667690:

+
`repair-data start-ec-node-repair --repair-id 6949309319275667690`

+
Este comando reintenta realizar una reparación de volumen con fallos mediante el ID de reparación 6949309319275667690:

+
`repair-data start-ec-volume-repair --repair-id 6949309319275667690`



--
====