---
permalink: maintain/monitoring-services-appliance-installation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance 
summary: El instalador del dispositivo StorageGRID proporciona el estado hasta que se completa la instalación. Una vez finalizada la instalación del software, el dispositivo se reinicia. 
---
= Supervisar la instalación del dispositivo de servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El instalador del dispositivo StorageGRID proporciona el estado hasta que se completa la instalación. Una vez finalizada la instalación del software, el dispositivo se reinicia.

.Pasos
. Para supervisar el progreso de la instalación, haga clic en *instalación del monitor* en la barra de menús.
+
La página Monitor Installation (instalación del monitor) muestra el progreso de la instalación.

+
La barra de estado azul indica qué tarea está en curso actualmente. Las barras de estado verdes indican tareas que se han completado correctamente.

+

NOTE: Installer garantiza que las tareas completadas en una instalación anterior no se vuelvan a ejecutar. Si vuelve a ejecutar una instalación, las tareas que no necesitan volver a ejecutarse se muestran con una barra de estado verde y el estado “Omitida”.

. Revise el progreso de las dos primeras etapas de instalación.
+
** *1. Configurar almacenamiento*
+
Durante esta fase, el instalador borra toda la configuración existente de las unidades y configura la configuración del host.

** *2. Instalar OS*
+
Durante esta fase, el instalador copia la imagen del sistema operativo base para StorageGRID desde el nodo de administración principal al dispositivo o instala el sistema operativo base desde el paquete de instalación del nodo de administración principal.



. Continúe supervisando el progreso de la instalación hasta que se produzca una de las siguientes situaciones:
+
** Para los nodos de puerta de enlace del dispositivo o los nodos de administración de dispositivos no primarios, la etapa *instalar StorageGRID* se detiene y aparece un mensaje en la consola integrada, solicitándole que apruebe este nodo en el nodo de administración mediante el Administrador de grid.
** En el caso de los nodos de administración principales del dispositivo, aparece una quinta fase (Load StorageGRID Installer). Si la quinta fase está en curso durante más de 10 minutos, actualice la página manualmente.


. Vaya al siguiente paso del proceso de recuperación para el tipo de nodo de grid del dispositivo que está recuperando.
+
[cols="1a,2a"]
|===
| Tipo de recuperación | Referencia 


 a| 
Nodo de puerta de enlace
 a| 
link:selecting-start-recovery-to-configure-gateway-node.html["Seleccione Start Recovery para configurar Gateway Node"]



 a| 
Nodo de administrador no primario
 a| 
link:selecting-start-recovery-to-configure-non-primary-admin-node.html["Seleccione Start Recovery para configurar el nodo de administrador que no es primario"]



 a| 
Nodo de administrador principal
 a| 
link:configuring-replacement-primary-admin-node.html["Configure el nodo de administración principal de reemplazo"]

|===

