---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Puede mover el servicio ADC a otro nodo de almacenamiento del mismo sitio. 
---
= Mueva el servicio ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mover el servicio ADC a otro nodo de almacenamiento del mismo sitio.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Tienes link:admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"].
* El nodo de origen contiene el servicio ADC.
* El nodo de destino no contiene el servicio ADC.
* El nodo objetivo es un nodo solo de metadatos o combinado (metadatos y datos de objetos).
* El nodo de origen y el nodo de destino están en el mismo sitio.


.Acerca de esta tarea
Utilice el procedimiento Mover ADC cuando desee:

* Decomisionar un nodo de almacenamiento que contenga el servicio ADC
* Convierta un nodo ADC en un nodo de solo datos
* Agregue un nodo para ejecutar tareas relacionadas con ADC


Cuando desee retirar un nodo de almacenamiento o link:../maintain/convert-to-data-only-node.html["Convertir un nodo de almacenamiento en un nodo solo de datos"], primero, puede que necesite utilizar el procedimiento Mover ADC. Deberá asegurarse de que el link:../maintain/understanding-adc-service-quorum.html["Se mantiene el quórum ADC"].

Este procedimiento mueve los servicios ADC, IDNT, ACCT y RSM de un nodo de almacenamiento a otro en el mismo sitio. Los servicios RSM y ACCT dependen del servicio ADC, por lo que se mueven automáticamente cuando el servicio ADC se mueve.

.Pasos
. Registre los ID de nodo de los nodos de origen y destino.
+
En la API de gestión de grid, el identificador de nodo de origen se denomina `sourceNodeId` . El ID de nodo de destino se denomina `targetNodeId` .

. En la parte superior de Grid Manager, selecciona el icono de ayuda y selecciona *Documentación de API*.
. Seleccione *Ir a documentación privada de API*.
. Seleccione `POST /private/move-adc/start` la operación. Consulte link:../admin/using-grid-management-api.html#issue-api-requests["Emita solicitudes API"] si desea obtener más información.
+
Cada nodo se reiniciará durante el procedimiento.

. Puede utilizar `GET /private/move-adc` para supervisar el procedimiento. Si se producen errores, `POST /private/move-adc/retry` seleccione para volver a intentar el procedimiento.
. link:../maintain/downloading-recovery-package.html["Descargue un paquete de recuperación"] después de completar este procedimiento.

