---
permalink: maintain/move-adc-service.html 
sidebar: sidebar 
keywords: storagegrid, move adc, adc quorum 
summary: Puede mover el servicio ADC a otro nodo de almacenamiento en el mismo sitio. 
---
= Mover el servicio ADC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede mover el servicio ADC a otro nodo de almacenamiento en el mismo sitio.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Tieneslink:../admin/admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"] .
* El nodo de origen contiene el servicio ADC.
* El nodo de destino no contiene el servicio ADC.
* El nodo de destino es un nodo de solo metadatos o un nodo combinado (metadatos y datos de objeto).
* El nodo de origen y el nodo de destino están en el mismo sitio.


.Acerca de esta tarea
Utilice el procedimiento Mover ADC cuando desee:

* Desactivar un nodo de almacenamiento que aloja el servicio ADC
* Convertir un nodo de almacenamiento que aloja el servicio ADC en un nodo de almacenamiento solo de datos


Cuando desee desmantelar un nodo de almacenamiento olink:../maintain/convert-to-data-only-node.html["convertir un nodo de almacenamiento en un nodo de solo datos"] , primero es posible que necesites utilizar el procedimiento Mover ADC.  Necesitará asegurarse de que ellink:../maintain/understanding-adc-service-quorum.html["Se mantiene el quórum de ADC"] .

Este procedimiento mueve los servicios ADC, IDNT, ACCT y RSM de un nodo de almacenamiento a otro en el mismo sitio.  Los servicios RSM, IDNT y ACCT dependen del servicio ADC, por lo que se mueven automáticamente cuando se mueve el servicio ADC.

.Pasos
. Registre los identificadores de los nodos de origen y de destino.
+
En la API de administración de red, el ID del nodo de origen se conoce como `sourceNodeId` .  El ID del nodo de destino se conoce como `targetNodeId` .

. En la parte superior de Grid Manager, selecciona el icono de ayuda y selecciona *Documentación de API*.
. Seleccione *Ir a documentación privada de API*.
. Seleccione el `POST /private/move-adc/start` operación. Consulte link:../admin/using-grid-management-api.html#issue-api-requests["Emita solicitudes API"] Para más información.
+
Durante el procedimiento, los dos nodos se reiniciarán en secuencia.  El nodo de origen se reinicia primero, seguido por el nodo de destino.

. Puedes utilizar `GET /private/move-adc` para supervisar el procedimiento.  Si se producen errores, seleccione `POST /private/move-adc/retry` para volver a intentar el procedimiento.
. link:../maintain/downloading-recovery-package.html["Descargar un paquete de recuperación"]después de completar este procedimiento.

