---
permalink: maintain/powering-off-and-on-all-nodes-in-grid.html 
sidebar: sidebar 
keywords: storagegrid, recover, power nodes, power on nodes, power off nodes, power down nodes 
summary: Puede que tenga que apagar todo el sistema StorageGRID, por ejemplo, si va a mover un centro de datos. Estos pasos proporcionan una descripción general de alto nivel de la secuencia recomendada para realizar un apagado controlado e inicio. 
---
= Apague y encienda todos los nodos de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede que tenga que apagar todo el sistema StorageGRID, por ejemplo, si va a mover un centro de datos. Estos pasos proporcionan una descripción general de alto nivel de la secuencia recomendada para realizar un apagado controlado e inicio.

Cuando se apagan todos los nodos en un sitio o un grid, no se puede acceder a los objetos procesados mientras los nodos de almacenamiento están sin conexión.



== Detenga los servicios y apague los nodos de grid

Antes de poder apagar un sistema StorageGRID, debe detener todos los servicios que se ejecutan en cada nodo de grid y, a continuación, apagar todas las máquinas virtuales de VMware, los motores de contenedor y los dispositivos StorageGRID.

.Acerca de esta tarea
Detenga primero los servicios en los nodos de administración y la puerta de enlace y, a continuación, detenga los servicios en los nodos de almacenamiento.

Este enfoque permite usar el nodo de administración principal para supervisar el estado de los demás nodos de grid durante el mayor tiempo posible.


NOTE: Si un solo host incluye más de un nodo de cuadrícula, no apague el host hasta que haya detenido todos los nodos de ese host. Si el host incluye el nodo de administrador principal, apague ese host en último lugar.


NOTE: Si es necesario, puede link:linux-migrating-grid-node-to-new-host.html["Migre los nodos de un host Linux a otro"]realizar el mantenimiento del host sin afectar la funcionalidad o la disponibilidad de su grid.

.Pasos
. El acceso SSH externo está bloqueado de forma predeterminada.  Si es necesario,link:../admin/manage-external-ssh-access.html["permitir el acceso temporalmente"] .
. Detenga que todas las aplicaciones cliente no accedan a la cuadrícula.
. [[log_in_to_gn]]Iniciar sesión en cada nodo de puerta de enlace:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a raíz: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Al iniciar sesión como root, la petición de datos cambia de `$` a `#`.

. [[STOP_ALL_SERVICES]]Parar todos los servicios que se ejecutan en el nodo: `service servermanager stop`
+
Los servicios pueden tardar hasta 15 minutos en apagarse, y es posible que desee iniciar sesión en el sistema de forma remota para supervisar el proceso de apagado.

. Repita los dos pasos anteriores para detener los servicios en todos los nodos de almacenamiento y los nodos de administración no principales.
+
Puede detener los servicios en estos nodos en cualquier orden.

+

NOTE: Si emite `service servermanager stop` el comando para detener los servicios en un nodo de almacenamiento del dispositivo, debe apagar y encender el dispositivo para reiniciar el nodo.

. Para el nodo de administración principal, repita los pasos para <<log_in_to_gn,inicie sesión en el nodo>> y <<stop_all_services,detener todos los servicios del nodo>>.
. Para los nodos que se ejecutan en hosts Linux:
+
.. Inicie sesión en el sistema operativo del host.
.. Detenga el nodo: `storagegrid node stop`
.. Apague el sistema operativo host.


. Para los nodos que se ejecutan en máquinas virtuales de VMware y en los nodos de almacenamiento del dispositivo, emita el comando shutdown: `shutdown -h now`
+
Realice este paso independientemente del resultado `service servermanager stop` del comando.

+
Para el dispositivo, este comando apaga la controladora de computación, pero el dispositivo sigue encendido. Debe completar el siguiente paso.

. Si tiene nodos de dispositivo, siga los pasos para su dispositivo.
+
[role="tabbed-block"]
====
.SG110 o SG1100
--
.. Apague el aparato.
.. Espere a que se apague el LED de alimentación azul.


--
.SG100 o SG1000
--
.. Apague el aparato.
.. Espere a que se apague el LED de alimentación azul.


--
.SG6160
--
.. Apague la alimentación de la controladora de almacenamiento SG6100-CN.
.. Espere a que se apague el LED de alimentación azul de la controladora de almacenamiento SG6100-CN.


--
.SGF6112
--
.. Apague el aparato.
.. Espere a que se apague el LED de alimentación azul.


--
.SG6000
--
.. Espere a que se apague el LED verde de caché activa en la parte posterior de las controladoras de almacenamiento.
+
Este LED está encendido cuando es necesario escribir en las unidades los datos en caché. Debe esperar a que este LED se apague antes de apagarse.

.. Apague el aparato y espere a que se apague el LED de alimentación azul.


--
.SG5800
--
.. Espere a que se apague el LED verde de caché activa en la parte posterior de la controladora de almacenamiento.
+
Este LED está encendido cuando es necesario escribir en las unidades los datos en caché. Debe esperar a que este LED se apague antes de apagarse.

.. En la página de inicio del Administrador del sistema de SANtricity, seleccione *Ver operaciones en curso*.
.. Confirme que todas las operaciones se han completado antes de continuar con el siguiente paso.
.. Apague los dos switches de alimentación de la bandeja de controladoras y espere a que se apagen todos los LED de la bandeja de controladoras.


--
.SG5700
--
.. Espere a que se apague el LED verde de caché activa en la parte posterior de la controladora de almacenamiento.
+
Este LED está encendido cuando es necesario escribir en las unidades los datos en caché. Debe esperar a que este LED se apague antes de apagarse.

.. Apague el aparato y espere a que todos los LED y la actividad de visualización de siete segmentos se detengan.


--
====
. Si es necesario, cierre la sesión del shell de comandos: `exit`
+
El grid de StorageGRID se ha apagado.

. Si ha permitido el acceso SSH externo,link:../admin/manage-external-ssh-access.html["bloquear el acceso"] cuando haya terminado de apagar los nodos.




== Inicie nodos de grid


CAUTION: Si toda la cuadrícula se ha apagado durante más de 15 días, debe ponerse en contacto con el soporte técnico antes de iniciar cualquier nodo de grid. No intente los procedimientos de recuperación que reconstruyen los datos de Cassandra. Si lo hace, se puede producir la pérdida de datos.

Si es posible, encienda los nodos de la cuadrícula en este orden:

* Aplique primero la alimentación a los nodos de administración.
* Aplique alimentación a los nodos de puerta de enlace en último lugar.



NOTE: Si un host incluye varios nodos de grid, los nodos vuelven a estar en línea automáticamente cuando se enciende el host.

.Pasos
. Encienda los hosts del nodo de administrador principal y los nodos de administrador que no son primarios.
+

NOTE: No podrá iniciar sesión en los nodos de administrador hasta que se hayan reiniciado los nodos de almacenamiento.

. Encienda los hosts para todos los nodos de almacenamiento.
+
Puede encender estos nodos en cualquier orden.

. Encienda los hosts de todos los nodos de la puerta de enlace.
. Inicie sesión en Grid Manager.
. Seleccione *Nodos* y monitoree el estado de los nodos de la red.  Verifique que no haya íconos de alerta junto a los nombres de los nodos.


.Información relacionada
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6100/index.html["Dispositivos de almacenamiento SGF6112 y SG6160"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg110-1100/index.html["Dispositivos de servicios SG110 y SG1100"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg100-1000/index.html["Dispositivos de servicios SG100 y SG1000"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg6000/index.html["Dispositivos de almacenamiento SG6000"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5800/index.html["Dispositivos de almacenamiento SG5800"^]
* https://docs.netapp.com/us-en/storagegrid-appliances/sg5700/index.html["Dispositivos de almacenamiento SG5700"^]

