---
permalink: maintain/preparing-appliance-storage-node-for-reinstallation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, reinstallation appliance, reinstall appliance 
summary: Al recuperar un nodo de almacenamiento del dispositivo, primero debe preparar el dispositivo para la reinstalación del software StorageGRID. 
---
= Prepare el nodo de almacenamiento del dispositivo para su reinstalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al recuperar un nodo de almacenamiento del dispositivo, primero debe preparar el dispositivo para la reinstalación del software StorageGRID.

.Pasos
. Inicie sesión en el nodo de almacenamiento con errores:
+
.. Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a raíz: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Al iniciar sesión como root, la petición de datos cambia de `$` a `#`.

. Preparar el nodo de almacenamiento del dispositivo para la instalación del software StorageGRID. `sgareinstall`
. Cuando se le solicite continuar, introduzca: `y`
+
El dispositivo se reinicia y la sesión SSH finaliza. Normalmente tarda unos 5 minutos en estar disponible el instalador de dispositivos de StorageGRID; aunque en algunos casos es posible que deba esperar hasta 30 minutos.

+

CAUTION: No intente acelerar el reinicio apagando o reiniciando el aparato. Puede interrumpir las actualizaciones automáticas de BIOS, BMC u otras actualizaciones de firmware.

+
El nodo de almacenamiento del dispositivo StorageGRID se restablece y ya no se puede acceder a los datos en el nodo de almacenamiento. Las direcciones IP configuradas durante el proceso de instalación original deben permanecer intactas; sin embargo, se recomienda confirmarlo cuando finalice el procedimiento.

+
Después de ejecutar `sgareinstall` el comando, se eliminan todas las cuentas, contraseñas y claves SSH aprovisionadas por StorageGRID y se generan nuevas claves de host.


