---
permalink: maintain/recovering-from-primary-admin-node-failures.html 
sidebar: sidebar 
keywords: storagegrid, recover, primary admin node failure 
summary: 'Debe completar un conjunto específico de tareas para recuperar el sistema después de un fallo en un nodo de administrador principal. El nodo de administrador principal aloja el servicio Configuration Management Node (CMN) de la cuadrícula.' 
---
= Recupera de fallos del nodo primario de administración de StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe completar un conjunto específico de tareas para recuperar el sistema después de un fallo en un nodo de administrador principal. El nodo de administrador principal aloja el servicio Configuration Management Node (CMN) de la cuadrícula.


CAUTION: Debes reparar o sustituir sin demora un nodo de administración principal que haya fallado o podrías no poder realizar ciertos procedimientos de mantenimiento.

Siga estos pasos de alto nivel para recuperar un nodo de administración principal:

. link:copying-audit-logs-from-failed-primary-admin-node.html["Copie los registros de auditoría del nodo de administración principal con errores"]
. link:replacing-primary-admin-node.html["Sustituya el nodo de administración principal"]
. link:configuring-replacement-primary-admin-node.html["Configure el nodo de administración principal de reemplazo"]
. link:assess-hotfix-requirement-during-primary-admin-node-recovery.html["Determine si hay un requisito de revisión para el nodo de administración principal recuperado"]
. link:restoring-audit-log-on-recovered-primary-admin-node.html["Restaure el registro de auditoría en el nodo de administración principal recuperado"]
. link:restoring-admin-node-database-primary-admin-node.html["Restaure la base de datos del nodo de administración al recuperar un nodo de administración principal"]
. link:restoring-prometheus-metrics-primary-admin-node.html["Restaure las métricas de Prometheus al recuperar un nodo de administración principal"]

