---
permalink: maintain/recovering-storagegrid-appliance-storage-node.html 
sidebar: sidebar 
keywords: recover, appliance storage node failure, workflow 
summary: El procedimiento para recuperar un nodo de almacenamiento en dispositivos StorageGRID con fallos es el mismo tanto si se está recuperando de la pérdida de la unidad del sistema como de la pérdida de volúmenes de almacenamiento únicamente. 
---
= Advertencias para recuperar nodos de almacenamiento del dispositivo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El procedimiento para recuperar un nodo de almacenamiento en dispositivos StorageGRID con fallos es el mismo tanto si se está recuperando de la pérdida de la unidad del sistema como de la pérdida de volúmenes de almacenamiento únicamente.


CAUTION: Si más de un nodo de almacenamiento presenta errores (o está sin conexión), póngase en contacto con el soporte técnico. No realice el siguiente procedimiento de recuperación. Podrían perderse datos. Para obtener más información, consulte link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"].


CAUTION: Si las reglas de ILM se configuran para almacenar una sola copia replicada y existe una en un volumen de almacenamiento donde se produjo un error, no podrá recuperar el objeto.


NOTE: Para conocer los procedimientos de mantenimiento del hardware, como las instrucciones para reemplazar una controladora o reinstalar SANtricity OS, consulte la https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/index.html["instrucciones de mantenimiento para su dispositivo de almacenamiento"^].
