---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: Antes de recuperar una unidad de sistema fallida de un nodo de almacenamiento, revise las advertencias y consideraciones generales para la recuperación de nodos de grid y las siguientes advertencias específicas. 
---
= Advertencias para la recuperación de las unidades del sistema del nodo de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de recuperar una unidad de sistema con fallos de un nodo de almacenamiento, revise las advertencias generales link:warnings-and-considerations-for-grid-node-recovery.html["advertencias y consideraciones para la recuperación de nodos de grid"] y las siguientes específicas.

Los nodos de almacenamiento tienen una base de datos Cassandra que incluye metadatos de objetos. La base de datos Cassandra puede reconstruirse si:

* Un volumen de almacenamiento falla y se recupera.
* La unidad del sistema y uno o más volúmenes de almacenamiento fallan y se recuperan.


Cuando se reconstruye Cassandra, el sistema utiliza información de otros nodos de almacenamiento. Si Cassandra se ha reconstruido recientemente, es posible que los datos de Cassandra aún no sean coherentes en toda la cuadrícula. Si hay demasiados nodos de almacenamiento fuera de línea:

* Es posible que algunos datos de Cassandra no estén disponibles.
* Podrían perderse datos.



CAUTION: Si más de un nodo de almacenamiento presenta errores (o está sin conexión), póngase en contacto con el soporte técnico. No realice el siguiente procedimiento de recuperación. Podrían perderse datos. Para obtener más información, consulte link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"].


CAUTION: Si este nodo de almacenamiento está en modo de mantenimiento de solo lectura para permitir la recuperación de objetos por otro nodo de almacenamiento con volúmenes de almacenamiento con fallos, recupere los volúmenes en el nodo de almacenamiento con volúmenes de almacenamiento con errores antes de recuperar este nodo de almacenamiento con errores. Consulte las instrucciones para link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["recupere de un fallo en el volumen de almacenamiento donde la unidad del sistema esté intacta"].


CAUTION: Si las reglas de ILM se configuran para almacenar una sola copia replicada y existe una en un volumen de almacenamiento donde se produjo un error, no podrá recuperar el objeto.
