---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: Antes de recuperar volúmenes de almacenamiento con fallos para un nodo de almacenamiento, debe revisar las siguientes advertencias. 
---
= Advertencias para la recuperación del volumen de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de recuperar volúmenes de almacenamiento con errores para un nodo de almacenamiento, revise las siguientes advertencias.

Los volúmenes de almacenamiento (o mapedbs) de un nodo de almacenamiento se identifican con un número hexadecimal, que se conoce como el ID del volumen. Por ejemplo, 0000 es el primer volumen y 000F es el decimosexto volumen. El primer almacén de objetos (volumen 0) en cada nodo de almacenamiento usa hasta 4 TB de espacio para los metadatos de objetos y las operaciones de la base de datos de Cassandra; todo el espacio restante en ese volumen se usa para los datos de objetos. El resto de volúmenes de almacenamiento se utilizan exclusivamente para datos de objetos.

Es posible que la base de datos de Cassandra se reconstruya como parte del procedimiento de recuperación de volúmenes si:

* El volumen 0 falla y se recupera.
* La unidad del sistema y uno o más volúmenes de almacenamiento fallan y se recuperan.


Cuando se reconstruye Cassandra, el sistema utiliza información de otros nodos de almacenamiento. Si Cassandra se ha reconstruido recientemente, es posible que los datos de Cassandra aún no sean coherentes en toda la cuadrícula. Si hay demasiados nodos de almacenamiento fuera de línea:

* Es posible que algunos datos de Cassandra no estén disponibles.
* Podrían perderse datos.



CAUTION: Si más de un nodo de almacenamiento presenta errores (o está sin conexión), póngase en contacto con el soporte técnico. No realice el siguiente procedimiento de recuperación. Podrían perderse datos. Para obtener más información, consulte link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"].


CAUTION: Si las reglas de ILM están configuradas para almacenar solo una copia replicada y la copia existe en un volumen de almacenamiento que falló, no podrá recuperar el objeto.

.Información relacionada
link:warnings-and-considerations-for-grid-node-recovery.html["Advertencias y consideraciones sobre los procesos de recuperación de nodos de grid"]
