---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, volume warning 
summary: Antes de recuperar volúmenes de almacenamiento con fallos para un nodo de almacenamiento, debe revisar las siguientes advertencias. 
---
= Advertencias para la recuperación del volumen de almacenamiento
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de recuperar volúmenes de almacenamiento con errores para un nodo de almacenamiento, revise las siguientes advertencias.

Los volúmenes de almacenamiento (o mapedbs) de un nodo de almacenamiento se identifican con un número hexadecimal, que se conoce como el ID del volumen. Por ejemplo, 0000 es el primer volumen y 000F es el decimosexto volumen. El primer almacén de objetos (volumen 0) en cada nodo de almacenamiento usa hasta 4 TB de espacio para los metadatos de objetos y las operaciones de la base de datos de Cassandra; todo el espacio restante en ese volumen se usa para los datos de objetos. El resto de volúmenes de almacenamiento se utilizan exclusivamente para datos de objetos.

Si se produce un error en el volumen 0 y se debe recuperar, la base de datos de Cassandra puede reconstruirse como parte del procedimiento de recuperación de volumen. Cassandra también se puede reconstruir en las siguientes circunstancias:

* Un nodo de almacenamiento se vuelve a conectar después de haber estado desconectado más de 15 días.
* La unidad del sistema y uno o más volúmenes de almacenamiento fallan y se recuperan.


Cuando se reconstruye Cassandra, el sistema utiliza información de otros nodos de almacenamiento. Si hay demasiados nodos de almacenamiento sin conexión, es posible que algunos datos de Cassandra no estén disponibles. Si Cassandra se ha reconstruido recientemente, es posible que los datos de Cassandra aún no sean coherentes en toda la cuadrícula. Se pueden perder datos si Cassandra se vuelve a generar cuando hay demasiados nodos de almacenamiento sin conexión o si se reconstruyen dos o más nodos de almacenamiento en un plazo de 15 días entre sí.


CAUTION: Si más de un nodo de almacenamiento presenta errores (o está sin conexión), póngase en contacto con el soporte técnico. No realice el siguiente procedimiento de recuperación. Podrían perderse datos.


CAUTION: Si este es el segundo fallo del nodo de almacenamiento en menos de 15 días después de un fallo o una recuperación en el nodo de almacenamiento, póngase en contacto con el soporte técnico. La reconstrucción de Cassandra en dos o más nodos de almacenamiento en 15 días puede provocar la pérdida de datos.


NOTE: Si se produce un error en más de un nodo de almacenamiento de un sitio, es posible que se requiera un procedimiento de recuperación del sitio. Consulte link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"].


CAUTION: Si las reglas de ILM se configuran para almacenar una sola copia replicada y existe una en un volumen de almacenamiento donde se produjo un error, no podrá recuperar el objeto.

.Información relacionada
link:warnings-and-considerations-for-grid-node-recovery.html["Advertencias y consideraciones sobre los procesos de recuperación de nodos de grid"]
