---
permalink: maintain/selecting-node-recovery-procedure.html 
sidebar: sidebar 
keywords: storagegrid, recover, procedure 
summary: Selecciona el procedimiento de recuperación adecuado para el tipo de nodo que ha fallado. 
---
= Selecciona el procedimiento de recuperación del nodo StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Selecciona el procedimiento de recuperación adecuado para el tipo de nodo que ha fallado.

[cols="1a,2a"]
|===
| Nodo de grid | Procedimiento de recuperación 


 a| 
Nodo de almacenamiento
 a| 
El procedimiento de recuperación del nodo de almacenamiento depende del tipo de fallo.

link:recovering-from-storage-node-failures.html["Recupere el sistema de errores de nodo de almacenamiento"]



 a| 
Nodo de administración
 a| 
El procedimiento Admin Node depende de si se necesita recuperar el nodo de administrador principal o un nodo de administrador que no sea primario.

link:recovering-from-admin-node-failures.html["Recupere desde fallos de nodo de administrador"]



 a| 
Nodo de puerta de enlace
 a| 
link:replacing-gateway-node.html["Recuperarse de fallos de nodo de puerta de enlace"]



 a| 
Nodo de archivado
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/recovering-from-archive-node-failures.html["Recuperación de fallos de nodos de archivado (sitio de documentos de StorageGRID 11,8)"^]

|===

NOTE: Si falla un servidor que aloja más de un nodo de la red, puedes recuperar los nodos en cualquier orden. Sin embargo, si el servidor que ha fallado aloja el nodo de administración principal y no existen nodos de administración no principales, debes recuperar primero el nodo de administración principal. Recuperar primero el nodo de administración principal evita que las recuperaciones de otros nodos se bloqueen al intentar ponerse en contacto con el nodo de administración principal. Si hay disponible un nodo de administración no principal, también puedes usarlo para recuperar otros nodos, así esas recuperaciones pueden continuar sin necesidad de ponerse en contacto con el nodo de administración principal.
