---
permalink: maintain/selecting-start-recovery-to-configure-storage-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, storage node 
summary: Después de reemplazar un nodo de almacenamiento, debe seleccionar Iniciar recuperación en el Administrador de grid para configurar el nodo nuevo como reemplazo del nodo con error. 
---
= Selecciona Iniciar recuperación para configurar el nodo de almacenamiento StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Después de reemplazar un nodo de almacenamiento, debe seleccionar Iniciar recuperación en el Administrador de grid para configurar el nodo nuevo como reemplazo del nodo con error.

.Antes de empezar
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Usted tiene el link:../admin/admin-group-permissions.html["Permiso de mantenimiento o acceso raíz"].
* Tiene la clave de acceso de aprovisionamiento.
* Implementó y configuró el nodo de reemplazo.
* Tiene la fecha de inicio de cualquier trabajo de reparación para datos codificados de borrado.


.Acerca de esta tarea
Si el nodo de almacenamiento está instalado como un contenedor en un host Linux, debe realizar este paso solo si uno de estos valores es true:

* Ha tenido que utilizar `--force` el indicador para importar el nodo, o ha emitido `storagegrid node force-recovery _node-name_`
* Tenía que hacer una reinstalación de nodo completa o tenía que restaurar /var/local.


.Pasos
. Inicia sesión en el nodo de administración principal. Si el nodo de administración principal no está disponible, usa un nodo de administración no principal, si existe alguno.
. Desde el Grid Manager, selecciona *Maintenance* > *Tasks* > *Node recovery*.
. Seleccione el nodo de cuadrícula que desea recuperar en la lista Pending Nodes.
+
Los nodos aparecen en la lista después de que fallan, pero no puede seleccionar un nodo hasta que se haya reinstalado y esté listo para la recuperación.

. Introduce la *frase de contraseña de aprovisionamiento*.
. Haz clic en *Iniciar recuperación*.
. Supervisa el progreso de la recuperación seleccionando *Mantenimiento* > *Tareas* > *Recuperación de nodo* y viendo el progreso de la recuperación.
+
** Si el nodo de la red llega a la fase "Esperando pasos manuales", debes link:../maintain/remounting-and-reformatting-storage-volumes-manual-steps.html["Vuelve a montar y reformatea los volúmenes de almacenamiento manualmente"]. Una vez completados los pasos manuales, ve a link:../maintain/restoring-object-data-to-storage-volume.html["restaura los datos de los objetos en los volúmenes"].
** Si la recuperación del nodo de la red ha pasado de *En curso* a *Recuperado* sin pasar por la etapa “Esperando pasos manuales”, no necesitas hacer nada más.
+
[NOTE]
====
En cualquier momento durante la recuperación, puedes seleccionar *Restablecer* para iniciar una nueva recuperación. Aparecerá un cuadro de diálogo en el que se indica que el nodo quedará en un estado indeterminado si restableces el procedimiento.

Si quieres volver a intentar la recuperación después de reiniciar el procedimiento, debes restaurar el nodo del dispositivo a un estado previo a la instalación, así:

*** *VMware*: Elimine el nodo de la cuadrícula virtual desplegada. A continuación, una vez que esté listo para reiniciar la recuperación, vuelva a poner el nodo en marcha.
*** *Linux*: Reinicie el nodo ejecutando este comando en el host Linux: `storagegrid node force-recovery _node-name_`


====



