---
permalink: maintain/starting-storagegrid-appliance-installation.html 
sidebar: sidebar 
keywords: storagegrid, recover, appliance, appliance install 
summary: Para instalar StorageGRID en un nodo de almacenamiento del dispositivo, utilice el instalador de dispositivos StorageGRID, que se incluye en el dispositivo. 
---
= Inicie la instalación del dispositivo StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para instalar StorageGRID en un nodo de almacenamiento del dispositivo, utilice el instalador de dispositivos StorageGRID, que se incluye en el dispositivo.

.Antes de empezar
* El dispositivo se ha instalado en un bastidor, conectado a las redes y encendido.
* Se han configurado los enlaces de red y las direcciones IP para el dispositivo mediante el instalador de dispositivos de StorageGRID.
* Conoce la dirección IP del nodo de administrador principal para la cuadrícula StorageGRID.
* Todas las subredes de red de cuadrícula que aparecen en la página Configuración de IP del instalador de dispositivos StorageGRID se definieron en la lista de subredes de redes de cuadrícula del nodo de administración principal.
* Ha completado estas tareas de requisitos previos siguiendo las instrucciones de instalación para el dispositivo de almacenamiento. Consulte https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/index.html["Inicio rápido para la instalación de hardware"^].
* Está utilizando una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Conoce una de las direcciones IP asignadas a la controladora de computación en el dispositivo. Es posible usar la dirección IP para la red de administración (puerto de gestión 1 en la controladora), la red de grid o la red de cliente.


.Acerca de esta tarea
Para instalar StorageGRID en un nodo de almacenamiento de dispositivos:

* Especifique o confirme la dirección IP del nodo de administración principal y el nombre de host (nombre del sistema) del nodo.
* Inicia la instalación y espera a que los volúmenes estén configurados y el software esté instalado.
+

NOTE: Al recuperar un nodo de almacenamiento de dispositivo, reinstálelo con el mismo tipo de almacenamiento que el dispositivo original (combinado, solo metadatos o solo datos). Si especifica un tipo de almacenamiento diferente, la recuperación fallará y será necesario volver a instalar el dispositivo con el tipo de almacenamiento correcto especificado.

* Paso a través del proceso, la instalación se detiene. Para reanudar la instalación, debe iniciar sesión en Grid Manager y configurar el nodo de almacenamiento pendiente como reemplazo del nodo con errores.
* Una vez que haya configurado el nodo, se completa el proceso de instalación del dispositivo y el dispositivo se reinicia.


.Pasos
. Abra un explorador e introduzca una de las direcciones IP para la controladora de computación en el dispositivo.
+
`https://_Controller_IP_:8443`

+
Aparece la página de inicio del instalador de dispositivos de StorageGRID.

. En la sección Conexión del nodo de administración principal, determine si necesita especificar la dirección IP para el nodo de administración principal.
+
El instalador de dispositivos de StorageGRID puede detectar esta dirección IP automáticamente, suponiendo que el nodo de administración principal o, al menos, otro nodo de grid con ADMIN_IP configurado, esté presente en la misma subred.

. Si no se muestra esta dirección IP o es necesario modificarla, especifique la dirección:
+
[cols="1a,2a"]
|===
| Opción | Pasos 


 a| 
Entrada IP manual
 a| 
.. Desactive la casilla de verificación *Enable Admin Node discovery*.
.. Introduzca la dirección IP de forma manual.
.. Haga clic en *Guardar*.
.. Espere hasta que el estado de conexión de la nueva dirección IP esté listo.




 a| 
Detección automática de todos los nodos principales de administración conectados
 a| 
.. Seleccione la casilla de verificación *Enable Admin Node discovery*.
.. En la lista de direcciones IP detectadas, seleccione el nodo de administrador principal para la cuadrícula en la que se pondrá en marcha este nodo de almacenamiento del dispositivo.
.. Haga clic en *Guardar*.
.. Espere hasta que el estado de conexión de la nueva dirección IP esté listo.


|===
. En el campo *Nombre del nodo*, introduzca el mismo nombre de host (nombre del sistema) que se utilizó para el nodo que está recuperando y haga clic en *Guardar*.
. En la sección Instalación, confirme que el estado actual es “Listo para iniciar la instalación de `_node name_` Into grid con el nodo de administración principal `_admin_ip_`” y que el botón *Iniciar instalación* está habilitado.
+
Si el botón *Iniciar instalación* no está activado, es posible que deba cambiar la configuración de red o la configuración del puerto. Para obtener instrucciones, consulte las instrucciones de mantenimiento de su aparato.

. En la página de inicio del instalador de dispositivos StorageGRID, haga clic en *Iniciar instalación*.
+
El estado actual cambia a «Instalación en curso» y se muestra la página de instalación del monitor.

+

NOTE: Si necesita acceder a la página de instalación del monitor manualmente, haga clic en *instalación del monitor* en la barra de menús. Consulte https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/monitoring-appliance-installation.html["Supervise la instalación del dispositivo"^].


