---
permalink: maintain/understanding-adc-service-quorum.html 
sidebar: sidebar 
keywords: storagegrid, recover, adc, adc quorum 
summary: 'Es posible que no pueda retirar determinados nodos de almacenamiento en un sitio si quedan muy pocos servicios de controlador de dominio administrativo \(ADC\) tras el desmantelamiento.' 
---
= ¿Qué es el quórum ADC?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible que no pueda retirar determinados nodos de almacenamiento en un sitio si quedan muy pocos servicios de controlador de dominio administrativo (ADC) tras el desmantelamiento.

El servicio ADC, que se encuentra en algunos nodos de almacenamiento, mantiene la información de topología de cuadrícula y proporciona servicios de configuración a la cuadrícula. El sistema StorageGRID requiere que se disponga de quórum de servicios de ADC en todas las instalaciones y en todo momento.

No puede retirar un nodo de almacenamiento si al quitar el nodo se haría que el quórum ADC ya no se cumpliera. Para cumplir con el quórum ADC durante un desmantelamiento, un mínimo de tres nodos de almacenamiento en cada sitio debe tener el servicio ADC. Si un sitio tiene más de tres nodos de almacenamiento con el servicio ADC, la sencilla mayoría de ellos deberá seguir estando disponible tras el desmantelamiento: `((0.5 * _Storage Nodes with ADC_) + 1)`


CAUTION: Use precaución al decomisionar nodos de almacenamiento en un grid que contenga nodos solo de metadatos basados en software. Si retira todos los nodos configurados para almacenar _both_ objetos y metadatos, la capacidad de almacenar objetos se elimina de la cuadrícula. Consulte link:../primer/what-storage-node-is.html#types-of-storage-nodes["Tipos de nodos de almacenamiento"] para obtener más información sobre nodos de almacenamiento solo de metadatos.

Por ejemplo, supongamos que un sitio incluye actualmente seis nodos de almacenamiento con servicios ADC y que desea retirar tres nodos de almacenamiento. Debido al requisito de quórum de ADC, debe completar dos procedimientos de retirada, de la siguiente manera:

* En el primer procedimiento de retirada, debe asegurarse de que siguen estando disponibles cuatro nodos de almacenamiento con servicios ADC: `((0.5 * 6) + 1)`. Esto significa que solo puede decomisionar dos nodos de almacenamiento inicialmente.
* En el segundo procedimiento de desmantelamiento, puede eliminar el tercer nodo de almacenamiento porque el quórum de ADC ahora requiere que solo tres servicios de ADC permanezcan disponibles: `((0.5 * 4) + 1)` .


Si necesita desmantelar un nodo de almacenamiento, puede continuar cumpliendo con el requisito de quórum de ADClink:../upgrade/changes-to-grid-management-api.html#new-private-endpoints-for-move-adc["Mover el servicio ADC a otro nodo de almacenamiento en el mismo sitio"] o agregar un nuevo nodo de almacenamiento en unlink:../expand/index.html["expansión"] y especificando que debe tener un servicio ADC.  Luego, puedes desmantelar el nodo de almacenamiento existente sin afectar el quórum.
