---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: Si un nodo de grid falla, debe recuperarlo Lo antes posible.. Antes de empezar, debe revisar todas las advertencias y consideraciones de la recuperación de nodos. 
---
= Advertencias y consideraciones sobre los procesos de recuperación de nodos de grid
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un nodo de grid falla, debe recuperarlo Lo antes posible.. Antes de empezar, debe revisar todas las advertencias y consideraciones de la recuperación de nodos.


CAUTION: StorageGRID es un sistema distribuido compuesto por varios nodos que funcionan entre sí. No utilice instantáneas de disco para restaurar nodos de grid. En su lugar, consulte los procedimientos de recuperación y mantenimiento de cada tipo de nodo.


NOTE: Si un sitio completo de StorageGRID ha fallado, comuníquese con el soporte técnico.  El soporte técnico trabajará con usted para desarrollar y ejecutar un plan de recuperación del sitio que maximice la cantidad de datos recuperados y cumpla con sus objetivos comerciales. Consulte link:how-site-recovery-is-performed-by-technical-support.html["Cómo el soporte técnico recupera un sitio"] .

Entre los motivos para recuperar un Lo antes posible. de nodo de Grid con errores se incluyen los siguientes:

* Un nodo de grid fallido puede reducir la redundancia de los datos del sistema y del objeto, lo que le deja vulnerable al riesgo de pérdida permanente de datos si falla otro nodo.
* Un nodo de grid fallido puede afectar a la eficacia de las operaciones diarias.
* Un nodo de grid con errores puede reducir su capacidad para supervisar las operaciones del sistema.
* Un nodo de grid fallido puede provocar un error interno de 500 servidores si se aplican reglas estrictas de ILM.
* Si un nodo de grid no se recupera con la rapidez, es posible que aumenten los tiempos de recuperación. Por ejemplo, se podrían desarrollar colas que se deben borrar antes de que se complete la recuperación.


Siga siempre el procedimiento de recuperación para el tipo específico de nodo de cuadrícula que se va a recuperar. Los procedimientos de recuperación varían para los nodos de administración primarios o no principales, los nodos de puerta de enlace, los nodos de dispositivo y los nodos de almacenamiento.



== Condiciones previas para la recuperación de nodos de grid

Al recuperar nodos de grid, se da por sentado las siguientes condiciones:

* Se reemplazó y configuró el hardware físico o virtual que falló.
* La versión del instalador de dispositivos StorageGRID en el dispositivo de sustitución coincide con la versión de software de su sistema StorageGRID, como se describe en https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["Comprobar y actualizar la versión de StorageGRID Appliance Installer"^].
* Si está recuperando un nodo de red que no sea el nodo de administración principal, existe conectividad entre el nodo de red que se está recuperando y el nodo de administración que administra el procedimiento de recuperación.
* Si está recuperando un nodo de almacenamiento del dispositivo, debe especificar el mismo tipo de almacenamiento que el dispositivo original (combinado, solo metadatos o solo datos) durante la instalación del dispositivo.  Si especifica un tipo de almacenamiento diferente, la recuperación fallará y será necesario reinstalar el dispositivo con el tipo de almacenamiento correcto especificado.




== El orden de recuperación de nodos si se produce un error en un servidor que aloja más de un nodo de grid

Si falla un servidor que aloja más de un nodo de red, puede recuperar los nodos en cualquier orden. Sin embargo, si el servidor que falló aloja el nodo de administración principal y no existen nodos de administración secundarios, primero debe recuperar el nodo de administración principal.



== Direcciones IP para nodos recuperados

No intente recuperar un nodo usando una dirección IP que esté actualmente asignada a cualquier otro nodo. Cuando se implementa el nodo nuevo, use la dirección IP actual del nodo con errores o una dirección IP sin usar.

Si utiliza una dirección IP nueva para implementar el nodo nuevo y después recuperar el nodo, la dirección IP nueva se seguirá usando para el nodo recuperado. Si desea revertir a la dirección IP original, utilice la herramienta Change IP una vez completada la recuperación.
