---
permalink: primer/nodes-and-services.html 
sidebar: sidebar 
keywords: services, grid nodes, primary admin, storage, gateway 
summary: El elemento básico de un sistema StorageGRID es el nodo de Grid. Los nodos contienen servicios, que son módulos de software que proporcionan un conjunto de funcionalidades a un nodo de grid. 
---
= Nodos de grid y servicios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El elemento básico de un sistema StorageGRID es el nodo de Grid. Los nodos contienen servicios, que son módulos de software que proporcionan un conjunto de funcionalidades a un nodo de grid.



== Tipos de nodos de cuadrícula

El sistema StorageGRID utiliza cuatro tipos de nodos de grid:

Nodos de administración:: Proporcione servicios de gestión como la configuración, la supervisión y el registro del sistema. Cuando inicia sesión en Grid Manager, se conecta a un nodo de administración. Cada grid debe tener un nodo de administrador primario y puede tener nodos de administrador no primarios adicionales para la redundancia. Puede conectarse a cualquier nodo de administrador y cada nodo de administrador muestra una vista similar del sistema StorageGRID. Sin embargo, se deben realizar los procedimientos de mantenimiento usando el nodo de administración principal.
+
--
Los nodos de administración también se pueden usar para equilibrar la carga del tráfico de clientes S3.

Consulte link:what-admin-node-is.html["¿Qué es un nodo de administración?"]

--
Nodos de almacenamiento:: Gestione y almacene metadatos y datos de objetos. Cada sitio del sistema StorageGRID debe tener al menos tres nodos de almacenamiento.
+
--
Consulte link:what-storage-node-is.html["¿Qué es un nodo de almacenamiento?"]

--
Nodos de puerta de enlace (opcionales):: Proporcione una interfaz de equilibrio de carga que las aplicaciones cliente puedan utilizar para conectarse a StorageGRID. Un equilibrador de carga dirige sin problemas a los clientes a un nodo de almacenamiento óptimo, de modo que el fallo de los nodos o incluso de todo un sitio sea transparente.
+
--
Consulte link:what-gateway-node-is.html["¿Qué es un nodo de puerta de enlace?"]

--




== Nodos de hardware y software

Los nodos StorageGRID se pueden poner en marcha como nodos de dispositivo StorageGRID o como nodos basados en software.



=== Nodos del dispositivo StorageGRID

Los dispositivos de hardware StorageGRID están especialmente diseñados para su uso en un sistema StorageGRID. Algunos dispositivos se pueden usar como nodos de almacenamiento. Otros dispositivos se pueden usar como nodos de administrador o nodos de puerta de enlace. Puede combinar nodos de dispositivos con nodos basados en software o poner en marcha grids de dispositivo completamente diseñados que no tengan dependencias en hipervisores externos, almacenamiento ni hardware de computación.

Consulte lo siguiente para obtener más información sobre los dispositivos disponibles:

* https://docs.netapp.com/us-en/storagegrid-appliances/["Documentación del dispositivo StorageGRID"^]
* https://hwu.netapp.com["NetApp Hardware Universe"^]




=== Nodos basados en software

Los nodos de grid basados en software se pueden poner en marcha como máquinas virtuales de VMware o en motores de contenedor en un host Linux.

* Máquina virtual (VM) en VMware vSphere: Consulte link:../vmware/index.html["Instale StorageGRID en VMware"].
* En un motor de contenedores en Red Hat Enterprise Linux: Consulte link:../rhel/index.html["Instalar StorageGRID en Red Hat Enterprise Linux"].
* Dentro de un motor de contenedores en Ubuntu o Debian: Ver link:../ubuntu/index.html["Instalar StorageGRID en Ubuntu o Debian"].


Utilice https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp (IMT)"^] para determinar las versiones compatibles.

Durante la instalación inicial de un nuevo nodo de almacenamiento basado en software, puede especificar que sólo se utilice en link:../primer/what-storage-node-is.html#types-of-storage-nodes["almacenar metadatos"].



== Servicios de StorageGRID

A continuación, se muestra una lista completa de los servicios StorageGRID.

[cols="2a,3a,2a"]
|===
| Servicio | Descripción | Ubicación 


 a| 
Promotor de servicios de cuenta
 a| 
Proporciona una interfaz para que el servicio Load Balancer pueda consultar el Servicio de cuenta en hosts remotos y proporciona notificaciones de cambios de configuración de Load Balancer Endpoint al servicio Load Balancer.
 a| 
Servicio de equilibrio de carga en los nodos de administración y de puerta de enlace



 a| 
ADC (Controlador de dominio administrativo)
 a| 
Mantiene información de topología, proporciona servicios de autenticación y responde a las consultas de los servicios LDR y CMN.
 a| 
Al menos tres nodos de almacenamiento que contienen el servicio ADC en cada sitio



 a| 
AMS (Sistema de Gestión de Auditoría)
 a| 
Supervisa y registra todos los eventos y transacciones auditados del sistema en un archivo de registro de texto.
 a| 
Nodos de administración



 a| 
Apache Tomcat
 a| 
Servidor web para aplicaciones basadas en Java.
 a| 
Nodos de administración



 a| 
Daemon Avahi
 a| 
Maneja mDNS, que se utiliza para la resolución de nombres y la detección de servicios dentro de la red local.
 a| 
Todos los nodos



 a| 
Servicio de caché
 a| 
Se ejecuta en nodos de equilibrio de carga (Gateway) y gestiona una caché local de contenido de objeto.
 a| 
Nodos de puerta de enlace



 a| 
Cassandra
 a| 
Gestiona la base de datos distribuida para los metadatos de objetos.
 a| 
Nodos de almacenamiento (excepto solo datos)



 a| 
Cassandra Reaper
 a| 
Realiza reparaciones automáticas de metadatos de objetos.
 a| 
Nodos de almacenamiento



 a| 
Servicio CHUNK
 a| 
Gestiona datos codificados de borrado y fragmentos de paridad.
 a| 
Nodos de almacenamiento



 a| 
CMN (nodo de gestión de configuración)
 a| 
Gestiona las configuraciones de todo el sistema y las tareas de grid. Cada grid tiene un servicio CMN.
 a| 
Nodo de administrador principal



 a| 
DDS (almacén de datos distribuidos)
 a| 
Interactúa con la base de datos de Cassandra para gestionar los metadatos de objetos.
 a| 
Nodos de almacenamiento



 a| 
DMV (Data Mover)
 a| 
Mueve los datos a extremos de cloud.
 a| 
Nodos de almacenamiento



 a| 
IP dinámica (dynip)
 a| 
Supervisa la cuadrícula para los cambios dinámicos de IP y actualiza las configuraciones locales.
 a| 
Todos los nodos



 a| 
Grafana
 a| 
Se utiliza para la visualización de métricas en Grid Manager.
 a| 
Nodos de administración



 a| 
Alta disponibilidad
 a| 
Gestiona las IP virtuales de alta disponibilidad en los nodos configurados en la página High Availability Groups. Este servicio también se conoce como servicio de keepalived.
 a| 
Nodos de administración y puerta de enlace



 a| 
Identidad (no)
 a| 
Gestiona usuarios y grupos locales, autenticación y federa identidades de usuarios desde LDAP y Active Directory.
 a| 
Nodos de almacenamiento que usan el servicio ADC



 a| 
Árbitro Lambda
 a| 
Gestiona solicitudes S3 Select ObjectContent.
 a| 
Todos los nodos



 a| 
Equilibrador de carga (nginx-gw)
 a| 
Proporciona un equilibrio de carga del tráfico S3 desde los clientes a los nodos de almacenamiento. El servicio Load Balancer se puede configurar a través de la página de configuración Load Balancer Endpoints. Este servicio también se conoce como servicio nginx-gw.
 a| 
Nodos de administración y puerta de enlace



 a| 
LDR (enrutador de distribución local)
 a| 
Gestiona el almacenamiento y la transferencia de contenido dentro de la cuadrícula.
 a| 
Nodos de almacenamiento



 a| 
Daemon de Control de Servicio de Información MISCd
 a| 
Proporciona una interfaz para consultar y gestionar servicios en otros nodos y para gestionar configuraciones de entorno en el nodo, como consultar el estado de los servicios que se ejecutan en otros nodos.
 a| 
Todos los nodos



 a| 
nginx
 a| 
Actúa como mecanismo de autenticación y comunicación segura para que varios servicios de grid (como Prometheus y Dynamic IP) puedan comunicarse con servicios de otros nodos a través de las API HTTPS.
 a| 
Todos los nodos



 a| 
Equilibrador de carga nginx-gw
 a| 
Proporciona un equilibrio de carga del tráfico S3 desde los clientes a los nodos de almacenamiento. El servicio Load Balancer se puede configurar a través de la página de configuración Load Balancer Endpoints. Este servicio también se conoce como servicio nginx-gw.
 a| 
Nodos de administración y puerta de enlace



 a| 
NMS (Sistema de gestión de redes)
 a| 
Activa las opciones de supervisión, generación de informes y configuración que se muestran a través de Grid Manager.
 a| 
Nodos de administración



 a| 
Exportador de nodos (recopilación de datos de Prometheus)
 a| 
Publica estadísticas de nivel de sistema para la recopilación de métricas de series temporales de Prometheus.
 a| 
Todos los nodos



 a| 
ntp
 a| 
Servicio del protocolo de hora de red (NTP).
 a| 
Todos los nodos



 a| 
Persistencia
 a| 
Administra los archivos del disco raíz que deben persistir durante un reinicio.
 a| 
Todos los nodos



 a| 
Prometheus
 a| 
Recopila métricas de series temporales de los servicios en todos los nodos.
 a| 
Nodos de administración



 a| 
RSM (máquina de estado replicado)
 a| 
Garantiza que las solicitudes de servicio de la plataforma se envíen a sus respectivos extremos.
 a| 
Nodos de almacenamiento que usan el servicio ADC



 a| 
SSM (Monitor de estado del servidor)
 a| 
Supervisa las condiciones del hardware e informa al servicio NMS.
 a| 
Hay una instancia presente en cada nodo de cuadrícula



 a| 
Administrador de servidores
 a| 
Gestiona los servicios de StorageGRID.
 a| 
Todos los nodos



 a| 
Agente SNMP
 a| 
Responde a las solicitudes SNMP.
 a| 
Nodos de administración



 a| 
Servicio de gestión de puertos SNMP
 a| 
Maneja la administración dinámica de puertos SNMP.
 a| 
Todos los nodos



 a| 
SSH (shell seguro)
 a| 
Maneja el acceso seguro y la administración remota del sistema.
 a| 
Todos los nodos



 a| 
SSM (Monitor de estado del sistema)
 a| 
Supervisa las condiciones del hardware e informa al servicio NMS.
 a| 
Todos los nodos



 a| 
Urgente
 a| 
Registra métricas adicionales relacionadas con bloques de S3.
 a| 
Nodos de almacenamiento



 a| 
Agente de rastreo (agente jaeger)
 a| 
Recibe y procesa la información de rastreo enviada por el recolector de trazas (jaeger-collector).
 a| 
Todos los nodos



 a| 
Recolector de trazas (colector jaeger)
 a| 
Realiza la recogida de seguimiento para recopilar información que el soporte técnico utiliza. El servicio de recopilación de rastreo utiliza el software Jaeger de código abierto.
 a| 
Nodos de administración

|===