---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: Los nodos de administración, que proporcionan servicios de gestión como configuración, supervisión y registro del sistema. Los nodos de administración también se pueden usar para equilibrar la carga del tráfico de clientes S3. Cada grid debe tener un nodo de administrador primario y puede tener cualquier cantidad de nodos de administrador no primarios por motivos de redundancia. 
---
= ¿Qué es un nodo de administración?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los nodos de administración, que proporcionan servicios de gestión como configuración, supervisión y registro del sistema. Los nodos de administración también se pueden usar para equilibrar la carga del tráfico de clientes S3. Cada grid debe tener un nodo de administrador primario y puede tener cualquier cantidad de nodos de administrador no primarios por motivos de redundancia.



== Diferencias entre los nodos de administración primario y no principal

Cuando inicia sesión en el administrador de grid o en el administrador de inquilinos, se conecta a un nodo de administración. Puede conectarse a cualquier nodo de administrador y cada nodo de administrador muestra una vista similar del sistema StorageGRID. Sin embargo, el nodo de administración principal proporciona más funcionalidad que los nodos de administración no principales. Por ejemplo, la mayoría de los procedimientos de mantenimiento se deben realizar desde los nodos de administración principales.

En la tabla se resumen las capacidades de los nodos ADMIN principales y no principales.

[cols="2a,1a,1a"]
|===
| Funcionalidades | Nodo de administrador principal | Nodo de administrador no primario 


 a| 
Incluye el <<ams,AMS>> servicio
 a| 
Sí
 a| 
Sí



 a| 
Incluye el <<cmn,CMN>> servicio
 a| 
Sí
 a| 
No



 a| 
Incluye el <<nms,NMS>> servicio
 a| 
Sí
 a| 
Sí



 a| 
Incluye el <<prometheus,Prometheus>> servicio
 a| 
Sí
 a| 
Sí



 a| 
Incluye el <<ssm,SSM>> servicio
 a| 
Sí
 a| 
Sí



 a| 
Incluye los <<load-balancer,Equilibrador de carga>> servicios y.<<high-availability,Alta disponibilidad>>
 a| 
Sí
 a| 
Sí



 a| 
Es compatible con <<mgmt-api,Interfaz del programa de aplicaciones de gestión>> (mgmt-api)
 a| 
Sí
 a| 
Sí



 a| 
Se puede utilizar para todas las tareas de mantenimiento relacionadas con la red, por ejemplo, el cambio de dirección IP y la actualización de servidores NTP
 a| 
Sí
 a| 
No



 a| 
Puede realizar un reequilibrio de EC tras la ampliación del nodo de almacenamiento
 a| 
Sí
 a| 
No



 a| 
Se puede utilizar para el procedimiento de restauración de volúmenes
 a| 
Sí
 a| 
Sí



 a| 
Puede recoger archivos de registro y datos del sistema de uno o más nodos
 a| 
Sí
 a| 
No



 a| 
Envía notificaciones de alerta, paquetes AutoSupport y capturas SNMP e informa
 a| 
Sí. Actúa como el <<preferred-sender,remitente preferido>>.
 a| 
Sí. Actúa como remitente en espera.

|===


== [[preferred-sender]]Nodo de administración de remitente preferido

Si la implementación de StorageGRID incluye varios nodos de administración, el nodo de administración principal es el remitente preferido para las notificaciones de alertas, los paquetes de AutoSupport y las capturas SNMP.

En operaciones normales del sistema, solo el remitente preferido envía notificaciones. Sin embargo, el resto de los nodos de administración supervisan el remitente preferido. Si se detecta un problema, otros nodos de administración actúan como _remitentes en espera_.

Es posible que se envíen varias notificaciones en los siguientes casos:

* Si los nodos de administración pasan a ser “indistribuidos” entre sí, tanto el remitente preferido como los remitentes en espera intentarán enviar notificaciones, y es posible que se reciban varias copias de las notificaciones.
* Si el remitente en espera detecta problemas con el remitente preferido y comienza a enviar notificaciones, es posible que el remitente preferido recupere su capacidad para enviar notificaciones. Si esto ocurre, es posible que se envíen notificaciones duplicadas. El remitente en espera dejará de enviar notificaciones cuando ya no detecte errores en el remitente preferido.
+

NOTE: Cuando prueba los paquetes AutoSupport, todos los nodos de administración envían la prueba. Cuando prueba las notificaciones de alerta, debe iniciar sesión en cada nodo de administrador para verificar la conectividad.





== Servicios primarios para nodos de administración

En la siguiente tabla se muestran los servicios principales de los nodos de administrador; sin embargo, esta tabla no enumera todos los servicios de nodo.

[cols="1a,2a"]
|===
| Servicio | Función de la tecla 


 a| 
[[ams]]Sistema de Gestión de Auditoría (AMS)
 a| 
Realiza un seguimiento de la actividad y los eventos del sistema.



 a| 
[[cmn]]Nodo de gestión de configuración (CMN)
 a| 
Gestiona la configuración en todo el sistema.



 a| 
[[alta disponibilidad]]Alta disponibilidad
 a| 
Administra direcciones IP virtuales de alta disponibilidad para grupos de nodos de administración y nodos de puerta de enlace.

*Nota:* este servicio también se encuentra en los nodos Gateway.



 a| 
[[load-balancer]]Equilibrador de carga
 a| 
Proporciona un equilibrio de carga del tráfico S3 desde los clientes a los nodos de almacenamiento.

*Nota:* este servicio también se encuentra en los nodos Gateway.



 a| 
[[mgmt-api]]Interfaz de programa de aplicaciones de gestión (mgmt-api)
 a| 
Procesa las solicitudes de la API de gestión de grid y la API de gestión de inquilinos.



 a| 
[[nms]]Sistema de gestión de redes (NMS)
 a| 
Proporciona funcionalidad para Grid Manager.



 a| 
[[prometeo]]Prometeo
 a| 
Recopila y almacena métricas de series temporales de los servicios en todos los nodos.



 a| 
[[ssm]]Monitor de estado del servidor (SSM)
 a| 
Supervisa el sistema operativo y el hardware subyacente.

|===