---
permalink: expand/adding-grid-nodes-to-add-capabilities.html 
sidebar: sidebar 
keywords: grid nodes, expand, expansion, site, add, StorageGRID 
summary: Es posible añadir redundancia o funcionalidades adicionales a un sistema StorageGRID añadiendo nodos grid a las ubicaciones existentes. 
---
= Pautas para agregar nodos de cuadrícula en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es posible añadir redundancia o funcionalidades adicionales a un sistema StorageGRID añadiendo nodos grid a las ubicaciones existentes.

Por ejemplo, puede optar por agregar nodos de puerta de enlace para utilizarlos en un grupo de alta disponibilidad (HA), o puede agregar un nodo de administración en un sitio remoto para permitir la supervisión mediante un nodo local.

Los siguientes tipos de nodos se pueden añadir uno o varios de ellos en uno o varios sitios existentes en una sola operación de ampliación:

* Nodos de administrador no primario
* Nodos de almacenamiento
* Nodos de puerta de enlace


Al preparar la adición de nodos de grid, tenga en cuenta las siguientes limitaciones:

* El nodo de administrador principal se pone en marcha durante la instalación inicial. No puede agregar un nodo de administración principal durante una expansión.
* En la misma expansión, puede añadir nodos de almacenamiento y otros tipos de nodos.
* Cuando añada nodos de almacenamiento, debe planificar con cuidado el número y la ubicación de los nodos nuevos. Consulte link:../expand/guidelines-for-adding-object-capacity.html["Directrices para añadir capacidad de objeto"].
* Si la opción *Establecer nuevo nodo predeterminado* es *No confiable* en la pestaña Redes de cliente no confiables en la página Control de firewall, las aplicaciones cliente que se conectan a nodos de expansión mediante la Red de cliente deben conectarse mediante un puerto de punto final del balanceador de carga (*Configuración* > *Seguridad* > *Control de firewall*).  Vea las instrucciones paralink:../admin/configure-firewall-controls.html["cambie la configuración de seguridad del nuevo nodo"] y alink:../admin/configuring-load-balancer-endpoints.html["configurar puntos finales de equilibrio de carga"] .

