---
permalink: expand/contacting-technical-support.html 
sidebar: sidebar 
keywords: troubleshoot expansion, contact technical support, StorageGRID 
summary: Si encuentra errores durante el proceso de expansión de cuadrícula que no puede resolver o si falla una tarea de cuadrícula, recopile los archivos de registro y póngase en contacto con el soporte técnico. 
---
= Solucionar errores de expansión en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si encuentra errores durante el proceso de expansión de cuadrícula que no puede resolver o si falla una tarea de cuadrícula, recopile los archivos de registro y póngase en contacto con el soporte técnico.

Antes de comunicarse con el soporte técnico, recoja los archivos de registro requeridos para ayudar a la solución de problemas.

.Pasos
. El acceso SSH externo está bloqueado de forma predeterminada.  Si es necesario,link:../admin/manage-external-ssh-access.html["permitir el acceso temporalmente"] .
. Conéctese al nodo de ampliación que ha experimentado errores:
+
.. Introduzca el siguiente comando:``ssh -p 8022 admin@_grid_node_IP_``
+
El puerto 8022 es el puerto SSH del sistema operativo base, mientras que el puerto 22 es el puerto SSH del motor del contenedor que ejecuta StorageGRID.

.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a raíz: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


+
Después de iniciar sesión como root, la petición de datos cambia de `$` a `#`.

. Según la etapa en la que se haya alcanzado la instalación, recupere cualquiera de los siguientes registros disponibles en el nodo de grid:
+
[cols="1a,2a"]
|===
| Plataforma | Registros 


 a| 
VMware
 a| 
** `/var/log/daemon.log`
** `/var/log/storagegrid/daemon.log`
** `/var/log/storagegrid/nodes/<node-name>.log`




 a| 
Linux
 a| 
** `/var/log/storagegrid/daemon.log`
** `/etc/storagegrid/nodes/<node-name>.conf` (en cada nodo con errores)
** `/var/log/storagegrid/nodes/<node-name>.log` (para cada nodo con fallos; es posible que no exista)


|===
. Si ha permitido el acceso SSH externo,link:../admin/manage-external-ssh-access.html["bloquear el acceso"] Cuando hayas terminado la tarea.

