---
sidebar: sidebar 
permalink: expand/copying-audit-logs.html 
keywords: copy audit log, Admin Node expansion, StorageGRID 
summary: Cuando se agrega un nuevo nodo de administración a través de un procedimiento de expansión, su servicio AMS solo registra los eventos y acciones que ocurren después de que se une al sistema.  Según sea necesario, puede copiar registros de auditoría de un nodo de administración previamente instalado al nuevo nodo de administración de expansión para que esté sincronizado con el resto del sistema StorageGRID . 
---
= Copiar registros de auditoría a nuevos nodos de administración en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cuando se agrega un nuevo nodo de administración a través de un procedimiento de expansión, su servicio AMS solo registra los eventos y acciones que ocurren después de que se une al sistema.  Según sea necesario, puede copiar registros de auditoría de un nodo de administración previamente instalado al nuevo nodo de administración de expansión para que esté sincronizado con el resto del sistema StorageGRID .

.Antes de empezar
* Completó los pasos de ampliación necesarios para añadir un nodo de administrador.
* Tiene el `Passwords.txt` archivo.


.Acerca de esta tarea
Para que los mensajes de auditoría históricos estén disponibles en un nodo de administración nuevo, debe copiar los archivos de registro de auditoría manualmente desde un nodo de administración existente al nodo de administración de expansión.

[NOTE]
====
De forma predeterminada, la información de auditoría se envía a la `localaudit` Inicie sesión en cada nodo.  Para utilizar este procedimiento, debe haber configurado los nodos de administración como destino de auditoría de la siguiente manera:

* Ha configurado *Nodos de administración/nodos locales* como destino del registro.
* Ha configurado *Nodos de administración y servidor syslog externo* como destino del registro.


Referirse alink:../monitor/configure-audit-messages.html["Configure los mensajes de auditoría y el servidor de syslog externo"] Para más detalles.

====
.Pasos
. Inicie sesión en el nodo de administración principal:
+
.. Introduzca el siguiente comando: `ssh _admin@_primary_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a raíz: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
+
Al iniciar sesión como root, la petición de datos cambia de `$` a `#`.



. Detenga el servicio AMS para evitar que cree un nuevo archivo: `service ams stop`
. Navegue al directorio de exportación de auditoría:
+
`cd /var/local/audit/export/`

. Cambiar el nombre de la fuente `audit.log` archivo para asegurarse de que no sobrescriba el archivo en el nodo de administración de expansión al que lo está copiando:
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. Copie todos los archivos de registro de auditoría en la ubicación de destino en el nodo de administración de expansión:
+
`scp -p * _IP_address_:/var/local/audit/export/`

. Si se le solicita la contraseña para `/root/.ssh/id_rsa`, introduzca la contraseña de acceso SSH para el nodo de administración principal que aparece en el `Passwords.txt` archivo.
. Restaure el archivo original `audit.log`:
+
`mv _new_name_.txt audit.log`

. Inicie el servicio AMS:
+
`service ams start`

. Cierre la sesión en el servidor:
+
`exit`

. Inicie sesión en el nodo de administrador de ampliación:
+
.. Introduzca el siguiente comando: `ssh admin@_expansion_Admin_Node_IP_`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
.. Introduzca el siguiente comando para cambiar a raíz: `su -`
.. Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
+
Al iniciar sesión como root, la petición de datos cambia de `$` a `#`.



. Actualice la configuración del usuario y del grupo para los archivos de registro de auditoría:
+
`cd /var/local/audit/export/`

+
`chown ams-user:bycast *`

. Cierre la sesión en el servidor:
+
`exit`


