---
permalink: expand/copying-admin-node-database.html 
sidebar: sidebar 
keywords: copy Admin Node database, alert history, Admin Node expansion 
summary: Al añadir nodos de administrador mediante un procedimiento de ampliación, otra opción es copiar la base de datos del nodo de administración principal en el nuevo nodo de administración. Copiar la base de datos le permite conservar información histórica sobre atributos, alertas y alertas. 
---
= Copie la base de datos del nodo de administrador
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al añadir nodos de administrador mediante un procedimiento de ampliación, otra opción es copiar la base de datos del nodo de administración principal en el nuevo nodo de administración. Copiar la base de datos le permite conservar información histórica sobre atributos, alertas y alertas.

.Antes de empezar
* Completó los pasos de ampliación necesarios para añadir un nodo de administrador.
* Tiene el `Passwords.txt` archivo.
* Tiene la clave de acceso de aprovisionamiento.


.Acerca de esta tarea
El proceso de activación del software StorageGRID crea una base de datos vacía para el servicio NMS en el nodo de administración de expansión. Cuando el servicio NMS se inicia en el nodo de administración de expansión, registra información para servidores y servicios que actualmente forman parte del sistema o que se agregan más tarde. Esta base de datos de Admin Node incluye la siguiente información:

* Historial de alertas
* Datos de atributos históricos, que se utilizan en los gráficos de estilo heredado de la página Nodos


Para garantizar que la base de datos Admin Node sea coherente entre los nodos, se puede copiar la base de datos del nodo de administración principal en el nodo de administración de expansión.


NOTE: Copiar la base de datos desde el nodo de administración principal (el nodo________Source Admin) en un nodo de administración de expansión puede tardar hasta varias horas en completarse. Durante este período, no se puede acceder a Grid Manager.

Siga estos pasos para detener el servicio MI y el servicio API de administración tanto en el nodo de administración principal como en el nodo de administración de expansión antes de copiar la base de datos.

.Pasos
. Complete los siguientes pasos en el nodo de administración principal:
+
.. Inicie sesión en el nodo de administrador:
+
... Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a raíz: `su -`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


.. Ejecute el siguiente comando: `recover-access-points`
.. Introduzca la clave de acceso de aprovisionamiento.
.. Detenga el servicio MI: `service mi stop`
.. Detenga el servicio Management Application Program Interface (mgmt-api): `service mgmt-api stop`


. Complete los siguientes pasos en el nodo de administrador de ampliación:
+
.. Inicie sesión en el nodo de administrador de ampliación:
+
... Introduzca el siguiente comando: `ssh admin@_grid_node_IP_`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.
... Introduzca el siguiente comando para cambiar a raíz: `su -`
... Introduzca la contraseña que aparece en el `Passwords.txt` archivo.


.. Detenga el servicio MI: `service mi stop`
.. Detenga el servicio mgmt-api: `service mgmt-api stop`
.. Añada la clave privada SSH al agente SSH. Introduzca:``ssh-add``
.. Introduzca la contraseña de acceso SSH que aparece en `Passwords.txt` el archivo.
.. Copie la base de datos del nodo de administración de origen en el nodo de administración de expansión: `/usr/local/mi/bin/mi-clone-db.sh _Source_Admin_Node_IP_`
.. Cuando se le solicite, confirme que desea sobrescribir la base DE datos MI en el nodo de administración de expansión.
+
La base de datos y sus datos históricos se copian en el nodo de administración de expansión. Una vez que finaliza la operación de copia, el script inicia el nodo de administración de expansión.

.. Cuando ya no necesite un acceso sin contraseñas a otros servidores, quite la clave privada del agente SSH. Introduzca:``ssh-add -D``


. Reinicie los servicios en el nodo de administración principal: `service servermanager start`

