---
permalink: troubleshoot/troubleshooting-lost-and-missing-object-data.html 
sidebar: sidebar 
keywords: how to troubleshoot lost object data, how to troubleshoot missing object data 
summary: Los objetos se pueden recuperar por varios motivos, incluidas las solicitudes de lectura de una aplicación cliente, las verificaciones en segundo plano de los datos de objetos replicados, las reevaluaciones de ILM y la restauración de los datos de objetos durante la recuperación de un nodo de almacenamiento. 
---
= Solucionar problemas de datos de objetos perdidos o faltantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Los objetos se pueden recuperar por varios motivos, incluidas las solicitudes de lectura de una aplicación cliente, las verificaciones en segundo plano de los datos de objetos replicados, las reevaluaciones de ILM y la restauración de los datos de objetos durante la recuperación de un nodo de almacenamiento.

El sistema StorageGRID utiliza información de ubicación en los metadatos de un objeto para determinar desde qué ubicación recuperar el objeto.  Si no se encuentra una copia del objeto en la ubicación esperada, el sistema intenta recuperar otra copia del objeto desde otra parte del sistema, asumiendo que la política ILM contiene una regla para hacer dos o más copias del objeto.

Si esta recuperación es exitosa, el sistema StorageGRID reemplaza la copia faltante del objeto.  De lo contrario, se activa la alerta *Objetos potencialmente perdidos*, de la siguiente manera:

* En el caso de las copias replicadas, si no se puede recuperar otra copia, el objeto se considera perdido y se activa la alerta.
* En el caso de las copias con código de borrado, si no se puede recuperar una copia de la ubicación esperada, el atributo Copias dañadas detectadas (ECOR) aumenta en uno antes de intentar recuperar una copia de otra ubicación. Si no se encuentra ninguna otra copia, se activa la alerta.


Debe investigar todas las alertas de *Objetos potencialmente perdidos* inmediatamente para determinar la causa raíz de la pérdida y si el objeto aún podría existir en un nodo de almacenamiento fuera de línea o que no esté disponible en ese momento. Ver link:../troubleshoot/investigating-potentially-lost-objects.html["Investigar objetos potencialmente perdidos"] .  Es posible que se activen falsas alertas de objetos perdidos como medida de precaución.

En el caso de que se pierdan datos de objetos sin copias, no existe solución de recuperación.  Sin embargo, debeslink:../troubleshoot/investigating-potentially-lost-objects.html#reset-lost-obj-count["Restablecer el contador de objetos potencialmente perdidos"] para evitar que los objetos perdidos conocidos enmascaren nuevos objetos perdidos.
