---
permalink: ilm/enabling-s3-object-lock.html 
sidebar: sidebar 
keywords: enable s3 object lock, object lock 
summary: Si una cuenta de inquilino de S3 tiene que cumplir con los requisitos de normativa al guardar datos de objetos, debe habilitar el bloqueo de objetos de S3 para todo el sistema StorageGRID. Al habilitar el ajuste global de bloqueo de objetos de S3, cualquier usuario inquilino de S3 puede crear y gestionar bloques y objetos con S3 Object Lock. 
---
= Habilita S3 Object Lock en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si una cuenta de inquilino de S3 tiene que cumplir con los requisitos de normativa al guardar datos de objetos, debe habilitar el bloqueo de objetos de S3 para todo el sistema StorageGRID. Al habilitar el ajuste global de bloqueo de objetos de S3, cualquier usuario inquilino de S3 puede crear y gestionar bloques y objetos con S3 Object Lock.

.Antes de empezar
* Usted tiene el link:../admin/admin-group-permissions.html["Permiso de acceso raíz"].
* Ha iniciado sesión en Grid Manager mediante una link:../admin/web-browser-requirements.html["navegador web compatible"].
* Ha revisado el flujo de trabajo de bloqueo de objetos de S3 y comprende las consideraciones.
* Has confirmado que la regla predeterminada de la política de ILM activa cumple con los requisitos. Consulta link:creating-default-ilm-rule.html["Cree una regla de ILM predeterminada"] para más detalles.


.Acerca de esta tarea
Un administrador de grid debe habilitar la configuración global de bloqueo de objetos S3 para permitir a los usuarios inquilinos crear nuevos bloques con el bloqueo de objetos S3 habilitado. Una vez habilitada esta configuración, no se puede desactivar.

Después de habilitar S3 Object Lock, un administrador del grid también puede permitir que los usuarios inquilinos habiliten S3 Object Lock en un bucket existente. Después de que un administrador del grid habilite esta configuración, puede deshabilitarla. Para más información, consulta link:requirements-for-s3-object-lock.html#s3-object-lock-existing-buckets["Requisitos de S3 Object Lock"].

Revise la configuración de cumplimiento de los arrendatarios existentes después de activar la configuración global S3 Object Lock. Cuando habilita esta opción, la configuración de bloqueo de objetos por inquilino de S3 depende de la versión de StorageGRID en el momento en que se creó el inquilino.


NOTE: La configuración global de Compliance ha quedado obsoleta. Si activaste esta configuración usando una versión anterior de StorageGRID, la configuración de S3 Object Lock se activa automáticamente. Puedes seguir usando StorageGRID para gestionar la configuración de los buckets conformes existentes; sin embargo, no puedes crear nuevos buckets conformes. Para más detalles, consulta https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["Base de conocimientos de NetApp: Cómo gestionar bloques heredados que cumplen con la normativa StorageGRID 11.5"^].

.Pasos
. Seleccione *Configuración* > *Sistema* > *Bloqueo de objetos S3*.
+
Se muestra la página S3 Object Lock Settings.

. Selecciona *Habilitar S3 Object Lock* para habilitar S3 Object Lock en todo tu sistema StorageGRID.
. Si lo deseas, selecciona *Permitir que se active S3 Object Lock en los buckets existentes*.
+

CAUTION: Habilitar S3 Object Lock en un bucket existente podría provocar una migración involuntaria de datos desde un Cloud Storage Pool de vuelta a StorageGRID, dependiendo de tus reglas de ILM. No puedes detener esta migración una vez que comienza. Para más información, consulta link:requirements-for-s3-object-lock.html#s3-object-lock-existing-buckets["Requisitos de S3 Object Lock"].

. Seleccione *aplicar*.
+
Aparece un cuadro de diálogo de confirmación que le recuerda que no puede desactivar el bloqueo de objetos S3 después de que esté habilitado.

. Si está seguro de que desea activar de forma permanente el bloqueo de objetos S3 para todo el sistema, seleccione *Aceptar*.
+
Al seleccionar *Aceptar*:

+
** Si la regla predeterminada de la política de ILM activa es compatible, S3 Object Lock ahora está habilitado para toda la cuadrícula y no se puede deshabilitar.
** Si la regla predeterminada no cumple los requisitos, aparece un error. Debes crear y activar una nueva política de ILM que incluya una regla que cumpla los requisitos como regla predeterminada. Selecciona *OK*. Luego, crea una nueva política, simúlala y actívala. Consulta link:creating-ilm-policy.html["Cree una política de ILM"] para obtener instrucciones.



