---
permalink: ilm/resolving-consistency-errors-when-updating-bucket-s3-object-lock-configuration.html 
sidebar: sidebar 
keywords: consistency error, s3 object lock and consistency 
summary: Si un sitio de centro de datos o varios nodos de almacenamiento de un sitio no están disponibles, es posible que deba ayudar a los usuarios inquilinos S3 a aplicar los cambios en la configuración del bloqueo de objetos S3 o del cumplimiento heredado. 
---
= Resuelva los errores de coherencia al actualizar la configuración de bloqueo de objetos de S3 o cumplimiento heredado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un sitio de centro de datos o varios nodos de almacenamiento de un sitio no están disponibles, es posible que deba ayudar a los usuarios inquilinos S3 a aplicar los cambios en la configuración del bloqueo de objetos S3 o del cumplimiento heredado.

Los usuarios inquilinos que tienen bloques con S3 Object Lock (o Legacy Compliance) habilitado pueden cambiar ciertas opciones. Por ejemplo, es posible que un usuario arrendatario que utilice el bloqueo de objetos S3 deba poner una versión de objeto en retención legal.

Cuando un usuario tenant actualiza la configuración de un bloque de S3 o una versión de objeto, StorageGRID intenta actualizar inmediatamente los metadatos del objeto o el bloque en el grid. Si el sistema no puede actualizar los metadatos porque no hay disponibles un sitio de centro de datos o varios nodos de almacenamiento, devuelve un error:

[listing]
----
503: Service Unavailable
Unable to update compliance settings because the settings can't be consistently applied on enough storage services. Contact your grid administrator for assistance.
----
Para resolver este error, siga estos pasos:

. Se debe intentar que todos los nodos o sitios de almacenamiento estén disponibles de nuevo Lo antes posible..
. Si no puede dejar suficientes nodos de almacenamiento en cada sitio disponible, póngase en contacto con el soporte técnico, que puede ayudarle a recuperar nodos y asegurarse de que los cambios se apliquen de manera coherente en la cuadrícula.
. Una vez resuelto el problema subyacente, recuerde al usuario inquilino que vuelva a intentar cambiar sus cambios de configuración.


.Información relacionada
* link:../tenant/index.html["Usar una cuenta de inquilino"]
* link:../s3/index.html["USE LA API DE REST DE S3"]
* link:../maintain/index.html["Recuperación y mantenimiento"]

