---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: Un grupo de almacenamiento en la nube te permite utilizar ILM para trasladar datos de objetos fuera de tu sistema StorageGRID. Por ejemplo, podrías querer trasladar objetos a los que se accede con poca frecuencia a un almacenamiento en la nube de menor coste, como Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud o el nivel de acceso Archive en Microsoft Azure Blob Storage. O podrías querer mantener una copia de seguridad en la nube de los objetos de StorageGRID para mejorar la recuperación ante desastres. 
---
= Conoce los Cloud Storage Pools en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un grupo de almacenamiento en la nube te permite utilizar ILM para trasladar datos de objetos fuera de tu sistema StorageGRID. Por ejemplo, podrías querer trasladar objetos a los que se accede con poca frecuencia a un almacenamiento en la nube de menor coste, como Amazon S3 Glacier, S3 Glacier Deep Archive, Google Cloud o el nivel de acceso Archive en Microsoft Azure Blob Storage. O podrías querer mantener una copia de seguridad en la nube de los objetos de StorageGRID para mejorar la recuperación ante desastres.

Desde el punto de vista de ILM, un grupo de almacenamiento en la nube es similar a un grupo de almacenamiento. Para almacenar objetos en cualquiera de las ubicaciones, seleccionas el grupo al crear las instrucciones de ubicación para una regla de ILM. Sin embargo, mientras que los grupos de almacenamiento están formados por nodos de almacenamiento dentro del sistema StorageGRID, un grupo de almacenamiento en la nube está formado por un bucket externo (S3) o un contenedor (Azure Blob Storage).

La tabla compara los pools de almacenamiento con los pools de almacenamiento en cloud y muestra las similitudes y las diferencias a alto nivel.

[cols="1a,2a,5a"]
|===
|  | Del banco de almacenamiento | Pool de almacenamiento en cloud 


 a| 
¿Cómo se crea?
 a| 
Uso de la opción *ILM* > *agrupaciones de almacenamiento* en Grid Manager.
 a| 
Usando la opción *ILM* > *Storage Pools* > *Cloud Storage Pools* en Grid Manager.

Debe configurar el bloque o contenedor externo para poder crear el Cloud Storage Pool.



 a| 
¿Cuántos pools se pueden crear?
 a| 
Ilimitada.
 a| 
Hasta 10.



 a| 
¿Dónde se almacenan los objetos?
 a| 
En uno o más nodos de almacenamiento en StorageGRID.
 a| 
En un bucket de Amazon S3, un contenedor de Azure Blob Storage o en Google Cloud que sea externo al sistema StorageGRID.

Si Cloud Storage Pool es un bloque de Amazon S3:

* Opcionalmente, se puede configurar un ciclo de vida de bloque para pasar los objetos a un almacenamiento a largo plazo de bajo coste, como Amazon S3 Glacier o S3 Glacier Deep Archive. El sistema de almacenamiento externo debe admitir la clase de almacenamiento Glacier y la API S3 RestoreObject.
* Puede crear pools de almacenamiento en el cloud para usarlos con los servicios de cloud comercial (C2S) de AWS, compatibles con la región secreta de AWS.


Si el Cloud Storage Pool es un contenedor de Azure Blob Storage, StorageGRID traslada el objeto al nivel de archivo.

*Nota:* En general, no configures la gestión del ciclo de vida de Azure Blob Storage para el contenedor utilizado para un Cloud Storage Pool. RestoreObject operations en los objetos en el Cloud Storage Pool pueden verse afectadas por el ciclo de vida configurado.



 a| 
¿Qué controla la ubicación de objetos?
 a| 
Una regla de ILM en las políticas de ILM activas.
 a| 
Una regla de ILM en las políticas de ILM activas.



 a| 
¿Qué método de protección de datos se utiliza?
 a| 
Codificación de replicación o borrado.
 a| 
Replicación.



 a| 
¿Cuántas copias de cada objeto se permiten?
 a| 
Múltiples.
 a| 
Una copia en el pool de almacenamiento cloud y, opcionalmente, una o varias copias en StorageGRID.

*Nota:* No puedes almacenar un objeto en más de un Pool de almacenamiento en la nube en un momento dado.



 a| 
¿Cuáles son las ventajas?
 a| 
Los objetos son accesibles rápidamente en cualquier momento.
 a| 
Almacenamiento de bajo coste.

*Nota*: Los datos de FabricPool no se pueden organizar en niveles en los grupos de almacenamiento en la nube.

|===