---
permalink: release-notes/changes-to-tenant-management-api.html 
sidebar: sidebar 
keywords: tenant management api, api, api version, swagger, rest api 
summary: StorageGRID 12.1 utiliza la versión 4 de la Tenant Management API. La versión 4 deja obsoleta la versión 3. Sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles. 
---
= Cambios en la API de gestión de inquilinos en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 utiliza la versión 4 de la Tenant Management API. La versión 4 deja obsoleta la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles.


NOTE: Puedes seguir utilizando las versiones obsoletas de la API de gestión de inquilinos con StorageGRID; sin embargo, el soporte para estas versiones de la API se eliminará en una futura versión de StorageGRID. Después de actualizar a StorageGRID 12.0 o una versión posterior, puedes desactivar las API obsoletas usando la API  `PUT /grid/config/management`.

Para obtener más información, vaya a link:../tenant/understanding-tenant-management-api.html["Conozca la API de gestión de inquilinos"].



[[new-api-for-object-replication]]
== Nueva API para la replicación de objetos

Puedes utilizar el `/org/cross-grid-replication/{versionId}/replicate` API para replicar manualmente objetos en un depósito existente que tiene replicación entre redes recién configurada.
