---
permalink: release-notes/changes-to-grid-management-api.html 
sidebar: sidebar 
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: StorageGRID 12.1 utiliza la versión 4 de la API de gestión de Grid. La versión 4 deja obsoleta la versión 3. Sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles. 
---
= Cambios en la API de gestión de Grid en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 12.1 utiliza la versión 4 de la API de gestión de Grid. La versión 4 deja obsoleta la versión 3; sin embargo, las versiones 1, 2 y 3 siguen siendo compatibles.


NOTE: Puedes seguir utilizando versiones obsoletas de la API de gestión con StorageGRID; sin embargo, el soporte para estas versiones de la API se eliminará en una futura versión de StorageGRID. Tras actualizar a StorageGRID 12.0 o una versión posterior, puedes desactivar las API obsoletas mediante la  `PUT /grid/config/management` API.

Para obtener más información, vaya a link:../admin/using-grid-management-api.html["Utilice la API de gestión de grid"].



[[new-endpoints-for-changing-the-bmc-password-and-lan-ip-settings]]
== Nuevos endpoints para cambiar la contraseña de BMC y la configuración de la IP de la LAN

Se ha añadido el siguiente endpoint para que puedas link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password["cambiar la contraseña BMC de un appliance"].

`PUT /bmc-configuration/root-password`

Se han añadido los siguientes puntos finales para que puedas link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings["modificar o consultar la configuración de la IP de la LAN de BMC"].

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`
