---
permalink: release-notes/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: Infórmate sobre las funciones y capacidades que se han eliminado o que han quedado obsoletas en StorageGRID 12.1.0. Antes de actualizar, comprueba si alguna de las funciones eliminadas u obsoletas afecta a tus aplicaciones cliente o a la configuración de tu grid. 
---
= Funciones y capacidades eliminadas o en desuso en StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Infórmate sobre las funciones y capacidades que se han eliminado o que han quedado obsoletas en StorageGRID 12.1.0. Antes de actualizar, comprueba si alguna de las funciones eliminadas u obsoletas afecta a tus aplicaciones cliente o a la configuración de tu grid.



[[definitions]]
== Definiciones

Anticuado:: *No debes* utilizar esta función en nuevos entornos de producción. Los entornos de producción ya existentes pueden seguir utilizando esta función.
Fin de la vida:: Última versión enviada que admite la función. En algunos casos, la documentación de la característica puede eliminarse en esta etapa.
Quitada:: Primera versión que *no* soporta la característica.




[[storagegrid-end-of-feature-support]]
== Compatibilidad con fin de funciones de StorageGRID

Las funciones obsoletas se eliminarán en las versiones principales N+2. Por ejemplo, si una característica está obsoleta en la versión N (por ejemplo, 6,3), la última versión en la que existirá la característica es N+1 (por ejemplo, 6,4). La versión N+2 (por ejemplo, 6,5) es la primera versión cuando la función no existe en el producto.

Consulte la https://mysupport.netapp.com/site/info/version-support["Soporte de la versión del software"^] para obtener información adicional.


NOTE: En ciertas situaciones, NetApp podría terminar el soporte para determinadas funciones antes de lo indicado.

[cols="2a,1a,1a,1a,3a"]
|===
| Función | Anticuado | Fin de la vida | Quitada | Enlaces a documentación anterior 


 a| 
Configuración global de SSE para el cifrado AES-128
 a| 
12,1
 a| 
12,2
 a| 
12,3
 a| 
A partir de StorageGRID 12.1.0, la compatibilidad con el cifrado AES-128 de los nuevos datos de objetos almacenados en reposo está obsoleta. La compatibilidad para la recuperación de objetos almacenados que se cifraron originalmente con AES-128 continúa.



 a| 
Alarmas, heredadas (_no Alertas_)
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["Referencia de alarmas (StorageGRID 11,8)"^]



 a| 
Soporte para nodos de archivado
 a| 
11,7
 a| 
11,8
 a| 
11,9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["Consideraciones sobre el desmantelamiento de nodos de archivado (StorageGRID 11,8)"^]

*Nota*: Antes de comenzar tu actualización, debes:

. Decomisiona todos los nodos de archivo. Consulta https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["Retirada de nodo de grid (sitio de documentación de StorageGRID 11,8)"^].
. Elimina todas las referencias a los nodos de archivo de los grupos de almacenamiento y las políticas de ILM. Consulta https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["Base de conocimientos de NetApp: Guía de resolución de actualización de software de StorageGRID 11,9"^].




 a| 
Auditar la exportación a través de CIFS/Samba
 a| 
11,1
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Servicio CLB
 a| 
11,4
 a| 
11,6
 a| 
11,7
 a| 



 a| 
Motor de contenedor Docker
 a| 
11,8
 a| 
11,9
 a| 
POR CONFIRMAR
 a| 
La compatibilidad con Docker como motor de contenedores para implementaciones de solo software está obsoleta.  Docker será reemplazado por otro motor de contenedores en una versión futura.  Consulte lalink:../swnodes/software-requirements.html["Requisitos de software para nodos basados en software"] para obtener una lista de las versiones de Docker compatibles actualmente.



 a| 
Configuración del correo electrónico (legacy)
 a| 
11,9
 a| 
12,0
 a| 
12,1
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/managing-alarms.html#configure-notifications-for-alarms-legacy-system["Configura notificaciones para alarmas (sistema heredado) (StorageGRID 11.8)"^]



 a| 
Exportación de auditoría NFS
 a| 
11,8
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["Configure el acceso del cliente de auditoría para NFS (StorageGRID 11,8)."^]



 a| 
Reasignación de puertos
 a| 
12,0
 a| 
12,1
 a| 
12,2
 a| 



 a| 
Soporte para API Swift
 a| 
11,7
 a| 
11,9
 a| 
12,0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["Usar la API REST DE Swift (StorageGRID 11,8)"^]



 a| 
RHEL 8,8
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9,0
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
RHEL 9,2
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Sistema operativo Ubuntu 18,04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Sistema operativo Ubuntu 20,04
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 



 a| 
Debian 11
 a| 
11,9
 a| 
11,9
 a| 
12,0
 a| 

|===
Consulte también:

* link:changes-to-grid-management-api.html["Cambios en la API de gestión de grid"]
* link:changes-to-tenant-management-api.html["Cambios en la API de gestión de inquilinos"]

