---
permalink: fabricpool/other-best-practices-for-storagegrid-and-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, best practices, audit log, encryption, compressions, tiering, ontap, consistency 
summary: Al configurar un sistema StorageGRID para utilizarlo con FabricPool, es posible que deba cambiar otras opciones de StorageGRID. Antes de cambiar una configuración global, considere cómo afectará el cambio a otras aplicaciones S3. 
---
= Otras prácticas recomendadas para StorageGRID y FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Al configurar un sistema StorageGRID para utilizarlo con FabricPool, es posible que deba cambiar otras opciones de StorageGRID. Antes de cambiar una configuración global, considere cómo afectará el cambio a otras aplicaciones S3.



== Destinos de registro y mensajes de auditoría

Las cargas de trabajo de FabricPool suelen tener una tasa alta de operaciones de lectura, las que pueden generar un alto volumen de mensajes de auditoría.

* Si no necesita un registro de operaciones de lectura de cliente para FabricPool o cualquier otra aplicación S3, vaya opcionalmente a *CONFIGURACIÓN* > *Monitoreo* > *Servidor de auditoría y syslog*. Cambie la configuración de *Lecturas de cliente* a *Error* para disminuir el número de mensajes de auditoría registrados en el registro de auditoría. Consulte link:../monitor/configure-audit-messages.html["Configure los mensajes de auditoría y el servidor de syslog externo"] para obtener más información.
* Si tiene un grid grande, utilice varios tipos de aplicaciones S3 o desea conservar todos los datos de auditoría, configure un servidor syslog externo y guarde la información de auditoría de forma remota. El uso de un servidor externo minimiza el impacto en el rendimiento del registro de mensajes de auditoría sin reducir la integridad de los datos de auditoría. Consulte link:../monitor/considerations-for-external-syslog-server.html["Consideraciones sobre el servidor de syslog externo"] para obtener más información.




== Cifrado de objetos

Al configurar StorageGRID, puede habilitar opcionalmente el link:../admin/changing-network-options-object-encryption.html["opción global para el cifrado de objetos almacenados"]cifrado de datos IF necesario para otros clientes StorageGRID. Los datos organizados en niveles desde FabricPool a StorageGRID ya están cifrados, por lo que no es necesario habilitar la configuración de StorageGRID. Las claves de cifrado en el cliente son propiedad de ONTAP.



== Compresión de objetos

Al configurar StorageGRID, no active el link:../admin/configuring-stored-object-compression.html["opción global para comprimir objetos almacenados"]. Los datos que se organizan en niveles de FabricPool a StorageGRID ya están comprimidos. El uso de la opción StorageGRID no reducirá más el tamaño de un objeto.



== Consistencia del cucharón

Para los depósitos de FabricPool, la consistencia del cucharón recomendada es *Read-after-new-write*, que es la consistencia predeterminada para un nuevo cucharón. No edites cubos de FabricPool para usar *available* o *strong-site*.



== Organización en niveles de FabricPool

Si un nodo de StorageGRID utiliza almacenamiento asignado desde un sistema ONTAP de NetApp, confirme que el volumen no tiene una política de organización en niveles de FabricPool habilitada. Por ejemplo, si un nodo StorageGRID se ejecuta en un host VMware, asegúrese de que el volumen que realiza el backup del almacén de datos para el nodo StorageGRID no tenga habilitada una política de organización en niveles de FabricPool. Al deshabilitar el almacenamiento en niveles de FabricPool para los volúmenes que se usan con los nodos StorageGRID, se simplifica la solución de problemas y las operaciones de almacenamiento.


CAUTION: No utilice nunca FabricPool para colocar en niveles datos relacionados con StorageGRID en el propio StorageGRID. La organización en niveles de los datos de StorageGRID en StorageGRID aumenta la solución de problemas y la complejidad operativa.
